### PR TITLE
WIP : Handle Doze entry, exit and maintenance windows

### PR DESCRIPTION
**Pull request by rhari991**
PR #2545 restarts push and poll when exiting from Doze back to either normal functioning or a maintenance window. This PR makes the following changes 

- stops both push and poll when entering Doze mode
- trigger a single poll when entering a maintenance window
- restart push and poll when exiting from Doze

Related discussion - #857

### CODE REVIEW

**Comment by cketti** [comment]
Please add a description to every pull request. What motivated this change? What problem are you trying to solve?

I'll have to dig up my notes. But I believe there was a reason I didn't change the code to stop the pushers when creating PR #2545.

**Comment by rhari991** [comment]
@cketti Sorry about that. There are still some cases I think where this does not start the pushers correctly / performs more than one poll in a maintenance window. I have not tested this thoroughly.

**Comment by philipwhiuk** [comment]
I'm reluctant to approve changes that could stop push email and not restart it. The problem is that from the user's perspective they probably have to restart their device to fix it, which is not great UX. I think I'll let @cketti look at his notes here.

**Comment by cketti** [comment]
I can't find my notes. But I believe I didn't stop the pushers when entering Doze because I couldn't find out how to distinguish between 'deep doze' and 'light doze'. Light doze seems to be much more frequent and maintenance windows closer together. I believe it's quite possible for an IDLE connection to survive a light doze period. Always stopping pushers would probably lead to more network traffic than necessary.

I'm inclined to keep the current code for now. If we want to target API 26 at some point we'll need to change  the code anyway (see [Background Execution Limits](https://developer.android.com/preview/features/background.html)). And once we use a foreground service for the push functionality we don't have to worry about Doze restrictions.

**Pull request closed without merging**
