### PR TITLE
Spelling: String rework

### PR DESCRIPTION
**Pull request by comradekingu**
Fixes all Transifex issues, except for pluralization of strings, and those that are specific to French.
Big thank you to yahoe.001 and jony08 for reporting issues :)

### CODE REVIEW

**Comment by philipwhiuk** [comment]
Most of these are choices not bugs. 

For `Email` vs `E-mail` https://www.grammarly.com/blog/spelling-e-mail-email/

**Comment by comradekingu** [comment]
@philipwhiuk While that is true, it is a choice that makes for fewer errors in translation, seeing as variants of "email" are considered erroneous in other languages. Every project that i have ever checked, the pattern of introducing errors emerges.

"E-mail" is the classical spelling in English, so it is considered the least problematic there.

**Comment by philipwhiuk** [comment]
I linked to an article - the project has long used email. Erroneous translations is not a reason to change another language. The other translations can just be fixed.

In addition to those:

Tagline for Gmail:

> Gmail is email that's intuitive, efficient, and useful.

Tagline for Outlook

> Outlook.com - Microsoft free personal email

Tagline for Yahoo

> Yahoo Mail - Free email with 1,000 GB of storage

**Comment by philipwhiuk** [comment]
Oh and if we merge this we also need to go through 

* The website, most notably the title: https://k9mail.github.io/
* The Google Play description: https://play.google.com/store/apps/details?id=com.fsck.k9&hl=en_GB
*  F-Droid is actually using both - https://f-droid.org/en/packages/com.fsck.k9/
* Amazon Appstore uses e-mail - https://www.amazon.co.uk/K-9-Dog-Walkers-Mail/dp/B004JK61K0

**Comment by comradekingu** [comment]
@philipwhiuk https://github.com/k9mail/k9mail.github.io/pull/65

**Comment by cketti** [comment]
I'm with @philipwhiuk. Switching from "email" to "e-mail" is not something I want to do.

**Comment by comradekingu** [comment]
@cketti Nor do you have to, your offered choice in the matter is over implementing _one_ of the currently 4 different ways to spell e-mail. The first one of which, is argued to supposedly be important…?

Meanwhile I can confirm that it is also erroneous in other languages, and I would argue K-9 Mail indeed also exists in those other languages…

There are no takers in the matter of the hyptotetically "can be fixed", so in this scenario fixing the problem at one end, means it just takes care of itself downstream, provided some time for people to se the update.

If a first issue featuring a pletora of fixes, only is argued irrelevant over a valid and consistent way to spell e-mail, it doesn't bode well for the language of the K-9 Mail in any respects.

**Comment by philipwhiuk** [comment]
A valid and consistent way is to stick with the one we picked, which is email. I didn't point out all the places we spelled it consistently to get you to raise another dozen PRs. I did it to point out we have a standard, `email` and I backed it up with industry usage. I also pointed out you should have raised an issue. You said you did it based on feedback from two other people - why are they reporting issues to you, not us?

**All** of the changes in this PR are about your personal view of what K-9 is and personal grammar choices, not any common standard, use of Oxford commas.

Frankly it's bike-shedding and it's not helpful.

 'libre' (which is unclearly defined and might be the same as 'free') vs 'open source' is a world of complexity I really don't want to get into. 

> means it just takes care of itself downstream

Honestly, I'm not too interested in spending time helping forks. Besides the whole point of forks is you can change whatever strings you like.

```
-CloudBees' [FOSS program](https://www.cloudbees.com/resources/foss) allows us to use their DEV@cloud service for free.
 +CloudBees' [FOSS program](https://www.cloudbees.com/resources/foss) offers us gratis use of their DEV@cloud service.
```

There's no technical or grammatical reason to change this. `gratis` is less common and less clear.

If you want your downstream fork to be more professional, change it downstream.

The only change I have seen that's completely non controversial is the use of https in a link.

**Comment by comradekingu** [comment]
I meant translations downstream, internally if you will. They, and others, report issues on the translation platform used by K-9 Mail. None of which seem to have been given any attention. Outside of me thanking them and bringing it here. The irrelevant ones are largely mine, which still means I see the same improvements elsewhere. You have gone from "most of" to "all", so i am hoping for a variation upon this theme.

The tree still falls in the woods, even if not officially.
With current rules in English for e-mail/email, grammatically only consistency matters. In my head the actual strings users see, is more of what constitutes _grammatical_, rather than choices developers thought to have made. Insofar that it is also of greater concern than which of the two valid ways are employed elsewhere. The language I translate to is consistent, and i tried to extend that care to others in this regard.
I accept the decision to be logically consistent, but practically counterproductive.

Valid consistency is just as redundant as 100% free.

To specify, I seem to have avoided "free" on autopilot, for reasons it is problematic in the software sense, but it shortened the sentence. Irrelevant change.
Libre, in English, qualifying "software" is not unclearly defined, and was invented precisely because it isn't ambiguous. You don't get into the complexity of when open source differs, by not using open source where it strictly doesn't apply over free/libre software.
Matters compound words and qualifying aside, (which libre software solves) "100% free and open source" is as complex as it possibly could be.

**Pull request closed without merging**
