### PR TITLE
PgpData unit tests

### PR DESCRIPTION
**Pull request by vcaulier**
Beginning the crypto package tests.
And starting with PgpData tests (seen as uncovered with Jenkins).

However, I don't know how to integrate the test to the gradle build,
will do it next.

### CODE REVIEW

**Comment by artbristol** [comment]
PgpData is just a DTO. IMHO, a unit "test" is just overhead.

The only method that is vaguely worth testing is hasEncryptionKeys

**Comment by dschuermann** [comment]
Sry that you made this effort, but PgpData will be removed in future versions. It already is partially gone in the pgp preparations branch.

**Comment by vcaulier** [comment]
Ok, but at least, its a way to better understand the code.
Do you have any advice on which classes should be tested ?

**Comment by dschuermann** [comment]
If you want to create tests for PGP, please contact cketti on the mailinglist and look into https://github.com/k9mail/k-9/tree/pgp_mime_preparations

**Comment by vcaulier** [comment]
Ok, thank you; I will look for that.

**Pull request closed without merging**
