### PR TITLE
Fix email domain to handle a dotted quad address.

### PR DESCRIPTION
**Pull request by benkibbey**

### CODE REVIEW

**Comment by philipwhiuk** [comment]
`isQuad` is not really very explanatory. What you really mean I assume is, `isIPv4Address`.

The regex for that is: `^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$`

Your regex will match `0000.2.4.5.3.6.`

We should exclude IPv6 too at some point here as well e.g. `[12:123:231::1]`

What we really want is `isDomain`

Unfortunately checking for actual domain names is impractical (what with gTLDs and iTLDs). Almost all regex's on the internet for this are wrong (notably the ones with lots of upvotes on StackOverflow).

**Comment by benkibbey** [comment]
> `isQuad` is not really very explanatory. What you really mean I assume
> is, `isIPv4Address`.

Yes, that is what I meant. I've seen the term "dotted quad address" so I
figured I'd use it, too.

> The regex for that is: `^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$`
> 
> Your regex will match `0000.2.4.5.3.6.`

I know it isn't a catch-all regex but I also don't think it needs to be
since anything else would be a typo in the address and returned as an
error from the resolver. If one were to mis-type the address then a
"mail." would be prepended. Unless I'm missing something.

> We should exclude IPv6 too at some point here as well e.g. `[12:123:231::1]`

Definately.

> What we really want is `isDomain`
> 
> Unfortunately checking for actual domain names is impractical (what
> with gTLDs and iTLDs). Almost all regex's on the internet for this are
> wrong (notably the ones with lots of upvotes on StackOverflow).

I think the simpler the better. Adding '[' and ':' to my patch would be,
I think, enough to parse the host. Then let the resolver return an error,
if any.

**Comment by cketti** [comment]
The whole functionality probably wants to be extracted to a `ServerNameSuggester` class. Input arguments should be the email domain and the account/server type. So "example.com" + POP3/incoming could e.g. suggest "pop3.example.com".

**Comment by cketti** [comment]
When setting up a new account we don't allow users to enter email addresses containing IP addresses in the domain part (e.g. `user@[10.0.0.1]` or `user@[IPv6:2001:db8::1]`).

Until that is changed there's no point in fixing the name suggestion for incoming and outgoing servers.

**Pull request closed without merging**
