### PR TITLE
Fixed localized strings if app language and system language are different

### LINKED ISSUE #4407: Localized strings fail
Persian translation is fully done via transifex and it works properly while device language is set to Persian. But when device language is set to English and app language is set to Persian, some strings still are English.

### Expected behavior
Regardless of device language, all strings be in Persian (selected via app setting)

### Actual behavior
Some strings are English and some Persian.

### Steps to reproduce
1. Set device language to English.
2. Set app language to Persian.
3. Exit app.
4. Open app.
5. Some strings are english. For example:
5.1. "load up to 10 more" at bottom of screen
5.2. "inbox" and "outbox" in left menu
5.3. try to compose a new mail, then title "Compose" is in English. Also tap 3 dots menu, all items under it are English.
5.4. tap back to leave compose. Then tap pencil icon to open "compose" again.  It's now in Persian.
5.5. Go to settings. Choose an account setting. Go to Fetch mail. Then go to incoming server setting. Title of dialog is English.

### Environment
K-9 Mail version: 5.703

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Please take some time to retrieve logs and attach them here.

For steps 5.3 - 5.4:

[K9log.txt](https://github.com/k9mail/k-9/files/4002776/K9log.txt)

### PR DESCRIPTION
**Pull request by plan3d**
Resolves #4407

### CODE REVIEW

**Comment by cketti** [comment]
This feels like you're trying to fix a lot of problems in one pull request. Can you please pick one problem at a time and create a PR to fix that? Please also add a description to describe the problem you're solving.

**Comment by plan3d** [comment]
The commits resolve the following small issues:
1. Wrong title of incoming server settings (see issue description 5.5)
2. Quotation of answers or forwarded messages (see issue description 5.6 and 5.7)
3. Wrong title of unified inbox on startup
4. Wrong title of unified inbox after K9 language has changed
5. Wrong title on new account setup
6. Removing dead code

I can split my commits in six pull requests, each referencing issue 4407. Would you prefer that?

**Comment by cketti** [comment]
Yes, it's easier to deal with one issue at a time. You can group the ones that can be fixed using `Activity.setTitle()` into one PR. 

For the rest please create one pull request per problem. Also include instructions on how to reproduce the issue (including the Android version you used for testing).

**Comment by plan3d** [comment]
I opened pull requests https://github.com/k9mail/k-9/pull/5318, https://github.com/k9mail/k-9/pull/5319, https://github.com/k9mail/k-9/pull/5320 and https://github.com/k9mail/k-9/pull/5321.

After executing gradle clean I could not reproduce my finding 3 (wrong title of unified inbox on startup) so please ignore it. All issues where tested with Android 10 (API version 29).

**Pull request closed without merging**
