### PR TITLE
in saslAuthPlain: if AUTHENTICATE PLAIN fails, try LOGIN

### LINKED ISSUE #899: backslash in username does not work for IMAP login
I need to access an exchange server via IMAP. My username has the form username@domain\special_mailbox .
Authentication with just username for the personal mailbox works fine but not for the special mailbox with the backslash syntax above.
I tried two backslashes since I suspected some java string escaping problem, but that did not work either.

### PR DESCRIPTION
**Pull request by mmehnert**
This fixes #899 .

### CODE REVIEW

**Comment by cketti** [comment]
Thanks for your contribution! However, I'm not quite happy with the approach.

The method `saslAuthPlain()` should only be doing one thing. If you want to add a fallback to the LOGIN command please add a new method `saslAuthPlainWithLoginFallback()` that implements that logic. Then call this method instead of `saslAuthPlain()` from `authenticate()`.

Also, there's nothing wrong with putting the `login()` call into the `catch` block. That way the code flow is more obvious and you don't have to use a `return` statement in the `try` block.

If you feel this change requires a comment please link to the GitHub issue. The existing comment doesn't help to understand why we're doing the fallback.

I'd be happy to review an updated pull request.

**Comment by mmehnert** [comment]
Thanks for the advice! Does the updated patch look better?

**Comment by cketti** [comment]
Almost. I wanted `saslAuthPlainWithLoginFallback()` to look like this:

```java
try {
    saslAuthPlain();
} catch (AuthenticationFailedException e) {
    login();
}
```

That way the individual login mechanisms are neatly separated and you have the aggregated behavior in the new method.

**Comment by mmehnert** [comment]
I see. :-) Pushed.

**Comment by cketti** [comment]
Thanks!

**Comment by bernhardschmidt** [comment]
Would it be possible to get this into 5.0? #899 is hitting us and an updated stable release fixing this would be great.

**Pull request merged**
