### PR TITLE
Clear cache to prevent images from previous emails from being shown

### PR DESCRIPTION
**Pull request by philipwhiuk**
See #2699

### CODE REVIEW

**Comment by philipwhiuk** [comment]
This will affect performance - by clearing the cache every time going back and forth between the same email and the inbox will re-download the image again. Not sure what's worse right now, cache-clash or this.

I'm loathe to make it a setting because you won't know to disable it.

**Comment by cketti** [comment]
I'm guessing only inline images (referenced using the `cid` scheme) are a problem. So maybe find a way to bypass the cache for those.

**Comment by Trogel** [comment]
If the cache is disabled this way, it might make sense to include #2716 here for its described side-effect: unblock network data in the web view on restore, if it was unblocked before the save/restore cycle.

Otherwise, after an orientation change the message view could end up with blocked network data and no cache. So, I'd expect that external images would be gone, even if "show pictures" was clicked before the orientation change,

**Comment by cketti** [comment]
Completely disabling the cache feels wrong. It will require downloading external content every time the message is displayed. I've created PR #2737 that fixes issue #2699 on newer Android devices.

**Pull request closed without merging**
