### PR TITLE
Don't duplicate link URL in angle brackets

### LINKED ISSUE #4872: URLs in reopened drafts are bracket expanded not delimited (recursively)
### Expected behavior
URLs in drafts are left as written or is delimited once according to common practice and recommendations ([RFC 3986, app. C](https://tools.ietf.org/html/rfc3986#appendix-C)).

The recommendation and long standing practice (tracing back to an [appendix of W3C's URL specification from 1994](https://www.w3.org/Addressing/URL/5.1_Wrappers.html) which the RFC builds upon) is to **delimit** URLs using angle brackets to allow a somewhat consistent interpretation (introduces some robustness to especially added line breaks).

### Actual behavior
Every URL present in a draft is expanded, not delimited, with a space and itself in angle brackets when it is reopened for editing. Such that fx. `http://example.com` becomes `http://example.com <http://example.com>`.

The expansion is even recursive, so when reopening a saved draft for the second time this occurs again for both the original URL and the URL in brackets such that fx. `http://example.com <http://example.com>` becomes `http://example.com <http://example.com> <http://example.com <http://example.com>>`, and this will continue.

This seems to me to be a misunderstanding trying to provide a rendered representative text for an URL, like the anchor text of a HTML anchor or a Markdown hyperlink. A bit like Markdown's ["autolink" which uses angle brackets](https://daringfireball.net/projects/markdown/syntax#autolink) as a shortcut to creating HTML hyperlinks with the URL as duplicate anchor text in the rendering. However, I think K9 is not intended to do any interpreting of the text here. And I'll be surprised if this has has anything to do with the IMAP store (gmail).

As a side note, it also looks like [Wordpress has been discussing the use of angle brackets in links being sent, and they lost](https://core.trac.wordpress.org/ticket/44589).

### Steps to reproduce
1. First edit; Write new mail containing an URL (body="Http://example.com"), see screenshot 1
2. Save as draft (back->Save as draft or menu->Save as draft), see screenshot 2
3. Second edit; Reopen draft message, observe the expanded URL yielding one duplicate, write some more text ("Test"), see screenshot 3
4. Save as draft (back->Save as draft or menu->Save as draft), see screenshot 4
5. Third edit; Reopen draft message, observe the two URLs each expanded yielding 3 duplicates, see screenshot 5
6. Continue editing, if this is your idea of fun ;)

### Environment
* **K-9 Mail version**: 5.717, see screenshot 6
* **Android version**: 7.0, see screenshot 7
* **Account type (IMAP, POP3, WebDAV/Exchange)**: IMAP (gmail)
* **Phone model**: Samsung Galaxy S8, SM-G950F

### Screenshots
Done using Danish (dansk) locale.
Quick parlour;
* skrive = write
* fra = from
* til = to
* kladder = drafts

#### 1 - first edit
Screenshot_20200708-184809

#### 2 - saved first edit
Screenshot_20200708-184821

#### 3 - second edit
Screenshot_20200708-184905

#### 4 - saved second edit
Screenshot_20200708-184920

#### 5 - third edit
Screenshot_20200708-184930

#### 6 - K9 version
Screenshot_20200708-184339

#### 7 - Android version
Screenshot_20200708-191629

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

Could do if it shows not to be easily reproducible.

### PR DESCRIPTION
**Pull request by GNUDimarik**
So the root cause is:
in NodeVisitor.head it pushes text reprecentaion of the link i.e. content of html tag 'a' and in head it added href element content in angle brackets second time.
I removed this for now and we use just text representation and in future I'd suggest to back to this and implement some reasonable logic for use links in angle brackets

Fixes #4872

### CODE REVIEW

**Comment by GNUDimarik** [comment]
For now removed attempt of getting URL to angle brackets since it produces duplicates but in future we need to back to this.

**Comment by cketti** [comment]
@GNUDimarik: You continue to leave the pull request template text in the description and don't add any useful information. Please replace it with a technical description of the bug, a description of what your change does exactly, and a reference to the issue.

The way it is now I'd have to reverse engineer your change to figure out what's the bug you were trying to fix. Then I'd have to figure out if this correctly fixes the actual problem. That's more work than just fixing the issue myself. Please document your findings so I don't have to do the work myself and can easily check your work.

**Comment by GNUDimarik** [comment]
@cketti thanks for your patience

**Comment by GNUDimarik** [comment]
@cketti please give me some recomendations what issues are most omportand.
Now i trying to fix issues with melestone and label bug.
Please let me know

**Comment by cketti** [comment]
Please read https://github.com/k9mail/k-9/issues/4872#issuecomment-697010974 on how I think the issue should be fixed. The comment also contains an example of the kind of analysis I was hoping for from you. You don't have to describe the change you made in code as text. I can see what you did. The question that the pull request description should answer is why you made that particular change.

**Comment by GNUDimarik** [comment]
I'll create another one with better fix

**Pull request closed without merging**
