### PR TITLE
Basic implementation of Exchange Active Sync

### LINKED ISSUE #606: Support newer Exchange servers
With WebDAV support gone in newer Exchange versions, EWS support should be added so newer Exchange servers can be used as well.

### PR DESCRIPTION
**Pull request by wiomoc**
Fixes #606 
Implemented support for EAS 12.0 (Exchange 2007)

## Some notes
* The EAS sync model / api fit's better directly to the `com.fsck.k9.backend.api.Backend` api then abstracting it over an `RemoteStore`, so I implemented no `RemoteStore` and not the full `Folder`
* EAS doesn't allow syncing by message count only by specific time periods. This means the whole folder is synced until a user selectable time.
* These Timeperiods doesn't match exactly to what is currently available at https://github.com/k9mail/k-9/blob/168e0908464f5fe8306d99119864438d66d1da8e/app/core/src/main/res/values/arrays_account_settings_values.xml#L30-L43 and to what is supported by EAS [MS-ASCMD FilterType](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ascmd/de626aea-ce53-40c2-abcf-19eb8213ea6c)
* Also the pusher timeperiods used by the `IMAPPusher` are not all usable by the `EASPusher` [MS-ASCMD Appendix A6](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ascmd/26b48eb3-6a22-4509-8cc8-f934305f369c#Appendix_A_6)
* Draft upload is only supported in version 16+ [MS-ASCMD Add](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ascmd/22628ffe-b14a-4300-aec7-187b0c37a1dc)
* Expunge is only supported in version 14+ ?
* The `Search` command uses different [Ids](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ascmd/a31a7c95-c15c-4680-8d43-c734a3284dc9) then the `Sync` and `MoveItem` command so it isn't usable for K9. The newer `Find` command supports proper [Ids](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ascmd/a875f1e4-37ae-4ec3-832f-2e1867c13c0a), but is only support at Version 16.1 
* Batch opperations e.g. `markAllAsRead` aren't supported
* Currently all sent messages will be saved in "sent messages"

Please ensure that your pull request meets the following requirements - thanks !

* Follows our existing [codestyle](https://github.com/k9mail/k-9/wiki/CodeStyle). ✅
* Does not break any unit tests. ✅  [Build Status](https://travis-ci.com/wiomoc/k-9)
* Contains a reference to the issue that it fixes. ✅ #606
* For cosmetic changes add one or multiple images, if possible. ✅

### CODE REVIEW

**Comment by cketti** [comment]
@wiomoc Sorry, I don't think now is a good time to include EAS support in K-9 Mail. See https://github.com/k9mail/k-9/issues/606#issuecomment-526831943 for a bit more details.

**Comment by yoshimo** [comment]
What exactly should be done first out of the ~600 open issues and ~40 pull requests?
#606 doesn't really give details, it just says "i won't do it for now"

**Comment by cketti** [comment]
I'm planning to write a roadmap for the near and medium-term future of K-9 Mail soon.

@yoshimo: Are you offering to help?

**Comment by yoshimo** [comment]
I would suggest to reduce the issue list first, and to get it to a manageable size maybe use something like https://github.com/apps/stale

**Pull request closed without merging**
