### PR TITLE
MessageReference class : method equals() unit tests

### PR DESCRIPTION
**Pull request by vcaulier**
Adding some unit tests for MessageReference object, and its equals() method.

I have begin with the possibility that the compared object is not a MessageReference subclass.
And continue next by asserting the two MessageReference compared objects are really equal.

### CODE REVIEW

**Comment by cketti** [comment]
Please create one test method per test. The method name should describe in more detail what you're testing.

Please don't combine two method calls in one assert statement. That makes it unnecessarily hard to find out which case failed.

**Comment by vcaulier** [comment]
Ok, I'll split this.
Updating right now.

**Comment by vcaulier** [comment]
Done, I've tried to split it by functionnality.
Should be better right now.

**Comment by cketti** [comment]
Thanks!

I made some more changes and ended up with this: https://github.com/k9mail/k-9/blob/4db7de4ed8efc08d7f019b32b9a781cef87ace29/k9mail/src/androidTest/java/com/fsck/k9/activity/MessageReferenceTest.java

**Pull request merged**
