### PR TITLE
Insert <hr> element when converting from text to HTML

### PR DESCRIPTION
**Pull request by Sayan98**
Implemented `HorizontalRuleHelper` which take a message body as string input and replaces all possible horizontal rule like ASCII sequences by `<hr />` and `HorizontalRuleHelperTest` which has various unit test showing wanted behaviour.

**What this does?**

`---------------------------` gets replaced to `<hr />`
`===========================` gets replaced to `<hr />`
`-=-=-=-=-=-=-=-=-=-=-=-=-=-` gets replaced to `<hr />`
`-- >8  --` gets replaced to `<hr />`
`- >8 -` gets replaced to `<hr />`
`- - - >8 - - -` gets replaced to `<hr />`
` >8 ` gets replaced to `<hr />` 
`-- 8< --` gets replaced to `<hr />`
`- 8< -` gets replaced to `<hr />`
`- - - 8< - - -` gets replaced to `<hr />`
` 8< ` gets replaced to `<hr />`
`___________________________` gets replaced to `<hr />`
`-=` remains unaffected
`==` remains unaffected
`-- ` remains unaffected
`=-` remains unaffected
`-` remains unaffected
`=` remains unaffected
`_` remains unaffected

### CODE REVIEW

**Comment by philipwhiuk** [comment]
It would be good to add some edge unconverted cases as tests. So for example, the fewest amount of `---` that don't get converted. This is is more important because the regex is pretty obtuse - so we'd want any future change to it to be obvious and the easiest way to enforce that is tests specifying exact behaviour.

**Comment by Sayan98** [comment]
@philipwhiuk On it.

**Comment by Sayan98** [comment]
@philipwhiuk I've added some unconverted test cases, will add more if needed.

**Comment by ployt0** [comment]
Forgive my interjection but I saw it was failing on Travis last night and got learning better regex, mine's three concise lines I'd never have known of yesterday.

**Comment by philipwhiuk** [comment]
Travis itself was broken last night because of the Amazon S3 instance. So the failures were possibly not actual test failures.

**Comment by Sayan98** [comment]
Just to clarify, commit #c30e4b4 was failing a single test case (which I thought of later) due to some changes I'd made. Build failures before this was caused due to Travis outage, more on it [here](https://www.traviscistatus.com).

**Comment by ployt0** [comment]
Sayan98 I'm sorry but this doesn't meet the specs of #2259. I've submitted a "better" patch already. I'd have been happy to just test yours but apparently the test driven development clawoflight advocated isn't possible here.

**Comment by cketti** [comment]
There are some code style violations. Check out the [code style](https://github.com/k9mail/k-9/wiki/CodeStyle) wiki page to learn how to import our code style settings into Android Studio. That'll allow the IDE to properly format the code.

I like the fact that you extracted the functionality to a separate class. Also the test names.

However, you implemented the functionality in isolation. But we want to change the existing behavior of `HtmlConverter`. This adds some additional constraints, e.g. the text has been converted to HTML before the replacement code runs.
Also, we only want to replace occurrences that contain no additional characters on the line. Your code will happily replace e.g. `Hi there >8-)` with `Hi there<hr />)`.

I'm closing this in favor of a revised version of the other pull request.

**Pull request closed without merging**
