### PR TITLE
Update displayed folder list when folders on server have changed

### LINKED ISSUE #5661: some folders are not removed from K9 after a refresh folder list action
hi all

firstly, i have searched for "folders not removed". I've looked at both open and closed issues and can't seem to find anything that matches my problem. This of course makes me wonder if it's something specific to me.

### **Describe the bug**
when i've renamed a folder in gmail, i would expect the k9 refresh folder list action to:

a) produce the newly named folder

b) remove the old / missing folder

As per your FAQ here https://k9mail.app/documentation/faq.html#anchor16

However, I've got K9 folders that no longer exist in the browser gmail experience (because i've renamed them), yet they are still visible in K9.

Refresh Folder List does not remove them.

### **To Reproduce**
i can only partially reproduce it now :(

I've literally just tested with a new folder in browser gmail (no emails in test folder), just so as to not waste your time.

- I refreshed the k9 folder list. New folder appeared.
- i then renamed in gmail (browser) and k9 folder refreshing changed the folder name. The previous folder name no longer exists in K9.
- As a final test, i deleted the gmail folder ("remove label" command) and K9 folder refreshed. Folder disappears.

I retested the above with an email in it (admittedly a draft email).

- Test folder with emails in it appears in K9.
- Renamed test folder with email in it appears in K9.
- Old test folder with email disappears from K9.
- Removing test folder from gmail removes from K9 after folder refresh.

**However**, i DO have existing K9 folders which don't exist on gmail any more, yet i can't delete them from K9 because there's no delete function and refresh folder list doesn't remove them. 

- Although there were no emails showing the redundant K9 folders, i tried "clear local messages", in case there was some data marked against them. This didn't help.
- I've got 8 folders in K9 like this, which don't exist on gmail.
- I did think about the possibility of compacting the account but i think that functionality has been removed.

### **Expected behaviour**
all folders that no longer exist in gmail should get removed by K9's refresh folder list action.

### **Additional context**
using K9 v5.806 on Samsung S8 with official OTA android release 9 i.e. pie

Am using IMAP for gmail to K9 operations.

### **Logs**
~~didn't attach any as i get no errors~~

debug log attached for "Refresh Folder List" action on my the account in question.
[k9-log.txt](https://github.com/k9mail/k-9/files/7155866/k9-log.txt)

regards,

Gary

### PR DESCRIPTION
**Pull request by cketti**
Fixes #5661

### CODE REVIEW

**Comment by gazzawazza** [comment]
@cketti hi

I see you merged my old ticket https://github.com/k9mail/k-9/issues/5661 into this one.

I'm sorry i didn't reply to your last comment under 5661 (https://github.com/k9mail/k-9/issues/5661#issuecomment-919102464)

What i would say is i basically had already done the test that you proposed and had, i thought, declared that in my thread opener.

How should i proceed now anyway?

Or is my folder refresh issue now a recognised bug?

I'm just a bit confused and not that familiar with github procedures.


regards,

Gary

**Comment by cketti** [comment]
The bug was fixed. The next beta version will include the fix.

**Comment by gazzawazza** [comment]
> 
> 
> The bug was fixed. The next beta version will include the fix.

ah ok - excellent. Ty.

Do betas get regularly rolled out as public releases or might i need to wait (if i don't go down the beta path)? It's more really to confirm that the fix resolves my experiences.

**Comment by gazzawazza** [comment]
hi

This bug has not been resolved.

I have literally just moved to a new handset (s22) and done a fresh install of K9.

v6.202

on One UI 5.0 (android 13)

Gmail folders that do NOT exist when viewed in gmail (in a browser) have appeared in K9, when i synced for the first time.

I have also checked in gmail settings and these phantom K9 folders do not exist in any form i.e. it's not as if they exist but were set to hidden.

NOTE: I did import settings from from my old handset (running 6.202 too).

**testing**
I've tried refreshing folder list in K9 - no change (phantom folders still appear)
I removed the account in question and reinstalled - no change (phantom folders still appear)

Any suggestions?


thanks,

Gary

**Comment by cketti** [comment]
@gazzawazza: This is most likely not a bug. Please use the [forum](https://forum.k9mail.app/) to discuss the behavior you're seeing. Describe what you're seeing (not just "phantom folders", be specific) and what conclusions you draw from that. Please be aware that your conclusions might be sensible given your observations, but could be wrong nonetheless.

**Comment by gazzawazza** [comment]
> @gazzawazza: This is most likely not a bug. Please use the [forum](https://forum.k9mail.app/) to discuss the behavior you're seeing. Describe what you're seeing (not just "phantom folders", be specific) and what conclusions you draw from that. Please be aware that your conclusions might be sensible given your observations, but could be wrong nonetheless.

Thanks but i'm confused.

I posted this behaviour as a bug under this ticket: https://github.com/thundernest/k-9/issues/5661.

i was clear and specific about expected and actual behaviour. I've only abbreviated the problem to "phantom" folders because I've already explained problem previously.

You stated this was a bug and had been fixed in a beta release. You merged 5661 ticket into this one.

I have done as you requested under the old ticket but you wish this to be posted again in the forum?


thanks,

Gary

**Comment by cketti** [comment]
This pull request fixed a bug where K-9 Mail was correctly fetching the new folder list and making the necessary changes to the local database. However, the folder list displayed in the user interface wasn't updated. You could work around this bug by killing the app, then restarting it. Since your issue seems to persist after re-installing the app, it clearly is not the caching issue that was fixed here.

I have no reason to believe that there's a bug in K-9 Mail when fetching the folder list. K-9 Mail doesn't make up folder names. After a fresh installation there can't be any cached data that could accidentally be used. So the most likely explanation is that your expectations clash with reality. In the forum much more people will see your message and might be able to help you figure out what the problem is.

**Comment by gazzawazza** [comment]
> This pull request fixed a bug where K-9 Mail was correctly fetching the new folder list and making the necessary changes to the local database. However, the folder list displayed in the user interface wasn't updated. You could work around this bug by killing the app, then restarting it. Since your issue seems to persist after re-installing the app, it clearly is not the caching issue that was fixed here.
> 
> I have no reason to believe that there's a bug in K-9 Mail when fetching the folder list. K-9 Mail doesn't make up folder names. After a fresh installation there can't be any cached data that could accidentally be used. So the most likely explanation is that your expectations clash with reality. In the forum much more people will see your message and might be able to help you figure out what the problem is.

thanks

firstly, have posted as requested in the forum:

https://forum.k9mail.app/t/some-folders-are-not-removed-from-k9-after-a-refresh-folder-list-action/5691

Secondly, i've cracked what the the problem is:

K9 has issues with gmail folders with "/" in them and can't seem to remove the old folder name, if the new one contains "/"

My testing seemingly confirms this.

Could you comment?




many thanks,

Gary

PS i'm really pleased i seem to have discovered the behaviour that causes what i was experiencing, because it was puzzling me.

**Pull request merged**
