### PR TITLE
TextToHtml: Rewrite text to HTML conversion

### PR DESCRIPTION
**Pull request by cketti**
This replaces the text to HTML conversion code in `HtmlConverter` with a slightly different approach. 

Things like URI detection and ASCII divider detection now operate on the plain text and create `HtmlModification` objects that describe how to transform the matches to HTML. The currently supported methods are:
* `WRAP`: to wrap URIs in `<a>` tags
* `REPLACE`: to replace ASCII dividers with `<hr>` tags

In the future I hope to add more modifications, e.g. one to de-emphasize signatures (see #3168).

### CODE REVIEW

**Comment by Djfe** [comment]
pls take links like
<test@test.com>
into consideration :)

example (quoted replies):
Am 08.02.18, 11:25 schrieb "someone" <abc@xyz.de>:

**Comment by Djfe** [comment]
screenshot_20180208-125050
about dividers:
xda's Mails use * and ~ for different kinds of dividers

**this could be bold text**

**Comment by Djfe** [comment]
==============
should be double lines though

not simple lines like:
-------------

atm. they both look the same (hr tag)

**Comment by Djfe** [comment]
``` -- Deutsch ```
the dashes could mean: the following text is a heading
(if they aren't alone in one line without any following text)

**Comment by cketti** [comment]
@Djfe: Those are feature requests and/or bug reports. Please use issues for that.

**Comment by Djfe** [comment]
Just took care of them :)
#3171

**Pull request merged**
