### PR TITLE
Throw instead of returning null when Body.getInputStream() is not supported

### PR DESCRIPTION
**Pull request by cketti**
Inspired by trying to find out what happened in issue #1794

### CODE REVIEW

**Comment by philipwhiuk** [comment]
LGTM.

Not sure it's worth making `closeInputStreamWithoutDeletingTemporaryFiles` return cleanly if null? Or marking the method `@NotNull`?

**Comment by Valodim** [comment]
This escalates the problem from a missing body in some emails to a persistent crash on retrieve, right? Since this doesn't appear to happen too often (beta's been out for many months, problem only came up now), I suggest postponing this into a post-stable beta.

**Comment by philipwhiuk** [comment]
No, it just throws the exception earlier. It's already throwing an NPE, but later so we don't see why we were using the wrong Body type.

**Comment by cketti** [comment]
Right, this shouldn't change the overall outcome.

On the topic of null-ability: I'd like this to be the exception, rather than the norm. Ideally I want a missing `@Nullable`/`@NotNull` annotation to imply `@NotNull`. But since we have to deal with a large body of legacy code we'll have to start with both annotations, preferring `@NotNull` wherever possible.

**Pull request merged**
