### PR TITLE
List view to recycler view

### PR DESCRIPTION
**Pull request by kamil0074**
According to remarks on PR #2916. I created a transition from List View to Recycler View changing existing code as little as possible maintaining code functionality and readability. It required moving swipe handling system to MessageListFragment but it also opens the way to implement in relatively costless way delete by swipe feature in future if needed.

### CODE REVIEW

**Comment by philipwhiuk** [comment]
I will try and find time to test this at the weekend.

**Comment by Valodim** [comment]
Just at first glance it looks like there are several whitespace and other code-style changes in this PR, and not even isolated in a single commit :\

**Comment by philipwhiuk** [comment]
Crash on my rebase of this (a TODO for me)

```
01-31 12:22:19.399 581-970/? E/QC-QMI: linux_qmi_qmux_io_wake_unlock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
01-31 12:22:20.708 31490-31490/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.fsck.k9.debug, PID: 31490
                                                                   java.lang.NullPointerException: Attempt to write to field 'int android.support.v7.widget.RecyclerView$ViewHolder.mItemViewType' on a null object reference
                                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6322)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5509)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3266)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                       at android.os.Handler.handleCallback(Handler.java:790)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                       at android.os.Looper.loop(Looper.java:164)
01-31 12:22:20.709 31490-31490/com.fsck.k9.debug E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by cketti** [comment]
Continued with PR #3164.

**Pull request closed without merging**
