### PR TITLE
Spam Assassin support

### PR DESCRIPTION
**Pull request by rsavoye**
This branch adds support for the header fields Spam Assassin sets. If X-Spam-Flag is set to YES, then the message is moved to the user specified spam folder. If the message doesn't have these headers, the default is to assume it's not spam, and continue with normal processing. This has been a requested feature from what I can tell, but of course I implemented this cause I run Spam Assassin on my own email server, and also use K9 for reading email when mobile. I'm open to making any suggested changes to this branch.

### CODE REVIEW

**Comment by hobarrera** [comment]
Shouldn't this be done server side (eg: by sieve) rather than by a client?
What happens when a message that was already moved out of the spam folder on another device (eg: a desktop, or another mobile device) is downloaded into K-9?

**Comment by cketti** [comment]
Of course filtering on the server is the better alternative. But reality is that many people don't do that. Either because they don't know how or because their mail provider doesn't support it. 

> What happens when a message that was already moved out of the spam folder on another device (eg: a desktop, or another mobile device) is downloaded into K-9?

My first idea is to only consider newly downloaded, unread messages in the Inbox as candidates for being filtered.

**Comment by hobarrera** [comment]
> Of course filtering on the server is the better alternative. But reality is that many people don't do that. Either because they don't know how or because their mail provider doesn't support it. 

Or more importantly, because their client does not support it: see ([issue 451](https://code.google.com/p/k9mail/issues/detail?id=451)). K-9 users can't actually do server-side filtering without the help of a second email client, since K-9 does not support configuring them.

I think it would be much smarter to add managesieve support to K-9, and have the ability to create these spam-related rules there, rather than run them locally on every client.

> My first idea is to only consider newly downloaded, unread messages in the Inbox as candidates for being filtered.

This does not cover emails that have been un-marked as spam on other devices, but remain unread.

**Comment by cketti** [comment]
I don't know of any large email provider that supports sieve. But please go ahead and submit a pull request.

**Comment by hobarrera** [comment]
> I don't know of any large email provider that supports sieve.

Fastmail seems to support sieve. I'm not familiar with any other large-scale email provider that support IMAP.

> But please go ahead and submit a pull request.

I'm just suggesting that this be actually implemented via sieve *instead* of client side, rather than as *on top of* it.

**Comment by PanderMusubi** [comment]
Sieve is indeed not offered by large-scale providers but large organizations can have it configured in general of by users for example for handling junk mail as is described in https://code.google.com/p/k9mail/issues/detail?id=301

**Comment by PanderMusubi** [comment]
Still looking forward too seeing this land in the next version.

**Comment by cketti** [comment]
I want a more generic solution for local mail filtering. See #908 

Local spam filtering might also be an option some day. Although I think I prefer to add an interface for third-party applications to do spam filtering.

**Pull request closed without merging**
