### PR TITLE
"Delete", "archive" and "spam"

### PR DESCRIPTION
**Pull request by adamsmd**
This code regularizes the handling of "delete", "archive" and "spam" actions.  Specifically it adds "archive" and "spam" buttons to notifications.  This is optional and configurable by the user in the same way it is for "delete"

In the long run, it would be nice of K-9 did the same for "reply" and "mark read", but I am about to get busy with other projects and won't have the time myself.

I have not done extensive testing on this code.  (Also due to my getting busy.)  But I figure it is better to share the code incomplete than let it die.

One part of the code that I was unsure about was the version numbers in GlobalSettings.java.  Also, I did not find a vector version of the "archive" and "spam" icons so I made due with non-vector ones.   Both of these places are marked with TODO comments.

Finally, by default, notifications in Android ignore any actions after the first three.  To get around this I created ExtendedNotificationBuilder.java.  Note that build() and generateActionButton() are almost exact copies of similar code in AOSP Notification.java.  Since both K-9 and AOSP are licensed as Apache, I believe copying the code like that is okay.  My apologies if not.

### CODE REVIEW

**Comment by cketti** [comment]
Thanks for taking the time to implement a new feature and creating a pull request.

However, I don't want to add support for more than three notification actions because I believe it will lead to a bad user experience. 
The option to specify which actions are displayed will only be added once there's a decent UI that allows easy configuration. That feature is tracked in #943.

**Comment by adamsmd** [comment]
What if I take out commit 5e1ce4c (which added support for more than three actions).  This would allow users to have "archive" or "spam" in their notifications instead of "delete".

**Comment by cketti** [comment]
Then the "decent UI" to configure what actions to show is still missing.

Issue #943 links to this pull request. So your code won't be forgotten when we finally get to this.

**Comment by adamsmd** [comment]
@nomeata Hi, Joachim.  Unfortunately, I have not done anything to keep this up-to-date.  Sorry.

**Pull request closed without merging**
