### PR TITLE
Add autoconfig settings for some Greek providers

### PR DESCRIPTION
**Pull request by dalevizo**

### CODE REVIEW

**Comment by cketti** [comment]
Thanks!

I wasn't able to connect to any of the mycosmos.gr servers. Did the provider stop operations?

**Comment by dalevizo** [comment]
I'll check it out and I'll let you know.
If they changed anything I'll submit a new pull request.

Thanx!

**Comment by dalevizo** [comment]
There was a mistake in the server names for mycosmos.gr, they use mail.mycosmos.gr for both imap and smtp.
I've updated the file, everything should be ok now.

Again, thank you

**Comment by cketti** [comment]
Thanks!

**Pull request merged**
