### PR TITLE
Change appearance of attachment boxes in message view screen 

### LINKED ISSUE #2009: Display larger preview of image attachments
I review a ton of security camera footage. The pics come to me by email. This is what attached images are currently displayed like in K9:
screenshot_20170107-125805

It would be monumentally awesome if you guys simply changed the proportions of the same data, to behave a little more like gmails does, for the sake of being able to see more of the image. This would save folks in my boat a ton of time/clicks/taps :D

screenshot_20170107-125756

Hopefully this isn't a huge, massive change. And hopefully other users will agree with it! Otherwise, perhaps an option in the settings to change how inline images are displayed?

Thanks in advance!

### PR DESCRIPTION
**Pull request by cketti**
k9mail__message_view__attachments

Closes #2009

### CODE REVIEW

**Comment by cketti** [comment]
I created issue #4646 for improving the way we display attachments.

**Comment by Viss** [comment]
Is this default functionality now, or is there a way to turn this on or enable it? because I just pulled version 5.714 and the images in the emails I'm seeing are just little icons, not even thumbnails, and i have to manually tap each one to view the image.

**Comment by cketti** [comment]
It only works for supported image types (jpeg, png and gif) and only for attachments already downloaded (tap the "download complete message" button).

**Comment by Viss** [comment]
The images are jpegs, and the message has been fully downloaded already.

Screenshot_20200516-160739

**Comment by cketti** [comment]
I'm guessing the email doesn't contain the proper MIME type for the images.

**Comment by Viss** [comment]
it's plausible that's the case - the emails are coming from an axis security camera.
Before upgrading to this version, the images were being displayed properly and would render, but theyd show up as teeeny tiny thumbnails, so it was working in previous versions of k9.

**Pull request merged**
