### PR TITLE
Special folder icon

### PR DESCRIPTION
**Pull request by jca02266**
I think the special folder name in folder list is verbosely.

```
  Drafts (Drafts)
  Trash (Trash)
  ..
```

This patch adds icon in folder list.

### CODE REVIEW

**Comment by cketti** [comment]
I'd like us to have icons specific to the special folders.

If someone wants to gather Holo-style icons for the special folders we support, I'd be happy to merge a pull request. Otherwise I'd defer this until the UI overhaul. We'll need different icons then anyway.

**Comment by jca02266** [comment]
Sorry, I can't understand English very well.

You means that you don't just like the design of the special_folder_{dark,light}.png ?
Otherwise, You want to have each forlder icon for the Drafts folder, Trash folder, etc.?

**Comment by cketti** [comment]
Sorry, what I meant was that I want different icons for the different special folders.
E.g. one that looks like a trash can for the Trash folder. Similar to what the Gmail app does.

After the work on PGP/MIME is done we want to change the UI to material design. So all icons for special folders you create now will have the wrong style and be thrown out then. So my advice is to wait until we change the UI anyway.

**Comment by jca02266** [comment]
I understand. Thanks for your detailed explanations. You can close this request.

**Pull request closed without merging**
