### PR TITLE
PR: Don't limit subject in message view to 3 lines

### PR DESCRIPTION
**Pull request by GoneUp**
Fix for #1861 
Question: 
In this xml file several deprecated functions are used (like android:singleLine or android:toLeftOf).
Can I just change them in this PR or should such things happen in a different PR?

### CODE REVIEW

**Comment by ArchangeGabriel** [comment]
Question regarding this: what will that do if the title is very long? Does the header scroll work independently of message scroll or not? Not very common and probably not a to be supported use case, but I have at least one threads of emails where someone put a whole book in the title (which turned to be a good crash test case for email clients).

**Comment by GoneUp** [comment]
The header is included in the message scrolling, so that shouldn't be a problem.

**Comment by ArchangeGabriel** [comment]
OK, so just long scrolling. Seems fine given the limited use case, but still I’m a bit concerned that this could mean less space for message body in some emails. Could we have a better UI here ? Like reducing the title to one line or two (minimum size in height), but being able to tap it to open a pop-up window (like the “About” one) with the full title? Or maybe make it a foldable field, I think that’s part of the Material Redesign or should be. ;)

**Comment by cketti** [comment]
Why would you not want to be able to see the full subject without expanding it? Even if people put lots of text there, presumably it's important text you want to read.

**Comment by cketti** [comment]
@GoneUp: Thanks for the fix!

**Comment by ArchangeGabriel** [comment]
Well a whole book in the title is a troll, nothing important to read. But I agree that’s not common.

However, even if the title is important, maybe I don’t need to read it each time I go to such an email if what I’m interested in is something in the body. So having the title folded as the default looks like a more sensible default to me, but maybe that’s only my opinion. Anyway, if that ever become an issue, I’ll feel free to open a ticket for that. ;)

**Pull request merged**
