### PR TITLE
List view converted to RecyclerView using wrapper on existing adapter

### PR DESCRIPTION
**Pull request by philipwhiuk**
A rebased version of #2916 on-top of my minimal Material changes. Still in a TODO state. Pushed it to the main K-9 repo to make future work by others easier.

### CODE REVIEW

**Comment by cketti** [comment]
@philipwhiuk: Does this supersede PR #3066?

**Comment by philipwhiuk** [comment]
Yes.

**Comment by Valodim** [comment]
This would have been a lot easier to rebase if it didn't contain unrelated whitespace reformatting :P

**Comment by cketti** [comment]
There's currently work in progress to simplify `MessageListAdapter`. After that is done it should be relatively easy to switch to `RecyclerView`.

**Pull request closed without merging**
