### PR TITLE
Account Setup Rework

### PR DESCRIPTION
**Pull request by philipwhiuk**
This is a rebase of @daquexian 's GSoC Account Setup work. See #2530

* Mozilla ISPDB autoconfigure
* SRV based autoconfigure
* Microsoft Autodiscover
* Google OAuth 2.0
* Outlook OAuth 2.0
* Material design for Account Setup activities

While manually testing I've noticed that the manual setup has lost some IMAP settings so I probably need to look at that.

It would be good to get this into an beta sooner rather than later though.

### CODE REVIEW

**Comment by philipwhiuk** [comment]
It looks like the Gmail OAuth integration requests re-registration when it loses network. I still need to reproduce this when I have ADB handy though to diagnose why. Possibly an IOException we are treating incorrectly.

**Comment by philipwhiuk** [comment]
Hmm, it looks like the refresh token hasn't been saved. We're throwing an NPE because we don't have a promptRequestHandler.

@daquexian do you know how this is supposed to be handled?

```
01-18 22:01:42.794 14875-14942/com.fsck.k9.debug E/ImapSync: synchronizeMailbox
java.lang.NullPointerException: Attempt to invoke interface method 'void com.fsck.k9.account.Oauth2PromptRequestHandler.handleGmailRedirectUrl(java.lang.String)' on a null object reference
    at com.fsck.k9.account.GmailOAuth2TokenStore.showAuthDialog(GmailOAuth2TokenStore.java:34)
    at com.fsck.k9.account.K9OAuth2AuthorizationCodeFlowTokenProvider.showAuthDialog(K9OAuth2AuthorizationCodeFlowTokenProvider.java:41)
    at com.fsck.k9.mail.oauth.OAuth2AuthorizationCodeFlowTokenProvider.getToken(OAuth2AuthorizationCodeFlowTokenProvider.java:47)
    at com.fsck.k9.account.K9OAuth2TokenProvider.getToken(K9OAuth2TokenProvider.java:56)
    at com.fsck.k9.mail.store.imap.ImapConnection.attemptXOAuth2(ImapConnection.java:434)
    at com.fsck.k9.mail.store.imap.ImapConnection.authXoauth2withSASLIR(ImapConnection.java:396)
    at com.fsck.k9.mail.store.imap.ImapConnection.authenticate(ImapConnection.java:358)
    at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:143)
    at com.fsck.k9.mail.store.imap.ImapFolder.getPrefixedName(ImapFolder.java:92)
    at com.fsck.k9.mail.store.imap.ImapFolder.exists(ImapFolder.java:265)
    at com.fsck.k9.controller.imap.ImapSync.verifyOrCreateRemoteSpecialFolder(ImapSync.java:341)
    at com.fsck.k9.controller.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.java:120)
    at com.fsck.k9.controller.imap.ImapSync.sync(ImapSync.java:63)
    at com.fsck.k9.controller.imap.ImapMessageStore.sync(ImapMessageStore.java:25)
    at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:743)
    at com.fsck.k9.controller.MessagingController$37.run(MessagingController.java:3595)
    at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:207)
    at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:123)
    at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:176)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by cketti** [comment]
We want to split this up into smaller chunks to make reviews easier.

**Comment by BrainBlasted** [comment]
@philipwhiuk, has there been any progress on getting this split up and integrated?

**Comment by Krammig** [comment]
Could I perhaps take a look at this ?

**Comment by philipwhiuk** [comment]
I'm happy for anyone to take over this.

**Comment by cketti** [comment]
We'll probably end up rewriting all of the account setup code.

**Pull request closed without merging**
