### PR TITLE
move sign-only into a mode of its own

### PR DESCRIPTION
**Pull request by Valodim**
Picture's worth a thousand words:

sign only mode screenshot sign only menu screenshot

I don't believe signing mails by default is useful at all (see #1766), and compared to encryption it's sort of lateral - it just didn't fit anywhere in the slider. Extracting this into a mode of its own, the slider menu is now consistent, regardless of whether "Support signed only mails" is enabled. In particular, "Encrypt if possible" no longer signs if encryption isn't enabled. It also allows showing a dialog with explanations of what is going on, similar to pgp/inline.

(would be interested in comments & critique, ping @dschuermann @dkg @hpk42)

### CODE REVIEW

**Comment by hpk42** [comment]
I like this, thanks!

related: Is it possible to encrypt without signing?  That's what i'd currently like to do since i don't have my secret key on my mobile but i'd still like to encrypt to people when i sent from the phone.  I am fine with receiving an encrypted reply that i can't read on my phone.  In general we will need to teach people about this situation anyway -- note that it's not the same as teaching them the difficulties of handling/importing/exporting/uploading etc. keys.  It really just means we introduce the concept "this app supports encryption, the other doesn't".

**Comment by Valodim** [comment]
@hpk42 no. That is a misfeature and it's not going to be supported. See #1768 for a recent discussion on this.

**Comment by Valodim** [comment]
@cketti ping, merge and beta please

**Comment by dkg** [comment]
You say a picture's worth a thousand words, but then you show two pictures and don't explain how they relate to each other.  can you use some words to unlock the meaning of those pictures?

Is one of them before some change, and the other one after?

is the one on the right the menu that a user chooses "Attach PGP Signature" and the one on the left the dialog box that shows up?

Why "Attach PGP Signature" and not "Sign message with PGP" ?

If a PGP signature is something i just "attach", then maybe i could just take one off one message and attach it to another?  (that's how paper signatures work) -- this wording seems likely to confuse users.

that said, i agree that signing a message isn't "on a slider" -- there are orthogonal options here.

**Comment by cketti** [comment]
One scenario with a somewhat unsatisfying UX:
- User moves slider to "Always Encrypt"
- User enters recipient we can encrypt to (icon changes to non-grey lock)
- User selects "Attach PGP Signature"

The message will be sent unencrypted and signed. I don't believe this will be obvious to users.
I'm not sure how to best address this. Maybe animate the icon to the crossed-out lock (unencrypted) before animating to the blue checkmark.

Another option would be to hide the "Attach PGP Signature" menu item once the user selected "Always Encrypt". However, that still leaves the '"Encrypt if possible" + recipient we can encrypt to' case that will switch from 'message will be encrypted' to 'message will be signed only'.

**Comment by cketti** [comment]
Enabling, then disabling sign-only mode doesn't restore the previous slider state.

**Comment by Valodim** [comment]
@dkg Sorry, I didn't think this one through and forgot you didn't have the context. Nvm for now, we can discuss this maybe in a high-bandwidth scenario in December :)

@cketti Regarding your last comment, that sort of follows from the way state is kept in the code. Since this is only a minor problem, I'd like to keep it that way for now, in order to avoid touching more of that code than necessary.

**Comment by Valodim** [comment]
re wording: Agreed. My thought was that "those show up as attachments for most people", but I found that that is no longer true (e.g. ios mail, thunderbird), and also the aspect of being otherwise confusing is more important. I changed it to "Enable PGP Sign-Only".

Also moved the indicator in the place of pgp/inline, so now the struck-through lock is still there in sign-only mode, to avoid the scenario of confusion cketti outlined.

**Comment by cketti** [comment]
I'd like us to hide the "Enable PGP/INLINE" menu item when sign-only mode is enabled. It's frustrating to select an option only to be told you can't use it.

Similarly, tapping the lock icon when sign-only mode is enabled currently displays "Encryption unavailable in sign-only mode". Showing a dialog asking users whether they'd like to disable sign-only mode in order to change the encryption settings might be a less frustrating option.

Otherwise this feels nice.

**Comment by Valodim** [comment]
I thought about that, and it's a matter of vanishing options vs consistent options with possible errors. I think there is merit to being explicit and clear about these things, not finding options because some other options is connected in a non obvious way can be even more confusing. Also keep in mind, the signing option only shows up when sign-only is enabled in general, so this is not all that common in the first place.

**Comment by cketti** [comment]
@Valodim You're probably right about hiding the PGP/INLINE menu item. There's no obvious connection between signing and inline PGP that would explain the missing menu item.

I still think that clicking the lock icon should offer to disable sign-only mode instead of just displaying an error message. If users reconsidered, they'd have to click the sign-only icon, select "Disable" in the dialog, press the lock icon, then select the encryption mode.
However, this is something we can fix in another PR.

**Comment by kolAflash** [comment]
Hi!
I understand, that in a group of scenarios the sign-only option might be confusing.

_
But on the other hand please consider this:
- mail forgery is pretty easy and sending wrong emails or manipulating emails can be a pretty effective way for a targeted attack to disturb a groups communication
- a signed mail can still be read by a receiver without a PGP mailclient
- on mailinglists you usually can't encrypt but still sign your mails

_
So I can see only two arguments against signing every email you write:
- you may have to enter your password very often
- on rare occasions you might write something touchy into an email and you don't want to other to be able to cryptographically proof, that you wrote that

_
So I propose to rename the new option "Support signing of unencrypted messages" to something like "activate PGP expert mode".
And if the expert mode is active:
- provide per-account-setting to automatically sign every email
- provide option in mail editor, to not sign the current email (also if it's encrypted)
  - so you can disable signing when writing touchy stuff (e.g. you like in North Korea or some other dangerous state and you want to say write some thing the government may not want you to write)
  - and you might also want to have this option if you're in a hurry and you know that the receiver doesn't has a email client which can verify the signature and so you want to save the time for entering the password

**Comment by philipwhiuk** [comment]
I'd rather we just added a default mode. If you enable signing only and you set default to 'sign only' then you get what you want without some cryptic 'expert mode'

**Pull request merged**
