### PR TITLE
SMTP: Testing SmtpTransport using new MockSmtpServer

### PR DESCRIPTION
**Pull request by philipwhiuk**
I've written a new MockSmtpServer which works very similarly to the MockImapServer. I've used this to write conformance tests for the existing methods of authentication.

This should help to test any new SMTP functionality (such as the new authentication methods like XOAUTH2) as well as providing a platform to write regression tests for any issues we find.

I pulled the existing helpers from the ImapConnectIonTest to new classes to enable me to re-use them. I also moved the URI decoding stuff to a new class to better reflecting the testing it does (again, parity with IMAP).

### CODE REVIEW

**Comment by philipwhiuk** [comment]
The extra work covers off: actually sending messages, 8BITMIME extension, HELO/EHLO fallback and message sizing.

**Comment by philipwhiuk** [comment]
I'd really like to see this merged - it's a useful way of validating SMTP authentication methods in particular and I definitely want it in before my XOAUTH stuff (because then the XOAUTH method can be tested for SMTP rather than just IMAP).

**Comment by cketti** [comment]
I cleaned this up a bit. Let me know what you think.

**Comment by philipwhiuk** [comment]
LGTM.

I see you found a bug in sendMessage_withMessageTooLarge() :)

**Comment by jberkel** [comment]
looks good, needs to be rebased

**Pull request merged**
