### PR TITLE
replace AsyncTask with AsyncTaskLoader

### PR DESCRIPTION
**Pull request by yulin2**
Hello, I'm doing research on Android async programming. Some articles (for example [this article](http://bon-app-etit.blogspot.com/2013/04/the-dark-side-of-asynctask.html)) mention that AsyncTask leads to memory leak and losing task result when there's a configuration change (such as orientation change). Android docs recommend [AsyncTaskLoader](http://developer.android.com/reference/android/content/AsyncTaskLoader.html), which avoid the problems in AsyncTask.

I try to replace one AsyncTask with AsyncTaskLoader in k-9 in this pr (you don't have to merge). Do you think AsyncTaskLoader will work better for k-9? Do you want to replace all AsyncTask to AsyncTaskLoader?

### CODE REVIEW

**Comment by cketti** [comment]
Not all `AsyncTask`s should be replaced by an `AsyncTaskLoader`. In this case I think a loader is a good fit.

Unfortunately, your code doesn't work. `LoadAccounts` needs to be a static inner class.
After you fix that, you'll run into this issue: https://code.google.com/p/android/issues/detail?id=154696

My suggestion is call `initLoader()` from `onCreate()`.
I would also rename `LoadAccounts` to `AccountsLoader`.

**Comment by yulin2** [comment]
Thanks for your suggestion. I also notice the bug when calling `LoaderManager.initLoader` in `onStart`.

 But you said not all `AsyncTasks` should be replaced by `AsyncTaskLoader`. Could you let me know your reasons of not using `AsyncTaskLoader`? Based on my knowledge, `AsyncTaskLoader` avoids memory leak and prevent losing task result automatically, which is better than `AsyncTasks`. The only reason I know  is `AsyncTaskLoader` doesn't support reporting progress and requires API level 11.

**Comment by cketti** [comment]
Loaders are perfect when you want to load data that needs to be retained across configuration changes.

But sometimes you have to perform one-time actions you want to do in the background (see e.g. Accounts.MoveAccountAsyncTask). By using AsyncTasks you don't permanently leak memory. It's just that a finished activity can't be garbage collected until the last AsyncTask contained in it has completed. That is usually not an issue with short-running tasks.

**Comment by cketti** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
