### PR TITLE
Optionally enable web cache

### PR DESCRIPTION
**Pull request by sgomin**
Hi,

Thank you for the great open-source email client.

Please consider embedding a small amendment from me.
I have added an option to enable cache in WebView. Was there any reason for disabling it?
It really hurts to see images re-loaded every time I open a message.

Regards,
Stan

### CODE REVIEW

**Comment by cketti** [comment]
Making this a user-configurable setting seems unnecessary. Simply removing the line to explicitly configure the cache behavior should be fine.

Please make sure the bug fixed with #2737 is not an issue afterwards. For testing create two emails containing different inline images, but both using the same Content-ID value. Then make sure both messages show the correct image when viewed in K-9 Mail.

**Comment by sgomin** [comment]
What is the easiest way to open an email file in K-9 without actually sending it to myself? If I send an manually crafted email, the contentID of inline images are re-generated.

**Comment by wiktor-k** [comment]
@sgomin wouldn't it be better to just cherry-pick the last commit? The two first negate themselves out... (you can do that with `git rebase -i HEAD~3`, removing unneeded commits and then force-pushing here again).

**Comment by wiktor-k** [comment]
> What is the easiest way to open an email file in K-9 without actually sending it to myself? If I send an manually crafted email, the contentID of inline images are re-generated.

This is something cketti recommended and it works quite nice: https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools/?src=ss

**Comment by wiktor-k** [comment]
Thank you! :) Looks a lot cleaner.

**Comment by sgomin** [comment]
I've checked that [#2737](https://github.com/k9mail/k-9/pull/2737) is not reproduced with web cache enabled using the attached emails with inline images on Android 7.1.2 

[inline_images.zip](https://github.com/k9mail/k-9/files/2631066/inline_images.zip)

**Comment by cketti** [comment]
Thanks!

**Pull request merged**
