### PR TITLE
New icon.

### PR DESCRIPTION
**Pull request by bergentroll**
I don't like current icon design, cause it does not fit to android design, also dog with letter instead eyes breaks my mind. I believe, that dog should bring you fresh mail in it's jaws.
So, I make new cute icon, I hope, it's near Google's material design conception. And it contains one 
complaisant young canine, of course!
If you refuse to change app icon, may be you'll just add an option to choose design. I believe, many users agree with me about current icons design.
P. S.: thanks for great libre application!
canine
canine

### CODE REVIEW

**Comment by dschuermann** [comment]
I like the idea of having a new icon :+1: 
I am not entirely sure of this one. Has someone thought about getting rid of the dog entirely? What about an envelope with a dog paw mark on it?

**Comment by bergentroll** [comment]
It's good idea about a dog's paw on an envelope, but it is so clear form, that dog brings you letter in the mouth, isn't it?=)
Also I know, that current dog is relate to Doctor Who, but old Doctor universe's beauty is too specific.

**Comment by cketti** [comment]
The "K-9" in K-9 Mail is a reference to the robot dog from Doctor who: https://en.wikipedia.org/wiki/K9_(Doctor_Who)

So while a new icon would be nice, it can't just be "something with a dog".

**Comment by Valodim** [comment]
A new icon is definitely a good idea, and I very much appreciate someone coming up with concrete suggestions! I'm not so sure about the icon itself though, it looks a little uh, young? The idea of carrying the envelope in its mouth sounds reasonable on paper, but it might just not reasonably fit on an icon size.

While it would be nice to keep the Doctor Who K9 namesake, having that as a hard requirement might prove too restrictive if we want a nice new icon in material style.

**Pull request closed without merging**
