### PR TITLE
In recipient contact selection, display favorites first

### PR DESCRIPTION
**Pull request by starshipcoder**
In recipient contact selection, display favorites first

Fix the sorting was case sensitive

### CODE REVIEW

**Review by cketti — CHANGES_REQUESTED** [review]
Displaying starred contacts at the top is a good idea. But I don't see the need for the section headers. I think it's enough to just change the sort order (starred, times contacted, name).

**Comment by starshipcoder** [comment]
I think it is interresting for the user to understand the sorting and see K-9 use the contact starred flag
Maybe only a star at the end of the contact line as a compromise?

**Comment by cketti** [comment]
Users generally know which contacts they have starred. I don't see how displaying this information adds much value.
Also, users might then realize that starred contacts are always displayed first. But the order of starred contacts might still change depending on the number of times contacted. So displaying a star is not enough for users to have a chance to figure out the sort order.

**Comment by starshipcoder** [comment]
Done

Thank you for review

**Review by cketti — APPROVED** [review]

**Comment by cketti** [comment]
Thanks :+1:

**Pull request merged**
