### PR TITLE
Add \Draft flag to draft messages

### PR DESCRIPTION
**Pull request by BotQ**
As stated in title, there was a problem with setting "Draft" flag. If there is something wrong with this pull request please comment, it is my first contribution to this project.

See issue #3199

### CODE REVIEW

**Comment by BotQ** [comment]
Probably you are right. I will check it tomorrow.

**Comment by BotQ** [comment]
Changed `handleFetchResponse()` as cketti suggested.

**Comment by cketti** [comment]
@Valodim: Since you are currently working on drafts, can you please give this a test run with an actual server?

**Comment by Valodim** [comment]
Will do

**Comment by Valodim** [comment]
Tested creating a draft, clearing local folder, redownloading -> \\Draft flag is correctly set, uploaded, and applied on download - but not on older messages.

@cketti Thoughts on whether to do anything with `handleSendFailure`, and `SYNC_FLAGS`? Also, do you know if this is handled correctly if the FLAGS reply from an EXAMINE doesn't include \\Draft?

Thinking ahead, it probably makes sense to have a canonical way to determine whether a message is a draft or not, that takes other factors into account, e.g. if there is a thunderbird draft header. Not for now though.

**Comment by BotQ** [comment]
There is no column called "draft" in messages table and adding draft in `LocalMessage.setFlag` crashes app. Should I modify database schema then?

**Comment by cketti** [comment]
Some flags have their own column for faster database queries. I don't think we need that for the draft flag.

**Pull request merged**
