### PR TITLE
Add workflow for Update Gradle Wrapper Action

### PR DESCRIPTION
**Pull request by cristiangreco**
Hey there 👋, first of all thanks for your work on the K9 app!

I've got a suggested change: would you be willing to use [this GitHub Action](https://github.com/gradle-update/update-gradle-wrapper-action) to automatically keep Gradle Wrapper updated to latest release? (I've recently created the action and seeing it being used in such a popular project would definitely help me spread the word!)

**So what does "Update Gradle Wrapper Action" do?** It can be configured to run at scheduled intervals (e.g. daily or weekly) and will check whether the Wrapper script in the repo is up-to-date to the latest Gradle release: in case a new Gradle version is available, it will create a PR to update the Wrapper. And that's it!

**Why is that a good thing?** Well, first of all it alleviates the chore of manually updating the Wrapper -- the action will keep track of new Gradle releases for you!. More importantly, it boosts security around the Wrapper update and usage processes: this action verifies that the `gradle-wrapper.jar` file has not been tampered with (uses checksum comparison), and it sets the `distributionSha256Sum` property so that the new Gradle binary itself will be verified locally upon download.

In this PR I propose adding a new workflow which runs the action every day at midnight (but feel free to adjust the frequency as you prefer). I've verified it works correctly in my fork of the repo, and you can [see here](https://github.com/gradle-update/k-9/pull/1) how the generated PR looks like (it will bump the Wrapper from 6.5.1 to 6.6.1).

The action is under active development, you can have a look at the [list of inputs](https://github.com/gradle-update/update-gradle-wrapper-action#action-inputs) currently supported. There's new features coming up soon and if you'd like to request any particular change just let me know!

Hope you can find this useful and the project can benefit, would love your feedback! ❤️

### CODE REVIEW

**Comment by cristiangreco** [comment]
PS: I've noticed you use the [Wrapper Validation](https://github.com/k9mail/k-9/blob/master/.github/workflows/gradle-wrapper-validation.yml) action on `pull_request` events. Be advised that the check won't run on PRs created by _Update Gradle Wrapper_ action, but that is totally safe!

This happens due to a limitation of the `GITHUB_TOKEN` secret, which won't trigger any new event on PRs created by actions. You could work around by using a personal access token ([more info](https://github.com/gradle-update/update-gradle-wrapper-action#repo-token)) but that's not really needed as _Update Gradle Wrapper_ already verifies the integrity of the jar for you (that's literally the security advantage the action brings you).

**Comment by cketti** [comment]
Thanks for the pull request.

We usually update the Gradle Wrapper when we update the Android Gradle Plugin (AGP). In the past newer Gradle versions haven't always worked with the AGP version we were using. So I'd rather not have this automated. 
In general I hate having to fix the build. So usually K-9 Mail is not among the first projects to update to a new version. I keep an eye on reports by fellow Android developers. And when no problems are found (or a bugfix release of either Gradle or AGP has been published) we'll switch to the new versions.

Your GitHub Action does sound useful though :+1: I'll keep it in mind for non-Android projects.

**Comment by cristiangreco** [comment]
Hey @cketti, thanks for your reply!

This is actually quite useful feedback. So, if I read it correctly, you don't necessarily want to update to the latest Gradle release until you're comfortable that it doesn't break your project and it works well with the AGP version you use, is that correct?

To put it in another way, you might want to stick to a specific major/minor version for a while, e.g. you could decide to use `5.x` or `5.6.x` and only get patch-level updates. Would you find such a feature useful at all? I'm happy to implement that if you want to give it a try! 😊

**Comment by cketti** [comment]
> This is actually quite useful feedback. So, if I read it correctly, you don't necessarily want to update to the latest Gradle release until you're comfortable that it doesn't break your project and it works well with the AGP version you use, is that correct?

Almost. See below.

> To put it in another way, you might want to stick to a specific major/minor version for a while, e.g. you could decide to use `5.x` or `5.6.x` and only get patch-level updates. Would you find such a feature useful at all? I'm happy to implement that if you want to give it a try!

Not really. I don't want to update at all unless necessary (new stable AGP version). There's no infrastructure team taking care of these things. Every second spent with the build system is time that doesn't go into app development. 

If you want to volunteer maintaining our build tools I'm happy to give it a try ☺️ 
(You'd have to make sure new versions also work fine with Android Studio. I'm not sure if this can be automated easily.)

**Pull request closed without merging**
