### PR TITLE
Fix setup back navigation

### LINKED ISSUE #3971: App Closes On Pressing Back Button In Manual Setup
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
App should go back to the previous page.

### Actual behavior
App closes.

### Steps to reproduce
1. While creating new account, click on Manual setup
2. Press back Button
3. App closes

### Environment
Android version:
API 24

### PR DESCRIPTION
**Pull request by Monkey-Matt**
Previously pressing back during setup would exit the app from any setup screen when you would expect it to navigate to the previous step in the setup. Then reopening the app would launch the message list with an account that wasn't complete which led to problems/crashes.

This change allows for back navigation during setup. And when launching k9 it removes any accounts that have not finished setup so that we don't use the app with broken accounts.
Fixes #3971, #4797, #5044

I realize deleting incomplete accounts this way isn't the tidiest solution but should be good enough until wider work can be done around the setup flow.

### CODE REVIEW

**Comment by cketti** [comment]
Thanks. I haven't yet run the code. But it looks like this would remove all existing accounts that were created using the previous setup code. 
Instead of creating a migration to flag the existing accounts as having completed setup I'd change the flag to "setup in progress" and if the key is missing (on accounts that existed prior to this change) we assume setting up these accounts was completed successfully.

**Comment by Monkey-Matt** [comment]
In the `AccountPreferenceSerializer` it defaults to true when reading `isFinishedSetup` which I believed would cover the case of existing accounts that don't have this field. 
```
val isFinishedSetup = storage.getBoolean("$accountUuid.isFinishedSetup", true)
```
Do I misunderstand or is there a better way to handle it?

**Comment by cketti** [comment]
> In the `AccountPreferenceSerializer` it defaults to true when reading `isFinishedSetup` which I believed would cover the case of existing accounts that don't have this field.

Sorry, I missed that. You're right, it does cover that case :+1:

**Comment by cketti** [comment]
Thanks :+1:

This new functionality introduced/exposed a bug. See issue #5088. It's not a high priority issue. But I'd be awesome if you could take a look.

**Comment by Monkey-Matt** [comment]
Awesome thanks for taking a look through and merging. 

A shame I missed that bug. I'll try take a look in the next day or two, thanks for pointing it out

**Pull request merged**
