### PR TITLE
Kotlin migration

### PR DESCRIPTION
**Pull request by pueffl**
Migration to Kotlin 3.11

This pull request is based on branch androidx_migration.

### CODE REVIEW

**Comment by cketti** [comment]
Please don't create pull requests that depend on changes from another open pull request. It makes reviewing harder because one has to figure out which changes belong to which pull request.
Also, chances are the first pull request won't get merged without additional changes. So the branches diverge which makes reviewing even harder and also creates unnecessary branches in the commit graph.

Feel free to rewrite this branch to only contain the relevant changes on top of K-9 Mail's master branch once the androidx migration has been merged. But it's probably easier to just create a new pull request.

**Comment by pueffl** [comment]
Well, this was not so easy as it is based on the androidx migration. I will create a new pull request based on your androidx migration.

**Comment by cketti** [comment]
Thanks. But please only do it **after** the branch has been merged. It's quite possible my branch needs changes before it's ready to be merged.

**Comment by pueffl** [comment]
Ok.

**Comment by pueffl** [comment]
Closed because of new pull request with rebase.

**Pull request closed without merging**
