### PR TITLE
Update changelog for 5.300

### PR DESCRIPTION
**Pull request by cketti**
It's possible the inclusion of Esperanto is useless without the language selection setting. Maybe we have to bring it back.

### CODE REVIEW

**Comment by Valodim** [comment]
If there is doubt, maybe we better not remove it in the first place?

**Comment by Valodim** [comment]
just checked, and Esperanto is unsurprisingly not available as a system language

**Comment by philipwhiuk** [comment]
It might be useful on non Google builds - I don't know if Lineage OS adds more languages.

Oddly the Google keyboard app does support it. I guess it's easier to include a language than translate all of the system...

I think either we should re-implement it and test that everything is translated or we should not bother.

**Comment by cketti** [comment]
We'll bring back the language setting before releasing 5.300.

**Pull request closed without merging**
