### PR TITLE
Recipient select view issue

### PR DESCRIPTION
**Pull request by markcapella**
Please ensure that your pull request meets the following requirements - thanks !

* Follows our existing [codestyle](https://github.com/k9mail/k-9/wiki/CodeStyle).
* Does not break any unit tests.
* Contains a reference to the issue that it fixes.
* For cosmetic changes add one or multiple images, if possible.

### CODE REVIEW

**Comment by markcapella** [comment]
Still getting familiar with GIT ... this is to fix:
Reproducible RecipientSelectView bug introduces extraneous chars into text #3257

**Comment by cketti** [comment]
I checked the [documentation](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager.html#updateSelection(android.view.View,%20int,%20int,%20int,%20int)) in order to find out if it's safe for us to call that method. Unfortunately, it couldn't even tell me if `-1` are valid arguments.
But reading some of the `MultiAutoCompleteTextView`, `AutoCompleteTextView` and `TextView` source leads me to believe we a) shouldn't come near this method b) replacing text should work fine as is and the behavior you're seeing is probably a bug in the soft keyboard you're using.

**Comment by markcapella** [comment]
Oh yes. My preferred is SwiftKey and switching to Samsung Keyboard on my Edge resolves the issue. I should have noted that in the OP.

I borrowed the solution from some basic code I contributed to in Firefox mobile [0]. It triggers the reset here [1].

I'd remembered it, modified it to maintain Selection start/end for this particular issue, and when it worked wasn't terribly surprised.

Thanks for looking! I guess I'll post something to the library GITHUB for |tokenautocomplete| to see if helps their users' keyboard handling.

[0] https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/gecko/GeckoInputConnection.java#274

[1] http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/2.3.4_r1/android/view/inputmethod/InputMethodManager.java#InputMethodManager.updateSelection%28android.view.View%2Cint%2Cint%2Cint%2Cint%29

**Comment by Valodim** [comment]
@cketti Please backport this fix too, the buggy behavior is very annoying for affected keyboards

**Pull request merged**
