### PR TITLE
WIP - Add support for IMAP ID command - RFC 2971

### PR DESCRIPTION
**Pull request by philipwhiuk**

### CODE REVIEW

**Comment by cketti** [comment]
:+1: 

A couple of notes:
* We already have too many settings. Let's not make this another one. Always sending the ID command should be fine.
* I feel the amount of information sent is a bit much. I'd limit it to 'name' and 'version'. That information should be enough to find our contact details using a search engine. The name of the app should be "K-9 Mail".
* We should avoid hardcoding app-specific stuff in the library project. A user of k9mail-library should be able to pass in the values that are used as arguments to the ID command.
* Parsing of the ID response could use stricter format checking. Following the `*Response` class pattern should make it easy to add tests for that.
* Please try to keep PRs focused. Adding unrelated tests could be a separate pull request.

Side note:
I don't like the grouping of tests via comment. If you feel such a grouping is necessary please create a separate test class per group.

**Comment by philipwhiuk** [comment]
The RFC specifically mentions privacy considerations. That's the main justification for the setting. We've always been a privacy focused app so it seemed reasonable. We already have a user agent privacy setting flag for example.

I didn't actually add unrelated tests, I just reordered them so they were listed in a logical order. Probably should have been a separate commit though. I'm not a fan of comments either - it generally means your base class is doing too much. We could have a ConnectionOpener class that solved this.

I'll probably wait until rhari's IMAP rework lands then tidy up and rebase this.

**Comment by Valodim** [comment]
I find the usefulness of this feature questionable, in comparison to the required extra roundtrip. On top of that there's the privacy concerns, and a setting for this is just confusing to everyone who has never read an RFC (which is everyone).

**Comment by philipwhiuk** [comment]
I prototyped the connectionopener strategy idea: https://github.com/philipwhiuk/k-9/commit/49851ab24e10bc730209e02f16aa4fdca2fa7249

> I find the usefulness of this feature questionable, in comparison to the required extra roundtrip.

It makes K-9 a responsible well behaved email client.

> And a setting for this is just confusing to everyone who has never read an RFC (which is everyone)

We currently have a "User-Agent" privacy setting which equally confusing and aimed at the same privacy question. (One option is to use the same privacy setting for both with some slightly new text).

**Comment by cketti** [comment]
I didn't look closely at the "connectionopener strategy" prototype. There's a lot of changed lines. What I meant was handing a `ClientIdentification` data structure that holds information like client name and version to the library. The library would then use this data structure to fill in the arguments to the ID command.

Anyway, I'm with @Valodim regarding usefulness vs. cost. Maybe we should postpone this until we support sending multiple commands at once. That way we don't add an additional roundtrip.
And maybe by then we've reorganized the settings UI so we can add a setting for this to the advanced settings screen that is hidden by default.

**Comment by Valodim** [comment]
I would be fine with this if it didn't take an extra roundtrip, and merging with the other user-agent setting sounds reasonable.

With the extra roundtrip I'll vote against this one, since I consider the benefit marginal at best. I would be very surprised if we ever got a bug report from some mail server admin based on this id, it's far more likely that users notice something being off and report bugs, except maybe for bugs that show no actual symptoms.

**Comment by cketti** [comment]
The benefits of using the ID command seem small.

**Pull request closed without merging**
