### PR TITLE
Update build/libraries/API/SDKs/Java/tools + basic runtime permissions (Android Studio 3.1)

### PR DESCRIPTION
**Pull request by fat-tire**
I was annoyed by the inability to resize windows in my chromebook so I built K9 with the Android Studio 3.1 that went into beta today... and... now I can resize windows.

Note:  Google has also [announced that all apps in the Play store must update their targeted APIs starting in November 2018](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html).

image

On the Chromebook, K9 is nice but the holo theme looks grey and dingy by modern standards.  Material design can be enabled with the changes in #3175.

WHAT THIS COMMIT HOPEFULLY DOES:

* Update gradle plugin to latest to date in Android Studio 3.1 beta 1
* Update gradle from 3.3 to 4.5.1 release
* Update target API from 22 to 27 (min now 14)
* Update to Java 1.8
* Enable new Dex compiler
* Use new "implementation" syntax in build.gradle
* Update (most?) non-testing google/3rd party libraries to latest
* Add simple default notification channel (for Android 8+ compatibility)
* Handle runtime permissions for contacts/storage

DOES NOT DO:
*  A material conversion (See #3175 for this)
*  Update most testImplementation libraries

Cheers!

Note:  Rolling build failed with "_....some licences have not been accepted_".  No big deal.

### CODE REVIEW

**Comment by philipwhiuk** [comment]
As nice as it would be to use the latest libraries and features we can't reasonably merge this before we fix the permissions stuff. Crashing because people uncheck an option is not okay.

That said, it's a good overview of what we want to do after that's solved so it's a useful reference point.

**Comment by fat-tire** [comment]
Yes of course.  This is meant as a base to build on.

If i have time I'll take a closer look at  PR #3118 and see about tackling the contacts permission next unless @philipwhiuk or someone else beats me to it.   That plus the material stuff in #3124 will be pretty great.  In the meantime, I'm also going to see if I practically encounter any issues on the chromebook-- but so far so good. 

I do see room for immediate UI improvement on the chromebook, such as the need for back buttons on the preference screens (instead of having to tap ESC), catching ^W on the keyboard to prevent accidental closure, and perhaps changing ^S to auto-save to draft rather than auto-send (big difference!), ^N for a new window (instead of move down to next message, which should be the down arrow) and a few other keyboard shortcuts that are common on most desktop apps.

**Comment by fat-tire** [comment]
Update:  Implemented the Read Contacts run-time request.  I'm just gonna test it a bit and then I'll either add it to this PR or create a separate one (**depending on if anyone has an opinion on this**).  I did not do the External Storage permission as there's a version in #3118 already, which I think will be replaced with the Storage Access Framework per #2844 

Anyway, just wanted to let people no so no one else works on it.  I'll play with it and send in a few hours.  Want to make sure also that I got all the places where the permission is used.  For some strange reason the lint check seems to be missing in AS3.1, at least on my computer.

**Comment by fat-tire** [comment]
Seemed to work okay so I added to this commit.  Feel free to change it as you like.

**Comment by fat-tire** [comment]
Okay I added a quick WRITE_EXTERNAL_STORAGE that works a little differently than #2844.  It's very simple and should be tested more thoroughly than I did.  There may be some other methods that require permissions that I missed or some back-compatibility stuff I missed.

But give or take whatever tweaking people want to do, this brings us up to current.

**Comment by fat-tire** [comment]
One last addition to this and then I'll wait for comment--  I added material design in another commit in my repo,which I won't submit as one exists already:

[Material with AppCompat (building on commit from @philipwhiuk)](https://github.com/fat-tire/k-9/commit/d7a5f01ec2c56824190116f08d3cdef2bda39ab1)

If you use all this, you should get the latest stuff w/the permissions request + Material design.  And possibly bugs.. who knows.  I'll dogfood it on my chromebook, but it may not test well for other devices w/older Android or smaller screens or whatnot.  YMMV.

Cheers.

**Comment by cketti** [comment]
Thanks for looking into this. Unfortunately, it's not quite that easy. In order to raise `targetSdkVersion` to 27 a lot more changes are necessary. Most notably changing the background sync to be compatible with Oreo's [background execution limits](https://developer.android.com/about/versions/oreo/android-8.0-changes.html#back-all).

I'd like to get there in small steps. I don't see value in having a pull request with a collection of patches that make things just barely work. So I'm closing this pull request.
But please feel free to create pull requests for the individual patches, e.g. requesting permissions at runtime. Being able to raise `targetSdkVersion` to 23 would be a good first step.

To increase the chance of pull requests being merged quickly please try to keep them small and make sure the code follows our code style.

**Pull request closed without merging**
