### PR TITLE
Update TOP_LEVEL_DOMAIN_STR_FOR_WEB_URL to match more new TLDs

### LINKED ISSUE #1497: Some TLDs are not converted to links when using plain text
### Expected behavior
when receiving plain text emails with URLs containing TLDs like "link" or "online" the URL should be converted into a link.

### Actual behavior
www.whatever.link or www.whatever.online are NOT converted into a link. It's just plain text. Not clickable.

### Steps to reproduce
1. receive a plain text email containing an URL with a TLD like "link" or "online"

### Environment
K-9 Mail version: 5.010

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### PR DESCRIPTION
**Pull request by helmo**
new regex produced by https://github.com/irccloud/android/blob/master/make-iana-tld-pattern.py cbe04ae

I had the problem that 'http://example.consultig/' was not shown as link.

This will probably also fix #1497

### CODE REVIEW

**Comment by philipwhiuk** [comment]
I'm not opposed to this being merged as a stop-gap measure but I do think it's untenable. We don't try and filter actual domains like this and I'm unconvinced it's now practical to match TLDs given the generics that are now present.

**Comment by helmo** [comment]
yes, +1 for using a library for that. I just hope there's someone with time to do that.

**Comment by cketti** [comment]
I imagine this has some performance implications. Did you test this against a text body of say 500kb?

**Comment by helmo** [comment]
Sorry, I don't  have the setup here to test that.

**Comment by cketti** [comment]
We'll just use the alpha versions to test the performance in "production".

**Comment by cketti** [comment]
@helmo: Thanks for the pull request!

**Comment by philipwhiuk** [comment]
If this works fine, one possibility is to have `make-iana-tld-pattern.py` as part of our build process so it automatically includes new ones when we do a release.

**Comment by cketti** [comment]
@philipwhiuk: I want us to move away from using regular expressions to detect URIs. See https://github.com/k9mail/k-9/issues/1223#issuecomment-203466421

**Pull request merged**
