### PR TITLE
Some new icons.

### PR DESCRIPTION
**Pull request by bergentroll**
Hey guys! What about [hypercube](http://tardis.wikia.com/wiki/Hypercube) as new logo?
It's timelords mail!
cube
cube
cube

### CODE REVIEW

**Comment by philipwhiuk** [comment]
If you want to rename the app, it's better to discuss it (on the mailing list or an issue I'm not fussed where you start, probably both is necessary). We are likely to just close PRs like this. I appreciate you are trying to improve the app's icon and can't see how to do that by keeping the dog - but re-naming would affect a lot of places - app stores, dev lists, user lists. We'd also need to do a detailed search for existing apps that might conflict - more than one project has had to abandon a name (even when the argument looked thin) because it was contested.

For an open source app - K-9 was also fortunate enough to be Ars Technica and other places. You'd lose all of that by re-naming.

And K-9 comes partially from name of the Linux mail client, mutt as well from Doctor Who.

**Comment by bergentroll** [comment]
Oh, no, it's not about new naming!
What I mean — people unfamiliar with Dr. Who universe anyway confused by strange robo-dog with a mail instead of eyes (it happend to me some years ago when I tried the K-9 first time). So let's change the icon. For those who don't know timelord saga, tesseract icon will be just an eye-candy button, also for Doctor fans it will be sort of an easter egg.

**Comment by cketti** [comment]
I'm very reluctant to move away from the 'robot dog from Doctor Who' theme. It's a brand and the 		recognition value is very high.
Moving away from that and not using any symbol commonly associated with email is just not working at all.

**Comment by bergentroll** [comment]
Ok, newermind.
I'll keep trying=)

**Pull request closed without merging**
