### PR TITLE
WebView: Open links in external Browser

### LINKED ISSUE #587: Open Links in browser not inline
Tested on current git master:
Links are currently opened inline in the WebView not in my favorite browser.

### PR DESCRIPTION
**Pull request by m0vie**
1a20ca06f1ef8ab0d4a5952dcc614973014b50c7 connected a WebViewClient
to the WebView. But as soon as a client is connected, the WebView
stops handling links itself and tries to display everything on
its own.

Override shouldOverrideUrlLoading() and replicate what Android's
default WebView does if no WebViewClient is connected to work
around this.

This fixes #587.

### CODE REVIEW

**Comment by dschuermann** [comment]
looks good to me.

**Comment by cketti** [comment]
When starting the activity to open a link we should probably use [FLAG_ACTIVITY_NEW_TASK](https://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_NEW_TASK) so  it won't use our task. On Lollipop can use [FLAG_ACTIVITY_NEW_DOCUMENT](https://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_NEW_DOCUMENT).

I haven't actually tested this and don't know if there are any drawbacks. Does anyone feel like investigating this?

PS: Chrome seems to automatically do the right thing. I assume the receiving activity forwards to another activity using the right task so it doesn't depend on the `startActivity()` behavior of the calling app.
So the first task would be to find (or write) a simple app that doesn't do any activity task magic itself.

**Comment by m0vie** [comment]
I'm not sure if that's really needed. I took the code from the Android 4 source and it doesn't use any NEW_TASK/NEW_DOCUMENT flags:
https://android.googlesource.com/platform/frameworks/base/+/android-4.3.1_r1/core/java/android/webkit/CallbackProxy.java#255

**Comment by cketti** [comment]
@m0vie From the reports I get this seems to be a real pain point for users.

For what it's worth, the Email app seems to use `FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET` (which is the same as using `FLAG_ACTIVITY_NEW_DOCUMENT` on Lollipop): https://android.googlesource.com/platform/packages/apps/UnifiedEmail/+/master/src/com/android/mail/ui/AbstractConversationWebViewClient.java#134

**Pull request merged**
