### PR TITLE
Remove "hide subject in notifications" setting

### PR DESCRIPTION
**Pull request by cketti**
This feature didn't work properly. And the "lock screen notifications" setting offers very similar functionality.

Related to #3707.

### CODE REVIEW

**Comment by Le1b1** [comment]
Doesn't remove this the possibility to hide the message content from the OS?
I really think this was a nice privacy feature.

**Comment by cketti** [comment]
Not trusting the OS isn't really an option. Are you concerned about other apps reading the contents of K-9 Mail's notifications? This requires a special permission.

**Comment by Le1b1** [comment]
> Not trusting the OS isn't really an option.

It's about data reduction, kind of enabling screen security.
I know it's not a 100% protection against the OS, but it raises the bar.
Signal isn't offering it without reason. (I guess 😄)

**Comment by cketti** [comment]
I'm not convinced. If you don't trust the OS, the only sensible option is to not use it.

I guess reducing the amount of information in a notification makes sense if you're worried about [shoulder surfing](https://en.wikipedia.org/wiki/Shoulder_surfing_(computer_security)). But by default K-9 Mail doesn't pop notifications on the screen. The only indicator that there's a new message is the icon in the status bar, the notification sound, and/or vibration. 

Opening the notification drawer then comes with the same risk of exposing message content as opening the app. Adding a setting just to make opening the notification drawer "safer" feels like a lot of effort for very little gain.

**Pull request merged**
