### PR TITLE
Keep Reply-To header when editing a draft

### LINKED ISSUE #4219: Opening Draft loses Reply-To header
### Expected behavior
If I save a draft with a Reply-To header and open it again, the chosen Reply-To header should still be used.

### Actual behavior
If you open a draft the Reply-To header is lost.

### Steps to reproduce
1. Create a mail with an identity with a Reply-To header
2. Save draft
3. (check headers with other IMAP client, header is still there)
4. Open draft
5. Send/Save again
6. (no Reply-To header in send mail/draft folder anymore)

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### PR DESCRIPTION
**Pull request by plan3d**
Resolves #4219

### CODE REVIEW

**Comment by cketti** [comment]
This is a relatively large change. It would be nice if you could write a few sentences on what you did in this pull request and why.

It would probably be easier to review this pull request if you had split the change into smaller commits.

**Comment by plan3d** [comment]
I split my changes in four commits. Please review again and tell me if I should explain some of my changes

**Comment by cketti** [comment]
I'd like the fix to be much smaller. See https://github.com/k9mail/k-9/issues/4219#issuecomment-904100095

It's commendable that you extracted some code to make it testable. But the long-term goal is to get rid of the identity header (see #902). I believe the refactoring in this PR makes it harder to achieve that goal.

**Comment by cketti** [comment]
See #5668

**Pull request closed without merging**
