### PR TITLE
Importance (RFC 2156) and X-Priority support

### PR DESCRIPTION
**Pull request by philipwhiuk**
A reworked and rebased version of #2426 tested against Microsoft Outlook.

See notes on supported headers: https://www.chilkatsoft.com/p/p_471.asp

Given even Microsoft no longer sends `X-MSMail-Priority` I didn't add it.

### CODE REVIEW

**Comment by Valodim** [comment]
Code looks fine, but I wonder: do we really want to support "low priority" mail? This seems like a useless concept to me any way I look at it. I think I would prefer a simple "isHighPriority" flag.

**Comment by philipwhiuk** [comment]
There's Outlook filters you can set-up that automatically (for example) mark some sender emails as low priority.

**Comment by Valodim** [comment]
That sounds like a job that's better solved with tags/labels than priority headers

**Comment by cketti** [comment]
I find such headers not particularly useful. The first thing I'd want if we merged this, is a setting to disable the visual indicator in notifications :(

I guess it could be nice as input signal if we supported notification rules. 
Example: mail is from "boss@company.com" and priority header says "high" -> priority notification

It also adds to the UI clutter in the compose screen. I'd rather not add support for setting priority headers before the UI overhaul. We'll probably want to add a slide out menu on the right that includes message options like setting a priority, requesting a read receipt, PGP/MIME vs PGP/Inline mode, etc.

On a side note: I'd like `MimeMessage` to become super small and want all special header handling code to live in separate classes.

**Comment by cketti** [comment]
Not adding this functionality for now.

**Comment by philipwhiuk** [comment]
:(

**Pull request closed without merging**
