### PR TITLE
Provide a better explanation as to why sync is disabled

### PR DESCRIPTION
**Pull request by philipwhiuk**
'Sync disabled' is very vague. Providing more information about why sync is disabled is a small first step towards fixing synchronisation based issues.

### CODE REVIEW

**Comment by philipwhiuk** [comment]
Oh and this demonstrates quite clearly doze means you don't get a Connectivity change intent when Doze ends. #998

**Comment by gdt** [comment]
Separately from fixing the doze issue, I think increased clarity why k-9 is not syncing is very helpful, both for regular users, and for debugging.

**Comment by cketti** [comment]
I like this for the development version. For a release build I think it's better to get rid of the message entirely. I see little value in letting users know when the app is attempting the next poll. Especially with Doze there is no way to tell if it'll actually happen.
We also need to get rid of the error state where the app stops poll attempts completely. "Syncing disabled" shouldn't be a thing.

**Comment by philipwhiuk** [comment]
Extra detail only shown in debug mode now.

**Pull request merged**
