### PR TITLE
Runtime permissions - External Storage permission

### PR DESCRIPTION
**Pull request by philipwhiuk**
Contacts is more deeply embedded so that's a bit more work. But here's a PR for the external storage permission handling.

### CODE REVIEW

**Comment by cketti** [comment]
The change to `Accounts` shouldn't be necessary because we don't use direct access to external storage when exporting settings on KitKat and above. See:

https://github.com/k9mail/k-9/blob/a36254dbc0fcd2f307126cf644c0c26c8d557cb0/k9mail/src/main/java/com/fsck/k9/activity/Accounts.java#L1929-L1939

I'd like us to use the same approach for "save attachment" instead of requesting external storage permission when saving attachments. See #2844.

We still allow the user to move the message database to external storage. In that case we also need to request the permission.

**Comment by philipwhiuk** [comment]
Yeah, I saw this is as a short term easier fix. I'll remove it for Accounts though.

**Comment by wiktor-k** [comment]
Can this be closed in favor of #3818?

**Comment by Valodim** [comment]
Yup :+1:

**Pull request closed without merging**
