### PR TITLE
Added swipe to refresh to drawer

### LINKED ISSUE #4018: "Refresh all folders" button
In previous versions of k9, it was possible to manually refresh all folders on the folders screen. That screen is now a folder manager only. I suggest to add a "Refresh all" button somewhere on the main activity.

Do you have a suggestion where the button could be displayed?

### PR DESCRIPTION
**Pull request by ByteHamster**
Closes #4018

### CODE REVIEW

**Comment by ByteHamster** [comment]
After you fixed my workaround for manual refresh, I needed to come up with another solution :D

Some thoughts:

- I think this will also work with the new MaterialDrawer library (at least they still use that layout in master)
- The RelativeLayout that might look useless is necessary for the footer views (the library assumes it can assign RelativeLayout.LayoutParams and crashes without that RelativeLayout)
- Would it be a good idea to also refresh the folder list here?

**Comment by cketti** [comment]
> After you fixed my workaround for manual refresh, I needed to come up with another solution :D

I like it :smile: 

> Some thoughts:
> 
> * I think this will also work with the new MaterialDrawer library (at least they still use that layout in master)

Thanks for checking :+1:

> * The RelativeLayout that might look useless is necessary for the footer views (the library assumes it can assign RelativeLayout.LayoutParams and crashes without that RelativeLayout)

Please add a comment to the layout stating that.

> * Would it be a good idea to also refresh the folder list here?

We should probably always refresh the folder list when checking mail for an account. This can be a different PR, though.

I think I'd like it better if the spinning progress indicator was displayed on top of the folder list. IMHO that makes it more obvious that only the currently selected account will be refreshed. It looks like `swipeRefreshLayout.setProgressViewOffset()` can be used for this.

**Comment by cketti** [comment]
Another thing: can you please rebase this branch on current `master`?

**Comment by cketti** [comment]
Thanks. I tweaked the swipe behavior a little bit.

We still need to figure out what to do when the account list is displayed. Disable swipe to refresh? Or check all accounts?

It also looks like we the code currently doesn't handle the Unified Inbox. The refresh listener isn't set when the Unified Inbox is selected.

Note to future self: I don't like that the drawer is interacting with `MessagingController` directly. Fix this eventually.

**Comment by ByteHamster** [comment]
> We still need to figure out what to do when the account list is displayed.

Just tell me what you prefer. I only use one account, so I never open the list or unified inbox. 

Many users seem to be obsessed with the "Account overview" page. Maybe there could be an option (I know, options are not always a good thing) that opens the app in the account selector to please those users. In that case, refreshing all accounts with pull-to-refresh would probably be preferable.

**Comment by gdt** [comment]
I desire to have two email accounts configured in k-9, and want a page that shows unread in each, just like 5.600 does (semantically; I don't care much what it looks like).  I personally want both accounts use IMAP IDLE style push.   With swipe to refresh, I am assuming this is a "poll them now" command, similar to 5.600 refresh button, and I don't care if I push a button or swipe.   I also don't have a reason to want to check one and not the other, so if "check now" always checks all accounts, with no option to select which, that's ok.   I consider "check now" to be a workaround for network problems or push not working right.    In all of the above I think I'm pretty normal.

**Comment by cketti** [comment]
Then I guess we should refresh all accounts when the user swipes down while the account list is being displayed.

**Comment by cketti** [comment]
Nice. Thanks :+1:

**Pull request merged**
