### PR TITLE
add intent filter to main activty to provide default email application setting

### LINKED ISSUE #3231: k9mail as default email app
It should be possible to set k9mail as defualt email app. However there is no way to do so. 

Setting app as default is useful for example if one wants to start it by pressing "email" button on  hardware keyboard.

K-9 Mail version:
5.403

Android version:
7.0

### PR DESCRIPTION
**Pull request by dhebbeker**
Adds intent filter [ `CATEGORY_APP_EMAIL`](https://developer.android.com/reference/android/content/Intent.html#CATEGORY_APP_EMAIL) in order to provide the app's activity as possible default email application. This must be interpreted by Android and [set by the user outside of the application](https://github.com/k9mail/k-9/issues/3231#issuecomment-515759615).

- [x] Follows our existing [codestyle](https://github.com/k9mail/k-9/wiki/CodeStyle).
- [x] Does not break any unit tests.
- [x] Contains a reference to the issue that it fixes.  
  Fixes #3231 
- ~~For cosmetic changes add one or multiple images, if possible.~~
- [ ] Test, that the changes have a positive effect.

### CODE REVIEW

**Comment by dhebbeker** [comment]
As described in [this comment](https://github.com/k9mail/k-9/issues/3231#issuecomment-576395620) I was unable to observe any effects of the changes. I assume this is because the Android configurations I have available do not provide such a setting.

Maybe a user affected by #3231 (@taturati, @stonecrusher, @KlausH) or others could test it with their specific system? For conviniece I have build an [APK ready to test](https://github.com/dhebbeker/k-9/releases/download/v5.705-dev.add-mail-intent.1/k9mail-debug.v5.705-dev.add-mail-intent.1.fb72c9eca.apk). Please provide feedback in this pull request!

**Comment by cketti** [comment]
@dhebbeker: Thanks for working on this. 

I'm happy to merge this without testing on a real device beforehand. It looks good considering the documentation. Worst case is it doesn't work.

Can you please rebase this branch on current master instead of including a merge commit. Also, please use a descriptive commit message.

**Comment by dhebbeker** [comment]
Hello @cketti, 

thanks for the fast feedback!

> Can you please rebase this branch on current master instead of including a merge commit. Also, please use a descriptive commit message.

Done :heavy_check_mark:

**Comment by cketti** [comment]
Thanks!

**Pull request merged**
