### PR TITLE
Make the migration more resilient

### PR DESCRIPTION
**Pull request by Valodim**
If a single mail migration fails, that's no reason to reset the entire database. I added a catch-all, and an upper limit of failed mails before the migration routine gives up.

A fixed limit might not be the best option here, but it's simple and I couldn't think of a very good less-simple solution.

### CODE REVIEW

**Comment by philipwhiuk** [comment]
Given we and the user get told absolutely nothing about it either way it might as well be infinite. This is only really fixable by adding proper logging and triggering a 'crash report' for these cases so we can fix the updater.

I assume the reason it's 1 is because it means you'll leave garbage in the database.

**Comment by Valodim** [comment]
@cketti ping

**Comment by cketti** [comment]
I don't think we should ignore up to N failures and only reset then. Ideally, we notify the user of failure and give them the option to reset or cancel, which would deactivate the account until an app update can properly migrate the data. That's a lot of work, though. I guess that's why the current code simply recreates the database to allow moving on.

For now I'd like to keep the database reset for release builds. For debug builds we should crash instead of throwing away data.

**Comment by Valodim** [comment]
I imagine the 99% case is that some freak message or inconsistent db state breaks the migration, and simply ignoring the message won't break anything. It seems unlikely that other messages are influenced by the broken message, so throwing away the entire database seems a little extreme?

I agree though, we can crash in debug builds.

**Comment by cketti** [comment]
Closed in favor of #1340

**Pull request closed without merging**
