### PR TITLE
[WIP] Upgrade to MaterialDrawer v8

### PR DESCRIPTION
**Pull request by mikepenz**
Hi @cketti as noted here: https://github.com/mikepenz/MaterialDrawer/issues/2611 I looked into upgrading the drawer to MaterialDrawer v8 in this project. 

Along the way I also had to
- Upgrade to *Bridge* MaterialComponent theme (to not break AppCompat theming)
- Upgrade to FastAdapter v5.x

This PR is not yet ready for merge as it does not yet fully implement the exact same behavior as you had before with setting accent / selected color. 

I am not sure though if you shouldn't prefer proper accent theming and selected color theme via the theme (couldn't find a way to modify accent colors of the app but I guess perhaps something like that exists for individual accounts?) Please see under "Missing" the pieces which need to be adjusted

# Overview about the changes

- upgrade FastAdapter to v5.1.0
- upgrade to MaterialComponents (Bridge) Theme
- upgrade to MaterialDrawer v8.1.0
- introduce color fields no longer existing due to removed dependency on Materialize library
- remove no longer existing theme attributes, replace with materialDrawer style according to v8
  - introduce style for materialDrawer, specify custom selected color to the accent
- upgrade the message_list.xml to use the `DrawerLayout` and include the `MaterialDrawerSliderView` wrapped in a `SwipeRefreshLayout`
- remove obsolete classes
- upgrade to new API of MaterialDrawer v8 in K9Drawer.kt
  - NOTE: selected / accent coloring is currently not programmatically applied, only via style
  - possibly slight differences in UI
 - upgrade listener in MessageList.java for Drawer v8

# Missing

- https://github.com/k9mail/k-9/compare/master...mikepenz:feature/material_drawer_v8?expand=1#diff-5ae6b11fe363d41f3d9ddaa18d9f56caR266-R269

### CODE REVIEW

**Comment by cketti** [comment]
Thanks @mikepenz. This is most of the hard work done for #4667 :+1:

When playing around with this I noticed these issues:
- Background for selected item isn't always drawn (MaterialDrawer bug?)
  Steps to reproduce:
  - Open drawer while an account (not Unified Inbox) is selected, currently opened folder should show "selected" background
  - Pull-to-refresh
  - Selected item doesn't show appropriate background. Scrolling it out of view and back in fixes the issue
- Tapping an item in the list no longer closes the drawer. Is this an intentional behavior change in MaterialDrawer? Do we now manually have to close the drawer?
- `Widget.MaterialDrawerHeaderStyleCustom` is using inappropriate text colors (the background isn't `?attr/colorSurface`)
- The drawer seems to no longer be drawn under the status bar. Is this an intentional change? It also means the account header view is now taller than necessary.
- Scroll position is lost on orientation change
- The drawer is wider than before. It spans almost all of the screen width in landscape orientation, too. Is this an intentional change?

I probably won't have time to look into these issues myself before a new stable release is out. Any help would be greatly appreciated.

**Comment by mikepenz** [comment]
@cketti sorry for the late update. I have been looking into the various topics you reported and fixed most of them as far as I can say. 

Could you please have a look into providing the colors as you expect them to behave? I sadly don't fully know which ones it should have. 

For the scroll state I wonder if the next major update of RV will fix this by being able to control when the state of the RV is re-constructed after adding back the items?

**Comment by mikepenz** [comment]
Also I am really puzzled about:
```
/home/runner/work/k-9/k-9/app/ui/legacy/src/main/java/com/fsck/k9/ui/K9Drawer.kt:3:1: Imports must be ordered in lexicographic order without any empty lines in-between
```

It seems to be not happy if I remove the lines in between, but also not happy if I have them

**Comment by cketti** [comment]
Sadly Android Studio doesn't yet support defining the import order the way ktlint wants it to be. However, you can fix the formatting using `gradlew ktlintFormat`.

**Comment by mikepenz** [comment]
Ok thanks. applied this formatting :)

**Comment by cketti** [comment]
Thanks again :heart:

I rebased your changes and made some modifications so the drawer looks and behaves mostly like the old version. See PR #5169

**Pull request closed without merging**
