### PR TITLE
Tweak message list design (2)

### LINKED ISSUE #4110: Message list appearance
Right now the message list looks very dated. To move to a more modern look I suggest the following changes:

- [x] For unread messages display subject, sender (and possibly the date) in bold. See #4189
- [x] Don't change the background color for unread messages by default, i.e. make 'General settings > Display > Change colour when read' unchecked by default. See #4128
- [x] Align text (subject, sender, preview) with folder name in the toolbar. See #4177
- [x] Tweak icon to star a message. See #4124
- [x] Remove colored bar at the left that indicates which account a message belongs to. In list views where we mix messages from different accounts we probably still want to show some kind of indicator. See #4177 (change account chip), #4181 (hide chip)
- [x] Increase font size of subject line. See #4116
- [x] Reduce the font size of placeholder contact images a little bit. See #4123
- [x] Use material design colors for contact image placeholders. See #4162 

Experimental things (don't implement before all of the above is done):
- [x] Use more vertical padding for the message list items.
- [ ] ~~Use an outline for the box around the number of messages in a thread to make it less pronounced.~~
- [ ] For read messages use preview text color for subject and sender. That way unread messages stand out even more.
- [x] Experiment with list item divider options: full line, shortened line (see #1859), no line
- [x] Use color for starred messages (see #5512)
- [ ] Experiment with using Roboto Thin as font

If you want to help out with the implementation, please create a pull request that only deals with **one** item from this list. It's much easier to iterate on a pull request if there's only one change at a time.

### LINKED ISSUE #6692: improve the visibility of unread messages when using dark theme
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.400

### Problem you are trying to solve

The visibility and identification of unread messages using the dark theme is difficult, so I suggest to improve it perhaps by changing the color of read messages to gray

Here is a screenshot to demonstrate - this was taken on a OnePlus 6

Congratulations for the The team for this awesome app!

Screenshot_20230221-075643

### Suggested solution

Change the color of read messages to gray - here is a screenshot of the nine app which seems to be doing that

Screenshot_20230221-080208

### Screenshots / Drawings / Technical details

_No response_

### PR DESCRIPTION
**Pull request by cketti**
- Make sure there's space between subject and date
- Add en dash to separate sender name and preview text
- Use different text colors for read and unread messages
- Display date in same style as subject

|Before|After|
|-|-|
|image|image|
|image|image|

Closes #4110
Closes #6692

### CODE REVIEW

**Comment by sudwhiwdh** [comment]
Looking at the demo emails from this screenshot, I wonder if there shouldn't be an ellipsis in the subject.

"Verification Engineering: A Future ..."
instead of "Verification Engineering: A Future.."

**Comment by cketti** [comment]
That's because `android:ellipsize="marquee"` was used. I believe this only worked (long subjects were scrolling when the list item was focused) with hardware keyboards. I couldn't get the old behavior to work with the new layout. So I switched to `android:ellipsize="end"`.

**Comment by sudwhiwdh** [comment]
> So I switched to `android:ellipsize="end"`.

Are there any functional limitations associated with this change?

And I still ask myself: Isn't there always a space before an ellipsis?

**Review by wmontwe — APPROVED** [review]
LGTM

**Pull request merged**
