### PR TITLE
Add round icon

### PR DESCRIPTION
**Pull request by KoFuk**
Round icon added for Google Pixel devices.

### CODE REVIEW

**Comment by dexbleeker** [comment]
The build probably fails because targetSdkVersion is too low (version 25 needed).
https://github.com/k9mail/k-9/blob/master/k9mail/build.gradle#L58

**Comment by philipwhiuk** [comment]
Depends on #2108

**Comment by cketti** [comment]
Closing this PR as it's not something we'll get to very soon. I created issue #2252 to keep track of this, though.

**Comment by KoFuk** [comment]
Thanks.

**Pull request closed without merging**
