### PR TITLE
Enable fulltext imap search

### PR DESCRIPTION
**Pull request by infernix**
IMAP full text search was disabled in aea95b1493776d5e12ff984c91948e0451933eca due to the fact that no results are presented to the user.

In these commits I am re-enabling it with the assumption that we are going to fetch the message body when searching, because as far as I can tell this is the only way to present the search results. It may be better to fetch the body only when isRemoteSearchFullText() is true, but I am not sure how to check for that inside MessagingController.

I have tested this on the 5.0 branch and it is working well for me with Dovecot IMAP server using the Solr fts search plugin.

### CODE REVIEW

**Comment by cketti** [comment]
Thanks for taking the time to look into this issue and coming up with a patch.

However, this looks like it ignores all settings that limit how much of a message is downloaded. While that might work fine for the most common cases please imagine a scenario where the search term is found in a message with a 1GB large attachment. Downloading all of that message is clearly undesirable.

I think a better solution to this problem is to change the way the message list is displayed. Ideally, we should be able to display the search results without having to write them to the database. I have plans to change the message list code to support this, but it's currently not a high priority and quite a bit of work.

**Comment by infernix** [comment]
How about changing to FetchProfile.Item.BODY_SANE? That seems to respect getMaximumAutoDownloadMessageSize() so that would do nothing different than when the user would normally download a message in a poll?

**Comment by cketti** [comment]
That's better, but there's no guarantee the database search will return such a message. The text could be  in the part that wasn't downloaded. Or the server could interpret the search term differently than the local search, e.g. Gmail supports some advanced search features.

I want to do this right, rather than add a hack that works only 90% of the time.

**Comment by cketti** [comment]
Like I said, I want this feature implemented in a way that correctly displays the search results from the server.
Closing this PR. Issue #699 will keep track of the feature.

**Pull request closed without merging**
