### PR TITLE
Use json for serializing pending commands

### PR DESCRIPTION
**Pull request by Valodim**
This PR moves all pending commands from MessagingController, which were previously stored as `String[]`, into strongly typed data structures and extracts the serialization mechanism into its own `PendingCommandSerializer` which is then implemented using moshi to serialize the data into JSON objects.

Comes with with tests for serialization, a migration layer, tests for the migration, and a total of -300/+70 lines for MessagingController. Such a beauty.

### CODE REVIEW

**Comment by philipwhiuk** [comment]
Looks excellent.

**Comment by philipwhiuk** [comment]
I merged this into my local branch to test the code that's likely head into nextStable.

I can't be completely sure whether this is an issue of it not being upgrade-safe or just not being multi-run safe.

```
11-20 17:52:40.502 18176-18209/? E/SQLiteLog: (1) no such column: arguments

--------- beginning of crash
11-20 17:52:40.505 18176-18209/? E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
     Process: com.fsck.k9.debug, PID: 18176
     java.lang.Error: Exception while upgrading database
         at com.fsck.k9.mailstore.StoreSchemaDefinition.doDbUpgrade(StoreSchemaDefinition.java:39)
         at com.fsck.k9.mailstore.LockableDatabase.openOrCreateDataspace(LockableDatabase.java:381)
         at com.fsck.k9.mailstore.LockableDatabase.open(LockableDatabase.java:354)
         at com.fsck.k9.mailstore.LocalStore.<init>(LocalStore.java:194)
         at com.fsck.k9.mailstore.LocalStore.getInstance(LocalStore.java:219)
         at com.fsck.k9.Account.getLocalStore(Account.java:1329)
         at com.fsck.k9.search.SqlQueryBuilder.getFolderId(SqlQueryBuilder.java:111)
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:36)
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93)
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93)
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93)
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93)
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93)
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93)
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93)
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClause(SqlQueryBuilder.java:21)
         at com.fsck.k9.Account.getStats(Account.java:861)
         at com.fsck.k9.controller.MessagingController$22.run(MessagingController.java:2929)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
         at java.lang.Thread.run(Thread.java:761)
      Caused by: android.database.sqlite.SQLiteException: no such column: arguments (code 1): , while compiling: SELECT id, command, arguments FROM pending_commands ORDER BY id ASC
         at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
         at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
         at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
         at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
         at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
         at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
         at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
         at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
         at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1165)
         at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
         at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1204)
         at com.fsck.k9.mailstore.migrations.MigrationTo56.getPendingCommands(MigrationTo56.java:172)
         at com.fsck.k9.mailstore.migrations.MigrationTo56.migratePendingCommands(MigrationTo56.java:38)
         at com.fsck.k9.mailstore.migrations.Migrations.upgradeDatabase(Migrations.java:68)
         at com.fsck.k9.mailstore.StoreSchemaDefinition.upgradeDatabase(StoreSchemaDefinition.java:60)
         at com.fsck.k9.mailstore.StoreSchemaDefinition.doDbUpgrade(StoreSchemaDefinition.java:36)
         at com.fsck.k9.mailstore.LockableDatabase.openOrCreateDataspace(LockableDatabase.java:381) 
         at com.fsck.k9.mailstore.LockableDatabase.open(LockableDatabase.java:354) 
         at com.fsck.k9.mailstore.LocalStore.<init>(LocalStore.java:194) 
         at com.fsck.k9.mailstore.LocalStore.getInstance(LocalStore.java:219) 
         at com.fsck.k9.Account.getLocalStore(Account.java:1329) 
         at com.fsck.k9.search.SqlQueryBuilder.getFolderId(SqlQueryBuilder.java:111) 
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:36) 
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93) 
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93) 
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93) 
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93) 
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93) 
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93) 
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClauseInternal(SqlQueryBuilder.java:93) 
         at com.fsck.k9.search.SqlQueryBuilder.buildWhereClause(SqlQueryBuilder.java:21) 
         at com.fsck.k9.Account.getStats(Account.java:861) 
         at com.fsck.k9.controller.MessagingController$22.run(MessagingController.java:2929) 
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
         at java.lang.Thread.run(Thread.java:761)
```

**Comment by philipwhiuk** [comment]
I have a fix for that error which I added to my local branch here: https://github.com/philipwhiuk/k-9/commit/160880f83690fedc90197df6e0e80b0b33e47006#diff-84cbfa352671e0876b41f6f5ccc40ca0R39

**Comment by Valodim** [comment]
Feel free to push to this branch :)

**Comment by philipwhiuk** [comment]
Now we've split off 5.2 are we good to merge this into master?

**Comment by Valodim** [comment]
I rebased this on current master. Would like to see this merged to avoid extra rebasing work and extra bugs that might introduce

**Comment by cketti** [comment]
Continued as #2186

**Pull request closed without merging**
