### PR TITLE
Update the project url contained in the welcome message

### PR DESCRIPTION
**Pull request by jmeinke**
I've just compiled K-9 for the first time and noticed the project url is old (this also relates #761). This commit updates the url to https://github.com/k9mail/k-9/ in all language files.

### CODE REVIEW

**Comment by cketti** [comment]
Thanks for taking the time to fix this! However, we're using [Transifex](https://www.transifex.com/projects/p/k9mail/) for translations. Any changes to `value-*/strings.xml` files in the repository will be lost when translations are pulled from Transifex.

Can you please update this pull request to only change `values/strings.xml`?

**Comment by jmeinke** [comment]
Okay, now only `values/strings.xml` is changed.

**Comment by Djfe** [comment]
@cketti could you pls update the source string, I don't think users are able to do that sadly
https://www.transifex.com/k-9/k9mail/translate/#de/strings/20157568?q=code

**Comment by cketti** [comment]
Thanks @jmeinke. I squashed the commits and merged the change.

https://github.com/k9mail/k-9/commit/ce31e3460cf42880289246c546b2c5a2b533b6de

**Pull request closed without merging**
