### PR TITLE
Authenticate user before showing password

### PR DESCRIPTION
**Pull request by ByteHamster**
Replaces #5541

### CODE REVIEW

**Comment by ByteHamster** [comment]
Yeah, I would sell this as a feature, actually :D

**Comment by cketti** [comment]
I have no strong feelings whether or not we should allow users without a lock screen set up to view the password. But if we don't support it, we need to hide the eye icon.

**Comment by cketti** [comment]
I just checked Chrome and they display a toast saying "To view or copy your password here, set screen lock on this device."
Something like that would work, too.

**Comment by cketti** [comment]
Speaking of Chrome. I like their title ("Verify it's you") and subtitle ("Unlock to view your password") for BiometricPrompt.

**Comment by ByteHamster** [comment]
> I like their title ("Verify it's you") and subtitle ("Unlock to view your password") for BiometricPrompt.

Done

> I just checked Chrome and they display a toast saying "To view or copy your password here, set screen lock on this device."

Also done :)

**Comment by cketti** [comment]
I extracted the code to a separate file and made some changes that seem to make LeakCanary happy.

**Pull request merged**
