### PR TITLE
add gravatar support - closes #4876

### LINKED ISSUE #4876: File attachment name broken - Filename scrambled / wrong encoding
### Expected behavior
I want file attachments in mail drafts/sent mails to be shown and opened correctly even if the filename contains german umlauts (äöü...). I want k9mail to cope correctly even if they have badly encoded filenames.

### Actual behavior
If I add an attachment from k9mail everything works as intended. As soon as I use another client to add a file attachment to a draft email and store it to the imap drafts folder, this attachments name is not properly downloaded via imap from my (gmx) draft folder to k9mail. The same happens if i add the attachment and just send it. k9mail is not showing the mail attachment correctly in the sent mail and in the inbox if I send it to myself.
Instead the filename is scrambled in a more or less URL/percent-encoded way and is shown as a attachment with the name (example) UTF-8''%45%69%6E%76%65%72%73%74%C3%A4%6E%64%6E%69%73%65%72%6B
I also cannot open the file with k9mail.

If I url encode this I get back `UTF-8''Einverständniserk` which is parts of my original file name "Einverständniserklärung.pdf"

I actually add the attachment to the mail draft using Thunderbird 68.10.0 (64-Bit) with Windows OS.
As soon as I sync my imap in k9mail, I can see the mail draft including the broken attachment

Note: When I add attachments without umlaut characters, k9mail shows the attachment name as intended.
Note: When I log on to my email provider web-account the attachment is always shown correctly! So the provider seems to be more robust to such filenames.

### Steps to reproduce
1. use thunderbird (on windows) to add a file attachment with umlauts to some email draft
2. sync the mail account with imap
3. use k9mail to also sync imap
4. watch the draft or to send it to somebody
5. check the attachment file name, it is scrambled

### Environment
K-9 Mail version: 5.600
Android version: 10
Account type (IMAP, POP3, WebDAV/Exchange): imap

### PR DESCRIPTION
**Pull request by ligi**
add gravatar support - about the indent changes in there - I was running astyle with the parameters from:
https://github.com/k9mail/k-9/wiki/CodeStyle - somehow this style is not really enforced - I had a lot of reformatted files after running:

```
➜  k-9 git:(master) ✗ astyle --style=java --indent=spaces=4 --brackets=attach --convert-tabs   --unpad-paren --pad-header --pad-oper --suffix=none --recursive "src/com/fsck/k9/*.java"
------------------------------------------------------------
Directory  src/com/fsck/k9/*.java
------------------------------------------------------------
Formatted  Account.java
Unchanged  AccountStats.java
Unchanged  BaseAccount.java
Unchanged  Clock.java
Unchanged  EmailAddressAdapter.java
Unchanged  EmailAddressValidator.java
Unchanged  FontSizes.java
Unchanged  Identity.java
Formatted  K9.java
Unchanged  NotificationSetting.java
Formatted  PRNGFixes.java
Unchanged  Preferences.java
Formatted  Throttle.java
Unchanged  activity/AccountList.java
Formatted  activity/Accounts.java
Formatted  activity/ActivityListener.java
Formatted  activity/ChooseFolder.java
Unchanged  activity/ChooseIdentity.java
Formatted  activity/ColorPickerDialog.java
Unchanged  activity/ConfirmationDialog.java
Unchanged  activity/EditIdentity.java
Unchanged  activity/EmailAddressList.java
Formatted  activity/FolderInfoHolder.java
Formatted  activity/FolderList.java
Unchanged  activity/FolderListFilter.java
Formatted  activity/InsertableHtmlContent.java
Unchanged  activity/K9Activity.java
Formatted  activity/K9ActivityCommon.java
Unchatted  activity/MessageList.java
Unchanged  activity/MessageReference.java
Formatted  activity/NotificationDeleteConfirmation.java
Unchanged  activity/Search.java
Formatted  activity/UnreadWidgetConfiguration.java
Formatted  activity/UpgradeDatabases.java
Unchanged  activity/loader/AttachmentContentLoader.java
Formatted  activity/loader/AttachmentInfoLoader.java
Formatted  activity/misc/Attachment.java
Formatted  activity/misc/ContactPictureLoader.java
Formatted  activity/misc/ExtendedAsyncTask.java
Unchanged  activity/misc/NonConfigurationInstance.java
Formatted  activity/misc/SwipeGestureDetector.java
Formatted  activity/setup/AccountSettings.java
Unchanged  activity/setup/AccountSetupAccountType.java
Formatted  activity/setup/AccountSetupBasics.java
Formatted  activity/setup/AccountSetupCheckSettings.java
Unchanged  activity/setup/AccountSetupComposition.java
Formatted  activity/setup/AccountSetupIncoming.java
Unchanged  activity/setup/AccountSetupNames.java
Unchanged  activity/setup/AccountSetupOptions.java
Formatted  activity/setup/AccountSetupOutgoing.java
Unchanged  activity/setup/FolderSettings.java
Formatted  activity/setup/FontSizeSettings.java
Formatted  activity/setup/Prefs.java
Formatted  activity/setup/SliderPreference.java
Unchanged  activity/setup/SpinnerOption.java
Formatted  activity/setup/WelcomeMessage.java
Formatted  cache/EmailProviderCache.java
Formatted  cache/EmailProviderCacheCursor.java
Unchanged  controller/MessageRemovalListener.java
Unchanged  controller/MessageRetrievalListener.java
Formatted  controller/MessagingController.java
Formatted  controller/MessagingControllerPushReceiver.java
Formatted  controller/MessagingListener.java
Formatted  crypto/Apg.java
Formatted  crypto/CryptoHelper.java
Unchanged  crypto/CryptoProvider.java
Formatted  crypto/None.java
Unchanged  crypto/OpenPgpApiHelper.java
Formatted  crypto/PgpData.java
Formatted  fragment/ConfirmationDialogFragment.java
Formatted  fragment/MessageListFragment.java
Formatted  fragment/MessageViewFragment.java
Unchanged  fragment/ProgressDialogFragment.java
Formatted  helper/ClipboardManager.java
Unchanged  helper/ContactItem.java
Formatted  helper/ContactPicture.java
Formatted  helper/Contacts.java
Unchanged  helper/FileBrowserHelper.java
Formatted  helper/HtmlConverter.java
Unchanged  helper/IdentityHelper.java
Unchanged  helper/MediaScannerNotifier.java
Unchanged  helper/MergeCursor.java
Formatted  helper/MergeCursorWithUniqueId.java
Formatted  helper/MessageHelper.java
Formatted  helper/Regex.java
Unchanged  helper/SizeFormatter.java
Formatted  helper/StringUtils.java
Formatted  helper/Utility.java
Unchanged  helper/power/TracingPowerManager.java
Formatted  mail/Address.java
Formatted  mail/AuthType.java
Unchanged  mail/Authentication.java
Unchanged  mail/AuthenticationFailedException.java
Unchanged  mail/Body.java
Unchanged  mail/BodyPart.java
Formatted  mail/CertificateChainException.java
Formatted  mail/CertificateValidationException.java
Unchanged  mail/CompositeBody.java
Formatted  mail/ConnectionSecurity.java
Unchanged  mail/FetchProfile.java
Unchanged  mail/Flag.java
Formatted  mail/Folder.java
Unchanged  mail/Message.java
Unchanged  mail/MessagingException.java
Formatted  mail/Multipart.java
Unchanged  mail/Part.java
Unchanged  mail/PushReceiver.java
Unchanged  mail/Pusher.java
Formatted  mail/ServerSettings.java
Formatted  mail/Store.java
Unchanged  mail/Transport.java
Unchanged  mail/filter/Base64.java
Unchanged  mail/filter/Base64OutputStream.java
Unchanged  mail/filter/CountingOutputStream.java
Unchanged  mail/filter/EOLConvertingOutputStream.java
Unchanged  mail/filter/FixedLengthInputStream.java
Unchanged  mail/filter/Hex.java
Unchanged  mail/filter/LineWrapOutputStream.java
Unchanged  mail/filter/PeekableInputStream.java
Unchanged  mail/filter/SmtpDataStuffing.java
Formatted  mail/internet/BinaryTempFileBody.java
Formatted  mail/internet/BinaryTempFileMessageBody.java
Unchanged  mail/internet/DecoderUtil.java
Unchanged  mail/internet/EncoderUtil.java
Unchanged  mail/internet/Iso2022JpToShiftJisInputStream.java
Formatted  mail/internet/MimeBodyPart.java
Unchanged  mail/internet/MimeHeader.java
Formatted  mail/internet/MimeMessage.java
Unchanged  mail/internet/MimeMultipart.java
Formatted  mail/internet/MimeUtility.java
Unchanged  mail/internet/TextBody.java
Formatted  mail/internet/TextBodyBuilder.java
Formatted  mail/store/ImapResponseParser.java
Formatted  mail/store/ImapStore.java
Formatted  mail/store/LocalStore.java
Formatted  mail/store/LockableDatabase.java
Formatted  mail/store/Pop3Store.java
Unchanged  mail/store/StorageManager.java
Unchanged  mail/store/UnavailableAccountException.java
Unchanged  mail/store/UnavailableStorageException.java
Formatted  mail/store/WebDavSocketFactory.java
Formatted  mail/store/WebDavStore.java
Unchanged  mail/store/imap/ImapUtility.java
Formatted  mail/transport/SmtpTransport.java
Unchanged  mail/transport/WebDavTransport.java
Unchanged  mail/transport/imap/ImapSettings.java
Formatted  net/ssl/KeyChainKeyManager.java
Formatted  net/ssl/SslSessionCacheHelper.java
Formatted  net/ssl/TrustManagerFactory.java
Formatted  net/ssl/TrustedSocketFactory.java
Formatted  preferences/AccountSettings.java
Formatted  preferences/CheckBoxListPreference.java
Unchanged  preferences/Editor.java
Formatted  preferences/FolderSettings.java
Formatted  preferences/GlobalSettings.java
Formatted  preferences/IdentitySettings.java
Formatted  preferences/Settings.java
Formatted  preferences/SettingsExporter.java
Unchanged  preferences/SettingsImportExportException.java
atted  activity/MessageList.java
Unchanged  activity/MessageReference.java
Formatted  activity/NotificationDeleteConfirmation.java
Unchanged  activity/Search.java
Formatted  activity/UnreadWidgetConfiguration.java
Formatted  activity/UpgradeDatabases.java
Unchanged  activity/loader/AttachmentContentLoader.java
Formatted  activity/loader/AttachmentInfoLoader.java
Formatted  activity/misc/Attachment.java
Formatted  activity/misc/ContactPictureLoader.java
Formatted  activity/misc/ExtendedAsyncTask.java
Unchanged  activity/misc/NonConfigurationInstance.java
Formatted  activity/misc/SwipeGestureDetector.java
Formatted  activity/setup/AccountSettings.java
Unchanged  activity/setup/AccountSetupAccountType.java
Formatted  activity/setup/AccountSetupBasics.java
Formatted  activity/setup/AccountSetupCheckSettings.java
Unchanged  activity/setup/AccountSetupComposition.java
Formatted  activity/setup/AccountSetupIncoming.java
Unchanged  activity/setup/AccountSetupNames.java
Unchanged  activity/setup/AccountSetupOptions.java
Formatted  activity/setup/AccountSetupOutgoing.java
Unchanged  activity/setup/FolderSettings.java
Formatted  activity/setup/FontSizeSettings.java
Formatted  activity/setup/Prefs.java
Formatted  activity/setup/SliderPreference.java
Unchanged  activity/setup/SpinnerOption.java
Formatted  activity/setup/WelcomeMessage.java
Formatted  cache/EmailProviderCache.java
Formatted  cache/EmailProviderCacheCursor.java
Unchanged  controller/MessageRemovalListener.java
Unchanged  controller/MessageRetrievalListener.java
Formatted  controller/MessagingController.java
Formatted  controller/MessagingControllerPushReceiver.java
Formatted  controller/MessagingListener.java
Formatted  crypto/Apg.java
Formatted  crypto/CryptoHelper.java
Unchanged  crypto/CryptoProvider.java
Formatted  crypto/None.java
Unchanged  crypto/OpenPgpApiHelper.java
Formatted  crypto/PgpData.java
Formatted  fragment/ConfirmationDialogFragment.java
Formatted  fragment/MessageListFragment.java
Formatted  fragment/MessageViewFragment.java
Unchanged  fragment/ProgressDialogFragment.java
Formatted  helper/ClipboardManager.java
Unchanged  helper/ContactItem.java
Formatted  helper/ContactPicture.java
Formatted  helper/Contacts.java
Unchanged  helper/FileBrowserHelper.java
Formatted  helper/HtmlConverter.java
Unchanged  helper/IdentityHelper.java
Unchanged  helper/MediaScannerNotifier.java
Unchanged  helper/MergeCursor.java
Formatted  helper/MergeCursorWithUniqueId.java
Formatted  helper/MessageHelper.java
Formatted  helper/Regex.java
Unchanged  helper/SizeFormatter.java
Formatted  helper/StringUtils.java
Formatted  helper/Utility.java
Unchanged  helper/power/TracingPowerManager.java
Formatted  mail/Address.java
Formatted  mail/AuthType.java
Unchanged  mail/Authentication.java
Unchanged  mail/AuthenticationFailedException.java
Unchanged  mail/Body.java
Unchanged  mail/BodyPart.java
Formatted  mail/CertificateChainException.java
Formatted  mail/CertificateValidationException.java
Unchanged  mail/CompositeBody.java
Formatted  mail/ConnectionSecurity.java
Unchanged  mail/FetchProfile.java
Unchanged  mail/Flag.java
Formatted  mail/Folder.java
Unchanged  mail/Message.java
Unchanged  mail/MessagingException.java
Formatted  mail/Multipart.java
Unchanged  mail/Part.java
Unchanged  mail/PushReceiver.java
Unchanged  mail/Pusher.java
Formatted  mail/ServerSettings.java
Formatted  mail/Store.java
Unchanged  mail/Transport.java
Unchanged  mail/filter/Base64.java
Unchanged  mail/filter/Base64OutputStream.java
Unchanged  mail/filter/CountingOutputStream.java
Unchanged  mail/filter/EOLConvertingOutputStream.java
Unchanged  mail/filter/FixedLengthInputStream.java
Unchanged  mail/filter/Hex.java
Unchanged  mail/filter/LineWrapOutputStream.java
Unchanged  mail/filter/PeekableInputStream.java
Unchanged  mail/filter/SmtpDataStuffing.java
Formatted  mail/internet/BinaryTempFileBody.java
Formatted  mail/internet/BinaryTempFileMessageBody.java
Unchanged  mail/internet/DecoderUtil.java
Unchanged  mail/internet/EncoderUtil.java
Unchanged  mail/internet/Iso2022JpToShiftJisInputStream.java
Formatted  mail/internet/MimeBodyPart.java
Unchanged  mail/internet/MimeHeader.java
Formatted  mail/internet/MimeMessage.java
Unchanged  mail/internet/MimeMultipart.java
Formatted  mail/internet/MimeUtility.java
Unchanged  mail/internet/TextBody.java
Formatted  mail/internet/TextBodyBuilder.java
Formatted  mail/store/ImapResponseParser.java
Formatted  mail/store/ImapStore.java
Formatted  mail/store/LocalStore.java
Formatted  mail/store/LockableDatabase.java
Formatted  mail/store/Pop3Store.java
Unchanged  mail/store/StorageManager.java
Unchanged  mail/store/UnavailableAccountException.java
Unchanged  mail/store/UnavailableStorageException.java
Formatted  mail/store/WebDavSocketFactory.java
Formatted  mail/store/WebDavStore.java
Unchanged  mail/store/imap/ImapUtility.java
Formatted  mail/transport/SmtpTransport.java
Unchanged  mail/transport/WebDavTransport.java
Unchanged  mail/transport/imap/ImapSettings.java
Formatted  net/ssl/KeyChainKeyManager.java
Formatted  net/ssl/SslSessionCacheHelper.java
Formatted  net/ssl/TrustManagerFactory.java
Formatted  net/ssl/TrustedSocketFactory.java
Formatted  preferences/AccountSettings.java
Formatted  preferences/CheckBoxListPreference.java
Unchanged  preferences/Editor.java
Formatted  preferences/FolderSettings.java
Formatted  preferences/GlobalSettings.java
Formatted  preferences/IdentitySettings.java
Formatted  preferences/Settings.java
Formatted  preferences/SettingsExporter.java
Unchanged  preferences/SettingsImportExportException.java
Formatted  preferences/SettingsImporter.java
Formatted  preferences/Storage.java
Unchanged  preferences/TimePickerPreference.java
Formatted  provider/AttachmentProvider.java
Formatted  provider/EmailProvider.java
Formatted  provider/MessageProvider.java
Formatted  provider/UnreadWidgetProvider.java
Unchanged  remotecontrol/AccountReceiver.java
Unchanged  remotecontrol/K9AccountReceptor.java
Unchanged  remotecontrol/K9RemoteControl.java
Formatted  search/ConditionsTreeNode.java
Formatted  search/LocalSearch.java
Formatted  search/SearchAccount.java
Formatted  search/SearchSpecification.java
Formatted  search/SqlQueryBuilder.java
Formatted  security/LocalKeyStore.java
Unchanged  service/BootReceiver.java
Unchanged  service/CoreReceiver.java
Formatted  service/CoreService.java
Formatted  service/DatabaseUpgradeService.java
Formatted  service/MailService.java
Formatted  service/NotificationActionService.java
Unchanged  service/PollService.java
Unchanged  service/PushService.java
Unchanged  service/RemoteControlReceiver.java
Unchanged  service/RemoteControlService.java
Unchanged  service/ShutdownReceiver.java
Formatted  service/SleepService.java
Unchanged  service/StorageGoneReceiver.java
Unchanged  service/StorageReceiver.java
Formatted  view/AttachmentView.java
Formatted  view/ClientCertificateSpinner.java
Unchanged  view/ColorChip.java
Formatted  view/FoldableLinearLayout.java
Unchanged  view/K9PullToRefreshListView.java
Unchanged  view/MessageCryptoView.java
Formatted  view/MessageHeader.java
Formatted  view/MessageOpenPgpView.java
Formatted  view/MessageTitleView.java
Formatted  view/MessageWebView.java
Formatted  view/NonLockingScrollView.java
Formatted  view/RigidWebView.java
Formatted  view/SingleMessageView.java
Unchanged  view/ViewSwitcher.java
Formatted  preferences/SettingsImporter.java
Formatted  preferences/Storage.java
Unchanged  preferences/TimePickerPreference.java
Formatted  provider/AttachmentProvider.java
Formatted  provider/EmailProvider.java
Formatted  provider/MessageProvider.java
Formatted  provider/UnreadWidgetProvider.java
Unchanged  remotecontrol/AccountReceiver.java
Unchanged  remotecontrol/K9AccountReceptor.java
Unchanged  remotecontrol/K9RemoteControl.java
Formatted  search/ConditionsTreeNode.java
Formatted  search/LocalSearch.java
Formatted  search/SearchAccount.java
Formatted  search/SearchSpecification.java
Formatted  search/SqlQueryBuilder.java
Formatted  security/LocalKeyStore.java
Unchanged  service/BootReceiver.java
Unchanged  service/CoreReceiver.java
Formatted  service/CoreService.java
Formatted  service/DatabaseUpgradeService.java
Formatted  service/MailService.java
Formatted  service/NotificationActionService.java
Unchanged  service/PollService.java
Unchanged  service/PushService.java
Unchanged  service/RemoteControlReceiver.java
Unchanged  service/RemoteControlService.java
Unchanged  service/ShutdownReceiver.java
Formatted  service/SleepService.java
Unchanged  service/StorageGoneReceiver.java
Unchanged  service/StorageReceiver.java
Formatted  view/AttachmentView.java
Formatted  view/ClientCertificateSpinner.java
Unchanged  view/ColorChip.java
Formatted  view/FoldableLinearLayout.java
Unchanged  view/K9PullToRefreshListView.java
Unchanged  view/MessageCryptoView.java
Formatted  view/MessageHeader.java
Formatted  view/MessageOpenPgpView.java
Formatted  view/MessageTitleView.java
Formatted  view/MessageWebView.java
Formatted  view/NonLockingScrollView.java
Formatted  view/RigidWebView.java
Formatted  view/SingleMessageView.java
Unchanged  view/ViewSwitcher.java
anged  activity/K9FragmentActivity.java
Formatted  activity/K9ListActivity.java
Unchanged  activity/K9PreferenceActivity.java
Unchanged  activity/LauncherShortcuts.java
Unchanged  activity/ManageIdentities.java
Formatted  activity/MessageCompose.java
Unchanged  activity/MessageInfoHolder.java
Formatted  activity/MessageList.java
Unchanged  activity/MessageReference.java
Formatted  activity/NotificationDeleteConfirmation.java
Unchanged  activity/Search.java
Formatted  activity/UnreadWidgetConfiguration.java
Formatted  activity/UpgradeDatabases.java
Unchanged  activity/loader/AttachmentContentLoader.java
Formatted  activity/loader/AttachmentInfoLoader.java
Formatted  activity/misc/Attachment.java
Formatted  activity/misc/ContactPictureLoader.java
Formatted  activity/misc/ExtendedAsyncTask.java
Unchanged  activity/misc/NonConfigurationInstance.java
Formatted  activity/misc/SwipeGestureDetector.java
Formatted  activity/setup/AccountSettings.java
Unchanged  activity/setup/AccountSetupAccountType.java
Formatted  activity/setup/AccountSetupBasics.java
Formatted  activity/setup/AccountSetupCheckSettings.java
Unchanged  activity/setup/AccountSetupComposition.java
Formatted  activity/setup/AccountSetupIncoming.java
Unchanged  activity/setup/AccountSetupNames.java
Unchanged  activity/setup/AccountSetupOptions.java
Formatted  activity/setup/AccountSetupOutgoing.java
Unchanged  activity/setup/FolderSettings.java
Formatted  activity/setup/FontSizeSettings.java
Formatted  activity/setup/Prefs.java
Formatted  activity/setup/SliderPreference.java
Unchanged  activity/setup/SpinnerOption.java
Formatted  activity/setup/WelcomeMessage.java
Formatted  cache/EmailProviderCache.java
Formatted  cache/EmailProviderCacheCursor.java
Unchanged  controller/MessageRemovalListener.java
Unchanged  controller/MessageRetrievalListener.java
Formatted  controller/MessagingController.java
Formatted  controller/MessagingControllerPushReceiver.java
Formatted  controller/MessagingListener.java
Formatted  crypto/Apg.java
Formatted  crypto/CryptoHelper.java
Unchanged  crypto/CryptoProvider.java
Formatted  crypto/None.java
Unchanged  crypto/OpenPgpApiHelper.java
Formatted  crypto/PgpData.java
Formatted  fragment/ConfirmationDialogFragment.java
Formatted  fragment/MessageListFragment.java
Formatted  fragment/MessageViewFragment.java
Unchanged  fragment/ProgressDialogFragment.java
Formatted  helper/ClipboardManager.java
Unchanged  helper/ContactItem.java
Formatted  helper/ContactPicture.java
Formatted  helper/Contacts.java
Unchanged  helper/FileBrowserHelper.java
Formatted  helper/HtmlConverter.java
Unchanged  helper/IdentityHelper.java
Unchanged  helper/MediaScannerNotifier.java
Unchanged  helper/MergeCursor.java
Formatted  helper/MergeCursorWithUniqueId.java
Formatted  helper/MessageHelper.java
Formatted  helper/Regex.java
Unchanged  helper/SizeFormatter.java
Formatted  helper/StringUtils.java
Formatted  helper/Utility.java
Unchanged  helper/power/TracingPowerManager.java
Formatted  mail/Address.java
Formatted  mail/AuthType.java
Unchanged  mail/Authentication.java
Unchanged  mail/AuthenticationFailedException.java
Unchanged  mail/Body.java
Unchanged  mail/BodyPart.java
Formatted  mail/CertificateChainException.java
Formatted  mail/CertificateValidationException.java
Unchanged  mail/CompositeBody.java
Formatted  mail/ConnectionSecurity.java
Unchanged  mail/FetchProfile.java
Unchanged  mail/Flag.java
Formatted  mail/Folder.java
Unchanged  mail/Message.java
Unchanged  mail/MessagingException.java
Formatted  mail/Multipart.java
Unchanged  mail/Part.java
Unchanged  mail/PushReceiver.java
Unchanged  mail/Pusher.java
Formatted  mail/ServerSettings.java
Formatted  mail/Store.java
Unchanged  mail/Transport.java
Unchanged  mail/filter/Base64.java
Unchanged  mail/filter/Base64OutputStream.java
Unchanged  mail/filter/CountingOutputStream.java
Unchanged  mail/filter/EOLConvertingOutputStream.java
Unchanged  mail/filter/FixedLengthInputStream.java
Unchanged  mail/filter/Hex.java
Unchanged  mail/filter/LineWrapOutputStream.java
Unchanged  mail/filter/PeekableInputStream.java
Unchanged  mail/filter/SmtpDataStuffing.java
Formatted  mail/internet/BinaryTempFileBody.java
Formatted  mail/internet/BinaryTempFileMessageBody.java
Unchanged  mail/internet/DecoderUtil.java
Unchanged  mail/internet/EncoderUtil.java
Unchanged  mail/internet/Iso2022JpToShiftJisInputStream.java
Formatted  mail/internet/MimeBodyPart.java
Unchanged  mail/internet/MimeHeader.java
Formatted  mail/internet/MimeMessage.java
Unchanged  mail/internet/MimeMultipart.java
Formatted  mail/internet/MimeUtility.java
Unchanged  mail/internet/TextBody.java
Formatted  mail/internet/TextBodyBuilder.java
Formatted  mail/store/ImapResponseParser.java
Formatted  mail/store/ImapStore.java
Formatted  mail/store/LocalStore.java
Formatted  mail/store/LockableDatabase.java
Formatted  mail/store/Pop3Store.java
Unchanged  mail/store/StorageManager.java
Unchanged  mail/store/UnavailableAccountException.java
Unchanged  mail/store/UnavailableStorageException.java
Formatted  mail/store/WebDavSocketFactory.java
Formatted  mail/store/WebDavStore.java
Unchanged  mail/store/imap/ImapUtility.java
Formatted  mail/transport/SmtpTransport.java
Unchanged  mail/transport/WebDavTransport.java
Unchanged  mail/transport/imap/ImapSettings.java
Formatted  net/ssl/KeyChainKeyManager.java
Formatted  net/ssl/SslSessionCacheHelper.java
Formatted  net/ssl/TrustManagerFactory.java
Formatted  net/ssl/TrustedSocketFactory.java
Formatted  preferences/AccountSettings.java
Formatted  preferences/CheckBoxListPreference.java
Unchanged  preferences/Editor.java
Formatted  preferences/FolderSettings.java
Formatted  preferences/GlobalSettings.java
Formatted  preferences/IdentitySettings.java
Formatted  preferences/Settings.java
Formatted  preferences/SettingsExporter.java
Unchanged  preferences/SettingsImportExportException.java
Formatted  preferences/SettingsImporter.java
Formatted  preferences/Storage.java
Unchanged  preferences/TimePickerPreference.java
Formatted  provider/AttachmentProvider.java
Formatted  provider/EmailProvider.java
Formatted  provider/MessageProvider.java
Formatted  provider/UnreadWidgetProvider.java
Unchanged  remotecontrol/AccountReceiver.java
Unchanged  remotecontrol/K9AccountReceptor.java
Unchanged  remotecontrol/K9RemoteControl.java
Formatted  search/ConditionsTreeNode.java
Formatted  search/LocalSearch.java
Formatted  search/SearchAccount.java
Formatted  search/SearchSpecification.java
Formatted  search/SqlQueryBuilder.java
Formatted  security/LocalKeyStore.java
Unchanged  service/BootReceiver.java
Unchanged  service/CoreReceiver.java
Formatted  service/CoreService.java
Formatted  service/DatabaseUpgradeService.java
Formatted  service/MailService.java
Formatted  service/NotificationActionService.java
Unchanged  service/PollService.java
Unchanged  service/PushService.java
Unchanged  service/RemoteControlReceiver.java
Unchanged  service/RemoteControlService.java
Unchanged  service/ShutdownReceiver.java
Formatted  service/SleepService.java
Unchanged  service/StorageGoneReceiver.java
Unchanged  service/StorageReceiver.java
Formatted  view/AttachmentView.java
Formatted  view/ClientCertificateSpinner.java
Unchanged  view/ColorChip.java
Formatted  view/FoldableLinearLayout.java
Unchanged  view/K9PullToRefreshListView.java
Unchanged  view/MessageCryptoView.java
Formatted  view/MessageHeader.java
Formatted  view/MessageOpenPgpView.java
Formatted  view/MessageTitleView.java
Formatted  view/MessageWebView.java
Formatted  view/NonLockingScrollView.java
Formatted  view/RigidWebView.java
Formatted  view/SingleMessageView.java
Unchanged  view/ViewSwitcher.java
```

### CODE REVIEW

**Comment by PanderMusubi** [comment]
Does this app exist and where can it be found?

**Comment by PanderMusubi** [comment]
For reference, see also https://code.google.com/p/k9mail/issues/detail?id=4876

**Comment by Valodim** [comment]
different services can be covered by allowing a string configuration for the avatar URI with printf-style formatting, with md5 and sha1 placeholders for the mail address. the binding would only be as tight as a preset for this setting, others can be added trivially.

I think this is actually a pretty nice feature which requires little maintenance - the original patch here is a mere 80 lines of code, after all

**Comment by PanderMusubi** [comment]
Problem with a separate app that enriches only existing email addresses in your contacts, is that Gravatars of people sending you emails who are not in your contacts will not show a Gravatar.

**Pull request closed without merging**
