### PR TITLE
Use correct OpenPGP key when sending signed-only email

### LINKED ISSUE #4914: Wrong OpenPGP key used when sending signed-only email
I have recently noticed that if I set the sending of an email with the openpgp signature only option, I don't have the possibility to choose which identity to use.  k9 v5.718 uses the first signature key available in openkeychain although it is not even that of the email from which I send.  then an email is sent with the address xxx @ xxx signed by a yyyu @ yyy identity how to choose which signature key to use?  I have no choices

### PR DESCRIPTION
**Pull request by GNUDimarik**
Update crypto state when switching accounts in message compose screen.

Fixes #4914

### CODE REVIEW

**Comment by cketti** [comment]
@GNUDimarik: Please read the text of the pull request template and modify your pull request accordingly. 

Note: "update crypto status in RecipientPresenter" is not a great title. I didn't look at your change yet. But from the bug report issue title I'm guessing "Use correct OpenPGP key when sending signed-only email" would be a better title for your pull request.

**Comment by GNUDimarik** [comment]
@cketti  please check once you have a chance

**Comment by cketti** [comment]
I updated the pull request description with a checklist. Please have another look. 

If you plan to contribute regularly, please make life easier for me by following the existing practice. I tried to be very explicit in the pull request template. If the instructions are not clear please let me know and I'll try to improve them.

**Comment by GNUDimarik** [comment]
Thanks a lot. I'll take a look. I just tried to describe change technically
What do you think about the change?

**Comment by GNUDimarik** [comment]
@cketti i'm still wrong please help me to understand why.
Thank you

**Comment by cketti** [comment]
Sorry, I've only gotten to testing your change just now. It seems to work :+1:

This introduces a subtle race condition, though. Users might be able to switch accounts and then hit the send button before the asynchronous load has completed. However, the same is true for all other calls to `asyncUpdateCryptoStatus()`. And it doesn't appear like those have been causing problems in practice. So we'll ignore that for now.

As for the checklist, you did not complete these items:
- Contains a reference to the issue that it fixes (e.g. Closes #XXX or Fixes #XXX) in the body text.
- Finally, please replace this template text with a description of the change and additional context if necessary.

I fixed that for you.

**Comment by cketti** [comment]
Thanks for the fix!

**Pull request merged**
