### PR TITLE
Return first, rather than last, response for pipelined SMTP commands

### LINKED ISSUE #3778: SMTP PIPELINING: K-9 displays wrong reply code and error message
The current implementation of K-9's [SMTPTransport.java](https://github.com/k9mail/k-9/blob/b3c0021edbc8a0d9b73beb2f45eee3fbc21ced33/mail/protocols/smtp/src/main/java/com/fsck/k9/mail/transport/smtp/SmtpTransport.java) returns the last error message instead of the first one.
Consequently, users cannot make an informed decision on how to handle the error, because the true error source is hidden.

[RFC2920](https://tools.ietf.org/html/rfc2920#section-3.1) also demands that "Client SMTP implementations that employ pipelining MUST check ALL statuses associated with each command in a group.".

An example, where a server cannot handle the RCPT TO command and returns 550 but user sees 502:

#### Mailserver's view
 MAIL FROM:<ky@example.com> BODY=8BITMIME
 250 Roger, accepting mail from <ky@example.com>
 RCPT TO:<550@test.rcpt.code>
 **550 Middleware RCPT says 550**
> Server cannot handle the rcpt address and returns error.

 DATA
 502 Missing RCPT TO command.
> Followup error

 QUIT
 221 Goodnight and good luck

#### K9's view
 SmtpTransport: SMTP >>> MAIL FROM:<ky@example.com> BODY=8BITMIME
 SmtpTransport: SMTP >>> RCPT TO:<550@test.rcpt.code>
 SmtpTransport: SMTP >>> DATA
 SmtpTransport: SMTP <<< 250 Roger, accepting mail from <ky@example.com>
 SmtpTransport: SMTP <<< **550 Middleware RCPT says 550**
 SmtpTransport: SMTP <<< **502 Missing RCPT TO command.**
> K9 displays the last error, however, the first error is the **true** source and should get reported to the user.

 SmtpTransport: SMTP >>> QUIT
 SmtpTransport: SMTP <<< 221 Goodnight and good luck

### Expected behavior
K-9 should return all or the first error message.

### Actual behavior
K-9 returns last error message.

### Environment
K-9 Mail version: 5.600

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP,SMTP

### PR DESCRIPTION
**Pull request by Valodim**
Fixes #3778

### CODE REVIEW

**Comment by cketti** [comment]
I don't think this will fix #3778. By the time we reach the (error) response for the "DATA" command we throw and forget about the previous error. I suggest adding the server responses from #3778 as a new test case.

**Comment by Valodim** [comment]
we actually already had such a test, I just missed it :)

**Comment by wiktor-k** [comment]
Hmm... wouldn't it be better to collect all exceptions and pass that collection to the exception that is ultimately thrown? That'd provide a trace of what was happening step by step.

Alternatively at least log each suppressed exceptions, for debugging purposes.

**Comment by Valodim** [comment]
I thought about that as well, but SMTP messages on the wire are already logged so there's not really a point :)

**Comment by wiktor-k** [comment]
Yeah, good point. As far as I can see the [exception building code](https://github.com/k9mail/k-9/blob/fda70cbea7e7e5c8c351bc62c322e45c6d1dbe72/mail/protocols/smtp/src/main/java/com/fsck/k9/mail/transport/smtp/SmtpTransport.java#L688-L713) doesn't add any critical information that couldn't be quickly retrieved from the SMTP message line (3 places for exceptions, one is empty line, two for negative status, that'd be clearly visible in logs).

**Comment by wiktor-k** [comment]
Okay, I'm not an SMTP expert, but this code seems small and contained, LGTM.

**Pull request merged**
