### PR TITLE
Display unread message count on app icon

### LINKED ISSUE #2114: Unread messages count on app dock icon
I would love to be able to see the unread messages count, not only on the home screen widget already provided, but more importantly on the K9 dock icon. Like the default android app, basically.

### PR DESCRIPTION
**Pull request by aviraldg**
Fixes #2114

### CODE REVIEW

**Comment by philipwhiuk** [comment]
As I said originally this only works on certain launchers.

It also seems superfluous given we have a widget that works everywhere.

But it's low maintenance and so I'm not utterly opposed assuming it works as expected.

If people want to turn this off however then it'd be easier to not merge it and say just use the widget.

**Comment by cketti** [comment]
I don't like it. This adds all kinds of permissions. And the library has done [dodgy stuff](https://github.com/leolin310148/ShortcutBadger/issues/22) in the past.

**Comment by aviraldg** [comment]
We use it on `riot-android` and it works fairly well there, so I assumed it'd be okay here as well.

**Comment by Valodim** [comment]
If we can request the permissions at runtime, having this as an option seems like a good feature: We can check if we are on a compatible launcher, only allow enabling the setting if we are, then request permission from the user when they enable it.

**Comment by cketti** [comment]
Weird edge cases. Assuming runtime permissions that aren't granted automatically, what if you enable this, then switch the launcher? You'd have to find out a) the launcher has changed and b) figure out the right moment to request the new permission.

We have the unread widget for regular users. And if people want to get fancy, they can get the unread count via MessageProvider.

**Pull request closed without merging**
