### PR TITLE
Message list: hide footer view if empty

### PR DESCRIPTION
**Pull request by starshipcoder**
Hide the footer view in message list if empty

Before
device-2020-07-30-104008

After
device-2020-07-30-103825

### CODE REVIEW

**Comment by szaimen** [comment]
I mean great if the footer is gone when the message list is empty but why was it needed at all in the first place?
(I would remove it completely)

**Comment by cketti** [comment]
Thanks a lot for your contribution :heart: 

Sorry for the delay in getting this merged.

@szaimen: The footer view is used as a button to fetch more messages from the server ("Load up to X more").

**Comment by szaimen** [comment]
> @szaimen: The footer view is used as a button to fetch more messages from the server ("Load up to X more").

Ah okay, thanks for the clarification!

Could the footer also get hidden if all mails in a specific folder are loaded?
(I can of course open a new issue for that, if you want)
image

**Comment by cketti** [comment]
@szaimen: This change will hide the footer whenever it would have been displayed as an empty view. So your case is covered by this as well.

**Comment by szaimen** [comment]
> @szaimen: This change will hide the footer whenever it would have been displayed as an empty view. So your case is covered by this as well.

Ah okay great! Thanks for for this!

**Pull request merged**
