### PR TITLE
Add esPass MIME type

### PR DESCRIPTION
**Pull request by ligi**
same as with https://github.com/k9mail/k-9/pull/1358 - but for esPass

### CODE REVIEW

**Comment by cketti** [comment]
You can't just make up media types. They have to be registered with IANA: http://www.iana.org/assignments/media-types/media-types.xhtml

See also: https://en.wikipedia.org/wiki/Media_type

**Comment by ligi** [comment]
apple did the same - you have a lot of stuff in the list that is not registred

**Comment by cketti** [comment]
They are using the [vendor tree](https://en.wikipedia.org/wiki/Media_type#Vendor_tree).

**Comment by ligi** [comment]
OK - I submitted a request for registration - follow up here: https://github.com/esPass/tasks/issues/1 - but as far as I was reading a registration is not really needed when using vendor-prefix. Would you merge a PR for application/vnd.espass-espass without registration?

**Comment by ligi** [comment]
espass is now a registered mime-type. In the process it changed to vnd.espass-espass+zip:

http://www.iana.org/assignments/media-types/application/vnd.espass-espass+zip

**Pull request closed without merging**
