### PR TITLE
Fixed issue 2846

### PR DESCRIPTION
**Pull request by jyn514**
Skip invalid input; parse strictly otherwise.
Added a unit test for base64 input.
See [issue](https://github.com/k9mail/k-9/issues/2846) for details.

### CODE REVIEW

**Comment by cketti** [comment]
Please don't create pull requests from your master branch. You now accidentally added an unrelated commit to this pull request.

**Comment by jyn514** [comment]
Understood, I will change this.

**Comment by jyn514** [comment]
Is there way to request only a single commit, or should I make a new branch for every pull request?

**Comment by cketti** [comment]
If you update a branch you created a pull request from the pull request is automatically updated. This is useful because often some kind of change is requested before merging a pull request. At the same time you don't want to accidentally update a pull request. So yes, a new branch per pull request.

Also, please give commits and the pull request a descriptive title (use present tense), e.g. "Avoid crash when parsing email address with invalid encoded word" instead of "Fixed issue 2846".
If you include `Fixes #2846` at the end of the description of the pull request the issue will be automatically closed when the pull request is merged.

**Pull request closed without merging**
