### PR TITLE
add "Manage folders" item to drawer footer

### PR DESCRIPTION
**Pull request by Valodim**
part of #3750 

also gives back a way to get to the folder list, for now :)

### CODE REVIEW

**Comment by cketti** [comment]
It feels weird to disable the "manage folders" option when the unified inbox is selected. Why not hide it?

**Comment by Valodim** [comment]
That probably makes sense. When I made the PR I just wanted a button to get to that activity again. The drawer still isn't ideal in more ways than this, we should get back to that when the other moving parts are done

**Comment by wiktor-k** [comment]
Visibile/invisible is a better idea than enabled/disabled but from what I see it's not a simple change (`withEnabled` exists, `withVisible` doesn't, would probably require removing and adding item on demand).

I'd be leaning towards current behavior in this PR as it's simple and non-obstructing :+1:

**Comment by wiktor-k** [comment]
One thing I'm worried though, in the actual Manage Folders activity I can't actually manage anything as long-press doesn't show menus and the overflow menu items are purely for display. And if managing doesn't work then well... maybe there is no point in showing that activity after all... or is work on that screen also planned Valodim?

**Comment by Valodim** [comment]
Of course, that's why it says "part of" #3750 :)

**Comment by wiktor-k** [comment]
Okay, sorry, I'm processing PRs in linear order :) In this case I approve this.

(I'll be bulk testing everything anyway later...)

**Pull request merged**
