### PR TITLE
Avoid leaking CountingOutputStream.

### PR DESCRIPTION
**Pull request by johnjohndoe**
- Ensure `CountingOutputStream` is closed in `ProgressBodyFactory#copyData`.

### CODE REVIEW

**Comment by cketti** [comment]
`CountingOutputStream` doesn't use any system resources that require to be released explicitly. While closing such `OutputStream`s doesn't hurt, it's not something we usually do (e.g. when using `ByteArrayOutputStream`).

Is there a particular reason you're proposing this change? Lint warning? StrictMode violation?

**Comment by johnjohndoe** [comment]
This popped into my face when I tried out a static analyzer on a rather large codebase like yours. It did not show up too much on my project but quite some here.

**Comment by cketti** [comment]
The people have spoken: https://twitter.com/cketti/status/1461769120756686863

Are you up for changing all usages of `CountingOutputStream` and `ByteArrayOutputStream`?

**Comment by johnjohndoe** [comment]
> Are you up for changing all usages of `CountingOutputStream` and `ByteArrayOutputStream`?

I will take a look if it fits into my lifetime and let you know.

**Comment by johnjohndoe** [comment]
I looked through usages of `org.apache.commons.io.output.CountingOutputStream` and `com.fsck.k9.mail.filter.CountingOutputStream` and adapted these.

**Comment by cketti** [comment]
Thanks :+1:

**Pull request merged**
