### PR TITLE
Optionally suppress notifications for mails matching a pattern

### PR DESCRIPTION
**Pull request by dscho**
I do get a lot of emails. I mean, a _lot_. And to get out of notification hell, I typically disable notifications altogether. However, K-9 is pretty neat in that it is open source, and I gave it a shot to suppress notifications based on regular patterns for the headers.

This is my current attempt, and it seems to do the job for me.

My open questions are:

- Is the code in an okay enough shape?
- Is this feature useful enough for K-9 to ship it as part of the official builds?
- Should this option be hidden behind an "Advanced" button in the notification settings?
- Is it okay to use regular expressions here?
- Are there any ideas how to improve this (e.g. make it prettier, or easier to configure)?

### CODE REVIEW

**Comment by cketti** [comment]
We do want this feature (see #3675). But a lot more work is required to make this ready to be included in the app. 

The most important requirement is a user interface that can be used by the average user. It should probably offer similar functionality like user interfaces to create message filters, i.e. allow specifying conditions like "[subject] [contains] [value]" (with the first two being dropdowns and the last one being a text field).

I don't mind having an "expert option" in the second dropdown that allows matching by regular expression. But it can't be the default. And allowing users to provide a regular expression can cause serious performance problems. So there needs to be a limit on what can be done. See https://swtch.com/~rsc/regexp/regexp1.html

**Comment by dscho** [comment]
I am not really versed in Android programming, and struggled for a couple days with trying to add a Fragment (?) to the Account Notifications settings (actually, one fragment for recipients, one for senders, and one for case-insensitive keywords in the subject to suppress notifications). It seems... complicated. @cketti would you kindly give me a pointer how I could possibly add variable-length lists of things to that settings page?

**Comment by cketti** [comment]
Apologies for not commenting earlier. 

Adding a decent UI for this feature is a lot of work. Both for the implementer and for the reviewer (currently I'm the only one).
And, frankly, it's something I currently don't want to deal with. It's probably best if you maintain a private fork with the functionality you currently have. We'll get to it eventually. But for now other things are more important.

Still, thank you for opening the pull request :heart: It can be used as a starting point once we get serious about adding the feature. It can also be used by people who are fine with using an "expert UI".

**Comment by dscho** [comment]
Even without guidance, I am actually driving the project forward. I did not force-push to _this_ branch in order to avoid cluttering it.

A completely messy state can be seen here: https://github.com/k9mail/k-9/compare/master...dscho:wip

I'm currently banging my head against the problem how to have a dynamically-adjustable `K9ListFragment` in which the muted senders will be presented. (Yes, I stepped away from the idea to have a regex, it works for me, but is too hard to manage. In the end, I want only a checkbox to suppress notifications for mails sent via a mailing list, and a list of sender email addresses for whose mails notifications should be suppressed, then I want to modify the way notifications are presented to add a "mute" option for the mail's sender.)

Maybe we can reopen this PR for that reason, so that other contributors do not think that nobody is working on it?

**Comment by dscho** [comment]
> Adding a decent UI for this feature is a lot of work.

I totally agree. And the documentation is abysmal. And the entire architecture is, well, not exactly as easy as at least _some_ node.js frameworks I encountered. That's why I asked for assistance, but I figured out a lot on my own in the meantime already.

**Comment by dscho** [comment]
> Maybe we can reopen this PR for that reason, so that other contributors do not think that nobody is working on it?

Fine, I will open a new PR.

**Pull request closed without merging**
