### PR TITLE
Show contact avatar in single message notification #2314

### PR DESCRIPTION
**Pull request by Gaelan-Bolger**

### CODE REVIEW

**Comment by Gaelan-Bolger** [comment]
Seems tests are failing due to a NPE when creating Contacts instance in BaseNotifications.createBigTextStyleNotification(). Unfortunately I'm not very fluent in testing yet so I'm not sure how to fix it. I'm thinking Contacts needs to be mocked maybe? Or the Context passed to Contacts.getInstance()?

**Comment by philipwhiuk** [comment]
Robolectric provides a `Context` that can act as a stub for a real Context. You need to add this line:

```
when(controller.getContext()).thenReturn(RuntimeEnvironment.application);
```

to `createFakeController` in `BaseNotificationsTest` (and the appropriate places in the other classes).

It would be nice to see some new tests which verify the behaviour you have written from various responses from `Contacts`. However `Contacts` itself is untested right now.

**Comment by Gaelan-Bolger** [comment]
@philipwhiuk Thanks for the help. It turns out it the call to getAddress on the `Address` instance was also throwing a NPE since the test param was 'null'. I added a createFakeAddress method and got all the tests working.

**Comment by cketti** [comment]
Thanks for working on implementing this feature :+1:

Our code has changed quite a bit since this pull request was created. So it's not easy to apply this to the current code base. The current focus is on creating a new stable release. After that fixing notifications and adding notification-related features is on the agenda and we'll revisit this.

**Pull request closed without merging**
