### PR TITLE
Rewrite LocalFolder.purgeToVisibleLimit

### PR DESCRIPTION
**Pull request by rhari991**
This PR makes the `purgeToVisibleLimit` method in `LocalFolder` more efficient by fetching only the required messages and message fields from the database.

### CODE REVIEW

**Comment by cketti** [comment]
The `MessageRemovalListener` is used to pass deleted messages to `MessagingListener.synchronizeMailboxRemovedMessage()`. The implementation of this interface in the `K9` class uses this `Message` instance to send broadcast intents. See https://github.com/k9mail/k-9/blob/b9c0c92e7435a83a74238a8dd5740eca6364d9ba/k9mail/src/main/java/com/fsck/k9/K9.java#L615 and https://github.com/k9mail/k-9/blob/b9c0c92e7435a83a74238a8dd5740eca6364d9ba/k9mail/src/main/java/com/fsck/k9/K9.java#L572-L591

At least the message properties used there need to be loaded from the database to preserve the current behavior.

**Comment by rhari991** [comment]
@cketti Done

**Comment by Valodim** [comment]
Drat, I hadn't considered this listener when I thought we could get away without loading the message. I really don't like partially loading a message in this way, but also I don't think we should do something like "load all messages to delete into memory".

The number of messages we query here will usually be small, but if it's big we're better off taking a long time than running out of memory.

I pushed a suggestion, please take a look.

**Comment by cketti** [comment]
Valodim's change looks good to me.

On another note: This branch needs to be rebased after merging #2693

**Comment by Valodim** [comment]
done

**Comment by Valodim** [comment]
added a test

**Comment by cketti** [comment]
I merged the code without the test. I'd rather have such functionality tested with an integration test, in particular against a real sqlite. That's far less brittle and ensures the used SQL statements are correct.
For now I think we're better off without test than with a test that mocks everything.

**Pull request closed without merging**
