### PR TITLE
Test and fix database upgrade process

### PR DESCRIPTION
**Pull request by philipwhiuk**
I wrote some tests for DB upgrade.

What I currently test:

* Basic creation of the database works
* Failure throws an ERROR in DEBUG
* Upgrading from V29 produces the same database structure as a fresh install (passes with a new migration step added)

NB: 

1. I basically created a v29 database by deleting stuff until the upgrade worked. I didn't dig through the Git history for an actual v29 database (if it even exists). This isn't why the test breaks though.

2. The tests are still fairly blunt instruments. Basically it's a check that the same named tables, triggers and indexes are created. Should catch most stuff though, especially going forward.

### CODE REVIEW

**Comment by Valodim** [comment]
oh. were those indexes actually missing for some migration paths?

**Comment by philipwhiuk** [comment]
MigrationTo51 destroys them by renaming then dropping the messages table. The new messages table it creates don't get the indexes.

**Comment by cketti** [comment]
I took the liberty of cleaning up the test class.

**Comment by philipwhiuk** [comment]
I think we need to consider this a performance bug fix and put it in the 5.204 release.

**Comment by Valodim** [comment]
Absolutely :+1:

**Comment by korelstar** [comment]
👍 

The next step would be to check if the column definitions of tables, and the content of triggers are equal. This could be easily done using the `sql` column in `sqlite_master`. However, for tables the comparison has to ignore different order of columns. But such a check would be coool and worthwhile!

**Comment by cketti** [comment]
@korelstar: We do love pull requests :)

**Comment by korelstar** [comment]
Sure 😁 
Honestly, I thought about that, too. But I can't tell when I will find some time ... Maybe on weekend ...

**Pull request merged**
