### PR TITLE
Added 20 best pseudonyms for, and the provider itself, mail.com

### PR DESCRIPTION
**Pull request by ployt0**

### CODE REVIEW

**Comment by cketti** [comment]
Is there a reason the mail.com entry is not grouped with the others?

**Comment by ployt0** [comment]
Only because it is not an alias for Mail.com, that is the domain which serves all of its aliases.

**Comment by cketti** [comment]
That doesn't sound like an important distinction :)

**Comment by ployt0** [comment]
I missed that pattern, way better than grouping it with USA

**Comment by cketti** [comment]
Thanks.

**Comment by ployt0** [comment]
Er, okay, is this the fabled limbo where a PR awaits merging with master or is there something wrong still?

**Comment by cketti** [comment]
I squashed the commits and merged the changes from this pull request. You can see that the commit b99b539c20328ca7e90d0f260607518585f06952 closed this issue.

github_pull_request_closed_via_commit

**Comment by Valodim** [comment]
Just for the record, changes like this preserve ownership of the original commits, your changes are now in 7af7d8a3d781f8a9e4863cb40b26ebafd632a83b

**Pull request closed without merging**
