### PR TITLE
ugly support of html signatures; issue #794

### PR DESCRIPTION
**Pull request by Raigedas**

### CODE REVIEW

**Comment by cketti** [comment]
Thanks for taking the time to create a pull request!
However, I don't like the user experience of this. Having users write HTML on a mobile device is painful. Moreover, I don't want users to be able to include arbitrary HTML in their signatures.

**Comment by Raigedas** [comment]
Not sure how thoroughly you have checked this so please let me elaborate.
First, I completely agree with you that manually writing HTML is painful especially on mobile devices. Second - for this reason I have made this "feature" optional. And third - i have made it disabled by default, so by default we would have original behavior. Only users those who absolutely need this feature (like those in corporate environments) would enable it. I saw that there are actually such users (other than me) for whom the ability to have HTML signatures is a must, who are forced to use other software if there is no such feature here.

Of course anyone can create and maintain their own forks of the application in a way whatever they like. But I personally think it is not good for users if there are available multiple almost-identical or very similar applications with slightly different feature sets. So in this case IMHO the benefits (not lost users, less overall maintenance) of including the feature would weigh out the "cost" (just additional checkbox for users who do not need this and a tiny increase in binary size).

So, please reconsider taking into account the new (if any) information I have provided and please let me know what you think.

**Comment by Raigedas** [comment]
By the way... I did not quite understand what you meant with "don't want users to be able to include arbitrary HTML in their signatures". It seems like you want to protect someone from sending ill-formated HTML. Like protecting children. As always, I think that it is better not to take away freedom from people but to help them make well-informed decisions. Again, sorry if I misunderstood you here.

**Comment by cketti** [comment]
Making everything a setting is not a solution but a source of many of the problems K-9 Mail is facing. So we're avoiding this as much as possible.

I don't see the danger of long-lived popular forks that add features in a questionable way. Hasn't happened in the past, isn't likely to happen in the future.

Are you suggesting that we only allow people who make well-informed decisions to write emails? Or are you suggesting that we have to live with the fact that there's a good chance other email clients won't be able to read messages because people don't make well-informed decisions when composing them?

**Comment by Raigedas** [comment]
Ok, so I see that the difference of how we would like go forward comes from a little bit different evaluation of costs and benefits. I must say that initially I did not think deeply about all the possible problems which may be caused by the "Making everything a setting". But even now after you raised my attention on this, I still do not envision lots of problems. I would be grateful if you could point me to any existing threads where this issue (big amount of customizations causing many problems to K-9) is being discussed.

I was not suggesting that or anything, I was just stating opinion that freedom is important.

Regarding uglyness and "adding features in a questionable way". I agree that the simple way I have implemented this feature/setting is not very convenient, not very user friendly to say the least. But let me say that I was a little bit shocked when I just saw the same feature implemented in exactly the same way in one of the most (if not the most) popular opensource desktop email client Thunderbird. Of course one could argue that there is a big difference between writing HTML on desktop and on mobile, but please do not forget that this needs to be done only once during account setup.

However, could you please give your recommendations on how we should go forward from this? I agree that in ideal world we should have the HTML signature feature implemented with WYSIWYG editor. But we live in not an ideal world, we do have only a limited supply of developers/time. Developers, implementing stuff they need themselves and sharing that with the rest of the world. What would be  your advice for all the other users who absolutely need the feature now, not a few months or years later? Thank you.

**Comment by cketti** [comment]
I'm not sure what you're asking for. Do you want to know what the functionality needs to look like so we would merge it? Or do you want to know what my recommendation is for developers who "solved the problem" but don't have the time to do it in a way that satisfies our merging criteria?

**Pull request closed without merging**
