### PR TITLE
Shorten code

### PR DESCRIPTION
**Pull request by ligi**
Not much shorter - but every line in this >3000 LOC class which is gone is a good line ;-)
Also this way resolveTitle() could be moved outside this class and save a dozen more lines ..

### CODE REVIEW

**Comment by philipwhiuk** [comment]
We lose 2 lines, true. But we gain a function call every time we call the method.

The file is huge. But tweaking around the edges isn't the way to fix this. 

If we move out all the static Intent constructors for example we'd save a lot more lines and keep the complexity of the code the same.

**Comment by ligi** [comment]
A function call is cheap and this method is only called once in onCreate 
Sure 2 lines is not much but A penny saved is a penny earned .. also this way you can easily move the function in a separate class now and gain a dozen more lines

**Comment by cketti** [comment]
You can get rid of the `switch` statement by adding the string resource to the enum.

```java
    enum Action {
        COMPOSE(R.string.compose_title_compose),
        REPLY(R.string.compose_title_reply),
        REPLY_ALL(R.string.compose_title_reply_all),
        FORWARD(R.string.compose_title_forward),
        EDIT_DRAFT(R.string.compose_title_compose);

        private final int titleResource;

        Action(@StringRes int titleResource) {
            this.titleResource = titleResource; 
        }

        public int getTitleResource() {
            return titleResource;
        }
    }
```

Then `setTitle()` becomes:
```java
    private void setTitle() {
        setTitle(mAction.getTitleResource());
    }
```

**Comment by ligi** [comment]
Nice idea - doing now exactly this

**Pull request merged**
