### PR TITLE
Client ID Security added for IMAP and SMTP

### PR DESCRIPTION
**Pull request by AmadeusAbdulla**
--------
General:
--------

This patch introduces new "Client ID" security technology to K-9 mail. This technology allows for an extra layer of security surrounding a unique identifier sent as an IMAP or SMTP command.

Our intention is to allow K-9 mail to send client ID commands at the SmtpTransport and ImapConnection level. This will enable servers and domains that support client ID to apply to add support for users who use K-9 mail.

The RFCs for client ID in draft form can be found here:

* SMTP: https://tools.ietf.org/html/draft-storey-smtp-client-id-06

* IMAP: https://tools.ietf.org/html/draft-yu-imap-client-id-01#section-3.1

The two unique identifiers used in this implementation are the device imei and if this is not found (eg: tablet with no mobility SIM card) the accountUuid.

----------
Rationale:
----------

How we achieve Client ID integration:

1) Retrieve the unique identifiers and store them in the Account class as member variables

2) Enable access to the unique identifiers in the SmtpTransport and ImapConnection classes

3) Verify that the connection objects at the SmptTransport and ImapConnection have "CLIENTID" as a capability 

4) Send the "CLIENTID" command and handle any client ID specific errors that may result 

5) Display the client ID to users in Account Settings 

--------------
Summary Of Changes:
--------------

* Added a checkPhoneStatePermission() method which prompts the user to allow us to access their imei for client ID security purposes. 

	* This occurs only once on a fresh installation of the app (requires READ_PHONE_STATE permission)

	* If the user grants permission the imei is stored physically using the storageEditor class

	* If the user does not grant permission the imei is stored as null and the accountUuid is used instead

* Added an imei parameter to the Account constructor so our unique identifier can be stored inside each account
	
	* When we retrieve accounts on launching the app we now also retrieve their associated imei if it has been saved

* Added setters to the Preferences class to set the accountUuid and imei in ImapBackendFactory
	
	* This allows us to use the Account object to pass the imei and accountUuid to ImapConnection and SmtpFactory classes for use in commands

* Created method(s) to set and get client ID error flags in MessagingException for error handling
	
	* This allows us to have messages for client ID command specific failures in account setup, refreshing the mailbox, or sending a message
	* The original K-9 error messages will remain for all non client ID command failures

* Added checks to set and detect error flags for client ID commands in ImapConnection and SmtpTransport classes

* Added push notifications / dialogs with client ID specific error messages triggered by these error flags

* Added capability / extensions / and secureConnection checks to ensure we only send client ID commands when advertised by the server

* Added a client ID page to view details (not editable) in Account Settings

--------------
Checks:
--------------

* follows existing codestyle (x)
* passes all JUnit tests (x)

--------------
UI Changes:
--------------
Below is the added menu option for viewing client ID in account settings:

Client_ID_Account_Settings

Below is the client ID details page which allows users to view their current client ID value if it is stored:

Client_ID_Details

### CODE REVIEW

**Comment by gdt** [comment]
It does not yet seem clear that these drafts are a good idea, and thus it seems very premature to consider merging this into k-9.  This is an individual draft, not a working group draft, which means that while published by the IETF, it has no official standing.  The PR incorrectly refers to it as an RFC, which it is not.

The drafts lack discussion of the privacy consequences of sending IMEI to mail servers.  Users who uderstand should reject this, so having a prompt and option seems unwise.

It's really not clear what security benefit sending an IMEI is, since there is no basis to assume that it is secret, and indeed it is exactly the same kind of shared not-really-secret information that a reused password is.

I don't understand why people who want security beyond username and password, tied to a device, don't use something like client certificates.

Overall, I don't think this is appropriate to merge.

**Comment by gdt** [comment]
Also, it would be good to understand if there are IMAP and SMTP servers that implement this, and the relationships among those, companies using them, the draft authors, the PR author, and similar.  Could you disclose any relatonships?

**Comment by linuxmagic-mp** [comment]
All comments are welcome, and for the record, the RFC drafts are still looking for a home amongst working groups at the IETF.  The draft does not specify 'what' the CLIENTID token should be, this is left up to the implementor, but is meant to be unique enough to identify the device/client being used.  

However, the 'purpose' of CLIENTID token is to help address the world wide problems with legacy email protocols, and their weakness in terms of password re-use, and distributed brute force attacks. In a perfect world, only the owner of an email account should be able to access it.  However, the idea of a password being enough to identify that is no longer valid.  With the email address being public information, and the password which MAY have been revealed, and/or brute forced, legacy email protocols were not designed to handle the modern challenges.  And since we are not yet at a stage where we can uniquely identify the human who should have access to an email resource, at least we can help identify the devices that human owns, uses, and considers approved to access their email accounts. While there are many attempts to address this problem, many solutions are either not workable in the real world, or require a complete change to the underlying protocols.  

CLIENTID is a simple way to deal with these challenges, in a completely backwards compatible manner.
CLIENTID is currently supported by all MagicMail platforms, and work is under way on both various email clients, as well as other server implementations, however it is not our place to disclose 3rd party release plans.  While the makers of MagicMail are also behind the RFC Drafts, and strong proponents of a worldwide adoption for CLIENTID, this should have no bearing on the validity of using CLIENTID, or of the value of this patch.  The team is also contributing to that effort by assisting various opensource projects and contributing code and patches to facilitate support for it.  This patch allows k9 users who have an email account which supports CLIENTID to use K9, as well as taking advantage of this to further protect/restrict access. In today's world, legacy methods of identifying devices (eg, IP Address, EHLO) are no longer viable, with things like Carrier Grade Nat, and mobile connectivity. The ability to 'authorize' approved devices, or to prevent authentication/access attempts from unknown or unauthorized devices is essential, in a way that is natively supported.

As 'technical' people, while you may not understand why people don't use 'say, client certificates', we have to understand that for the average email user, we need to make security LESS complicated, not more, which is why email clients should have the ability to present a unique identifier as part of the connection protocols without requiring human intervention. People however understand, "I want only my home computer, my tablet, my phone, and my office computer" to access my email account, and NOT some random computer in some far flung country they never visit.

We believe this technology will help the world, and efforts like this (offering patches for open source projects) will help encourage adoption.

**Comment by gdt** [comment]
Stepping back from process, my technical concerns are
  - IMEI should not be used at all. The very existence of this identifier is already a major privacy problem, and while that's not your fault, every use of it makes things worse.  The draft does not really address this issue, and certainly does not have adequate security discussion.  Given that the mechanism just needs a string which is unique, it seem best to avoid known identifiers.
  - This is basically adding a per-device password that the user doesn't manage.  There is then a question of where this comes from, and how it is registered with the server, and kept secret.   And then how revocation and supercession are handled.  I admit to skimming the draft, but I did not see discussion of these issues.

As for process: Reading between the lines, it seems your (proprietary software?) mail server is, the sole server-side implementation of these drafts.  Is that accurate, or are there more?

**Comment by cketti** [comment]
In general I don't want to expose things that are still under development to regular users. I'm not opposed to adding support for promising protocols/protocol features while they're still a draft. But there would have to be an opt-in mechanism that makes it clear it's functionality only meant to be used by advanced users.

That being said, I don't think this is a promising feature. The main purpose for this client ID seems to be security. But like @gdt said, it's just another secret stored in a client. The only scenario I can think of where having a client ID is better than not having it, is where the password leaks, but not the client ID. The most likely case for such a leak is password reuse and the password is leaked by another service. But if that other service is using the same client ID mechanism with static device identifiers and those client IDs leak as well, the mechanism is equally bad as simple passwords. So unless someone is using strictly one device per service we can immediately see that using static device identifiers is a bad idea.
This proposal requires changes to both clients and servers, but offers very little benefit. A much easier way to prevent password reuse is to have the server generate the credentials used for SMTP/IMAP, see e.g. Google's app-specific passwords. You'll still need a way to authenticate to such a service that's immune to password reuse across services. But Client IDs don't solve that problem either. 
If we're requiring changes to both clients and servers a much better approach would be to switch to something like OAuth.

If the goal is to track which device a client is running on, this proposal is inadequate as well. Because once the client ID is known it's easy to transfer it to another device. It'd be more like a voluntary device identification. In which case user-provided identifiers would make more sense.
Due to the privacy implications it's very unlikely we'd ever enable something like this by default. Also, there'd have to be massive user demand for us to even consider adding such an (optional) feature.

**Comment by linuxmagic-mp** [comment]
For the record, believe this was closed prematurely, without enough input from the k9 community.  Hoping for the ticket to be re-opened, however cketti suggests for now, comments continue to go on the pull request.

**Comment by d-g** [comment]
linuxmagic-mp wrote:
> this was closed prematurely, without enough input from the k9 community.
> however cketti suggests for now, comments continue to go on the pull request.

While I do not represent ‘K-9 community’ in whatever sense, as you insist on more comments, here’s my two cents: _kill it with fire_.

linuxmagic-mp wrote:
> while you may not understand why people don't use 'say, client certificates'

I believe, I do understand: by the same reason they don’t, say, sign and encrypt their mail — software they use do not nudge them to do it.

> we have to understand that for the average email user, we need to make security LESS complicated, not more

So you tried to make it _more_ complicated by inventing another protocol, that adds nothing to existing stack?

I guess, if one had really cared about end-users’ security, rather than about advertising his nonfree program by the means of pioneering some protocol, he would implement public cert auth server-side¹ and address his effort in patching MUAs to make its setup seamless.

¹ Your ‘Magic mail’ still does not support it [0], does it?

[0] https://www.google.com/search?gbv=1&q=site%3Amagicmail.com+certificate

**Pull request closed without merging**
