### PR TITLE
Issue #1988, escape special character in content ID replacement for Migration51

### PR DESCRIPTION
**Pull request by lazycodeninja**
This fixed the upgrade issue I was having moving from 5.0x to 5.1+  .  

I've taken a quick look at the code base and don't see any other similar issues.  I've used `Matcher.quoteReplacement()` but I see that the same problem was addressed in `TextQuoteCreator:49` by manually escaping the replacement string with a replaceAll() call.  I'm not sure if that was done deliberately because there's an issue with `Matcher.quoteReplacement()` or the author was just unaware of the method.

### CODE REVIEW

**Comment by philipwhiuk** [comment]
Probably the later.

But the odd thing is that contentID is supposed to be a URI. And that shouldn't have a \ or $ in it anyway. I can only assume someone is breaking the spec.

**Comment by philipwhiuk** [comment]
I presume you got something like:

```
java.lang.IllegalArgumentException: Illegal group reference

	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at java.lang.String.replaceAll(String.java:2223)
	at com.fsck.k9.mailstore.migrations.MigrationTo51.replaceContentUriWithContentIdInHtmlPart(MigrationTo51.java:395)
```

**Comment by lazycodeninja** [comment]
Thank you for adding test cases, that was sloppy of me not to add some but I didn't see similar test classes for the other Migration classes and I wasn't sure how straightforward it would be to set up. 

 
I actually got an ArrayIndexOutOfBoundsException, see the stack trace below:
```
Exception while upgrading database. Resetting the DB to v0
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	at java.util.regex.Matcher.group(Matcher.java:343)
 	at java.util.regex.Matcher.appendEvaluated(Matcher.java:626)
 	at java.util.regex.Matcher.appendReplacement(Matcher.java:601)
 	at java.util.regex.Matcher.replaceAll(Matcher.java:700)
 	at java.lang.String.replaceAll(String.java:2164)
 	at com.fsck.k9.mailstore.migrations.MigrationTo51.replaceContentUriWithContentIdInHtmlPart(MigrationTo51.java:393)
```
The content ID that caused this in my case was `cid:707f20be$1$13d5c82b5cf$Coremail$ei-30$vip.126.com` (which, based on that domain, unfortunately means that it was some spam rubbish that caused me this trouble and I could have simply deleted it from the mailbox instead and perhaps never encountered the problem again).

**Comment by philipwhiuk** [comment]
Yeah, if it was simple I'd have requested changes. I was going to just approve. 
Instead I spent quite a while writing one so that the code's better going forward :+1:

**Comment by cketti** [comment]
@lazycodeninja: Thanks a lot for tracking down the bug and coming up with a fix. I changed the implementation from `String.replaceAll()` to `String.replace()` which avoids the need to use quoted/escaped strings.

@philipwhiuk: Thanks a lot for the tests. Having done a lot of Kotlin lately, I couldn't resist the temptation to convert them to Kotlin.

**Pull request merged**
