### PR TITLE
Don't bother handling an intent in MessageList if we're finishing anyway

### LINKED ISSUE #1875: Crash: NPE in MessageList.decodeExtras()
Via Play Developer Console
App version: 5.200

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
	at com.fsck.k9.activity.MessageList.decodeExtras(MessageList.java:485)
	at com.fsck.k9.activity.MessageList.onNewIntent(MessageList.java:258)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1212)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1224)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2545)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2557)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2566)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1416)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

### PR DESCRIPTION
**Pull request by philipwhiuk**
Should fix #1875

### CODE REVIEW

**Comment by cketti** [comment]
Did you manage to trigger that exception? I don't believe `onNewIntent()` can be called when the Activity is in the process of finishing.

**Comment by philipwhiuk** [comment]
The way I see it, the only plausible explanation is that during creation:

https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/activity/MessageList.java#L202

returned true so

https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/activity/MessageList.java#L219

wasn't called so

mActionBarSubject was null

I think it's the same deal as the createOptionsMenu thing - it's a lifecycle event outside of create/destroy/pause/resume so it can be triggered even when finish() has been called.

But no I've not reproduced it. It's just to me, logically, the only plausible explanation for why mActionBarSubject is null.

**Comment by Valodim** [comment]
Actually... https://github.com/WhisperSystems/Signal-Android/commit/31224014ccb4621921103a2de1c03f9129ad46d1

**Comment by cketti** [comment]
Ok. So the `MessageList` Activity is started, realized the database needs upgrading, starts the `UpgradeDatabases` Activity, which probably finishes right away because the upgrade has been complete, before finishing it starts the original Activity causing `onNewIntent()` being called because the instance is reused.
By avoiding the crash we probably end up on the home screen because all our Activities have been finished. But what we really want is going back to the `MessageList` activity. Maybe using `FLAG_ACTIVITY_CLEAR_TASK` will do the trick and not reuse the finishing Activity.

**Pull request merged**
