### PR TITLE
handle encrypted parts in multipart/alternative

### LINKED ISSUE #1901: can't decrypt MIME encoded message, error from OpenKeychain
Sorry, I don't know whether this belongs here, but somewhere I have to begin ...

I have an encrypted mail, in m

ulti-part message MIME format, text, html and an (unencrypted) pdf attachment. 
K9 mail (5.200) tries to decrypt it with OpenKeychain, but fails and displays the MIME text unchanged.
This is what I get from logcat:

```D/k9      (28235): MessageView displaying message MessageReference{accountUuid='941dcfeb-a9f6-49cb-8056-94b66ecba3e1', folderName='INBOX', uid='107910', flag=null}
D/k9      (28235): Creating new local message loader
D/k9      (28235): OpenPGP API decryptVerify result code: 2
D/OpenGLRenderer(27929): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
V/WindowManager( 2638): Adding window Window{10174949 u0 org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.remote.ui.RemotePassphraseDialogActivity} at 13 of 19 (after Window{29f4167a u0 com.fsck.k9/com.fsck.k9.activity.MessageList})
I/OpenGLRenderer(27929): Initialized EGL, version 1.4
D/OpenGLRenderer(27929): Enabling debug mode 0
V/k9      (28235): conn63347625<<<#null# [OK, Still here]
V/k9      (28235): Got async response: #null# [OK, Still here]
V/k9      (28235): conn634925872<<<#null# [OK, Still here]
V/k9      (28235): Got async response: #null# [OK, Still here]
D/k9      (28235): OpenPGP API decryptVerify result code: 1
D/k9      (28235): Creating new decode message loader
D/k9      (28235): No external images.
D/skia    (28235): --- SkImageDecoder::Factory returned null
D/skia    (28235): --- SkImageDecoder::Factory returned null
D/OpenPgp API(28235): Stopped writing due to broken pipe (other end closed pipe?)
D/OpenPgp API(28235): Stopped writing due to broken pipe (other end closed pipe?)
```

Unfortunately, I can't upload a privatized version of that mail. WIll be available at request

### Environment
K-9 Mail Version 5.2.00

Android version:
Fairphone Open Os 5.1 (based on AOSP 5.1)

Account type is IMAP

### PR DESCRIPTION
**Pull request by Valodim**
When people paste a pgp/inline encrypted text into MUAs that send html mails by default, that text often ends up as the first part in a `multipart/alternative`. So far we only considered the first part, or the first part of a multipart/mixed as candidates for the displayed root part. This PR now also considers the first part of `multipart/alternative`, if it has pgp/inline content.

fixes #1901 and #1960

### CODE REVIEW

**Comment by philipwhiuk** [comment]
1. Won't we just display the unencrypted (and possibly blank) HTML in that case anyway? I seem to remember in a multipart/alternative situation we always prefer HTML right now if it exists.
2. Do we still decrypt non-primary parts? multipart/mixed is supposed to all be displayed so I assume we'd have to decrypt every encrypted multipart/mixed part at some point to display it all?

Say if you had:

```
multipart/mixed:
    encrypted
    image/png
    encrypted
```

what would happen?

(This is more a technical interest question that specifically approval of this commit, which seems like a good improvement - especially as 2 is a massively unlikely edge case)

**Comment by Valodim** [comment]
1. The text/plain part within the multipart/alternative becomes the primary part of the mail, so that is definitely displayed.

2. We do!

Regarding your example, we have a very restrictive set of parts we consider candidates for primary: the root part, the first part of a multipart/mixed, and the first part of a multipart/alternative. So the primary part would be the first bit of the multipart/mixed, everything else is listed as attachments.

**Comment by Valodim** [comment]
cketti with them extra tests. nice :+1:

**Comment by bronf** [comment]
Hi,

I use K9 5.203 on Android 4.4.2.
I have coupled K9 with OpenKeychain for encryption.
When my colleague sends me encrypted html emails from thunderbird/enigmail on Windows, I cannot read them in K9. I can read them very well in Thunderbird/enigmail on linux.

What I see in K9 is just an encrypted text:
-----BEGIN PGP MESSAGE-----
Charset: utf-8
Version: GnuPG v2

hQIMA7Fbpziio4
...

Apparently, it seems to be close to what is described here. Now if I look at the source of the message, here is what I get:

This is a multi-part message in MIME format.
--------------452D6D8A55323BDE0E7331EF
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable


-----BEGIN PGP MESSAGE-----
Charset: utf-8
Version: GnuPG v2
=20
hQIMA7Fbpziio4J6ARAAmXDAWKensof0HnoxQuyF+4K5VXHglo8kSD1Ov3ozP5EA
...
-----END PGP MESSAGE-----


--------------452D6D8A55323BDE0E7331EF
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit

<html>
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
  </head>
  <body bgcolor="#FFFFFF" text="#000000">
    <br>
    -----BEGIN PGP MESSAGE----- <br>
    Charset: utf-8 <br>
    Version: GnuPG v2 <br>
    Â <br>
    hQIMA7Fbpziio4J6ARAAmXDAWKensof0HnoxQuyF+4K5VXHglo8kSD1Ov3ozP5EA <br>
...
    -----END PGP MESSAGE----- <br>
    <br>
  </body>
</html>

--------------452D6D8A55323BDE0E7331EF--

**Comment by philipwhiuk** [comment]
This PR hasn't been released yet. It'll be in 5.204

**Pull request merged**
