### PR TITLE
Replaced most icons with vector drawables

### PR DESCRIPTION
**Pull request by hendrikbl**
I replaced most of the icons used in throughout the app with material design vector xml icons.

### CODE REVIEW

**Comment by cketti** [comment]
Have you tried running this on devices that don't natively support vector drawables?

**Comment by hendrikbl** [comment]
> Have you tried running this on devices that don't natively support vector drawables?

I've tested it using API 16 on a virtual device and it worked just fine.

**Comment by cketti** [comment]
Please move the vector drawables to `drawable-anydpi` (see https://commonsware.com/blog/2015/12/21/nodpi-anydpi-wtf.html).

Why did you rename the files? Having e.g. `ic_email_open_dark` instead of `ic_action_mark_as_read_dark` seems like a step back. Especially since "open" and "mark as read" are not really the same thing.

**Comment by hendrikbl** [comment]
Please move the vector drawables to drawable-anydpi


Seems like a smart thing to do, I'll do that.

Why did you rename the files?


I renamed the files because one or two were the same icons but for different actions which means there were basically duplicate files. So my idea was to use names that describe the image instead of the action it is used for and use the assigned name from theme.xml to describe the action. I hope that makes sense.

But I'm happy to rename them again if that's how it should be done.

**Comment by cketti** [comment]
> I renamed the files because one or two were the same icons but for different actions which means there were basically duplicate files. So my idea was to use names that describe the image instead of the action it is used for and use the assigned name from theme.xml to describe the action. I hope that makes sense.

I see. Sounds like a good idea :+1:
However, it doesn't seem to be very consistent right now. E.g. `ic_delete_dark` instead of `ic_trash_can_dark`. Also, sometimes confusing. I mistook `ic_email_open_dark` for an action. Maybe that one could be `ic_opened_envelope_dark` instead.

**Comment by hendrikbl** [comment]
I moved all the files I changed to `drawable-anydpi` and renamed some files so they better describe the icon. I couldn't find perfectly fitting names for every icon, so some of them might still be a little confusing...

**Comment by cketti** [comment]
Thanks!

**Pull request merged**
