### PR TITLE
Closes #4127 by changing sha-1 to sha-512

### LINKED ISSUE #4127: Display Sha512 Fingerprints for Server-Certs
### Expected behavior
If my mailserver uses a self-signed cert, k9 should display the sha512 fingerprint of the cert

### Actual behavior
I only see sha1 fingerpint

### Environment
K-9 Mail version: 5.600
Android version: 8.1

### PR DESCRIPTION
**Pull request by GNUDimarik**
Please ensure that your pull request meets the following requirements - thanks !

* Follows our existing [codestyle](https://github.com/k9mail/k-9/wiki/CodeStyle).
* Does not break any unit tests.
* Contains a reference to the issue that it fixes.
* For cosmetic changes add one or multiple images, if possible.

### CODE REVIEW

**Comment by GNUDimarik** [comment]
I had no chance to test it because it could not to find JMAP server for my emails ... I trying to find out why ...

**Comment by GNUDimarik** [comment]
Thanks for update.
Once i able to test it i'll add the PR.
Btw how do you currently test it during development? What do you use with
jmap support?

пт, 14 авг. 2020 г., 16:49 cketti <notifications@github.com>:

**Comment by cketti** [comment]
This code is unrelated to JMAP. It is only used for IMAP, POP3, SMTP and maybe WebDAV servers.

**Comment by GNUDimarik** [comment]
Right. But i can't loging to the app at all... Finding out ...

**Comment by cketti** [comment]
Make sure to launch `k9mail.app.k9mail` in Android Studio, **not** `k9mail.app.k9mail-jmap`.

**Comment by GNUDimarik** [comment]
Thanks.
Now it's better. Will continue working then

**Comment by GNUDimarik** [comment]
> Thanks for looking to contribute to K-9 Mail ❤️
> 
> Browsers show the SHA-1 and SHA-256 fingerprint of certificates. We should also do that.
> 
> I don't mind if we show the SHA-512 fingerprint as well. But only showing the SHA-512 value (when nobody else seems to do that) is not an option. So this PR should be changed to show the SHA-512 value in addition to the SHA-1 value. Ideally, you'd also add the SHA-256 value.

So you mean to put 3 different hashes there ideally. RIght? PLease confirm

**Pull request closed without merging**
