### PR TITLE
compare flag in MessageReference equals method

### PR DESCRIPTION
**Pull request by fabienli**
Please ensure that your pull request meets the following requirements - thanks !

* Follows our existing [codestyle](https://github.com/k9mail/k-9/wiki/CodeStyle).
seems OK.
* Does not break any unit tests.
got 129 passed, but 4 ignored (?)
* Contains a reference to the issue that it fixes.
Fixing the issue https://github.com/k9mail/k-9/issues/4658

### CODE REVIEW

**Comment by cketti** [comment]
Can you write a few sentences on what code is causing the problem and how this change fixes it?

**Comment by fabienli** [comment]
Investigating the issue https://github.com/k9mail/k-9/issues/4658 I happened to see the following behavior:
When clicking on the "edit quoted message" pencil, we want to reload the message edited, with the quoted message now editable.
The LocalMessageLoader.java > startOrResumeLocalMessageLoader() method checks if we reuse the local message loader, for this, it checks whether the currently loaded MessageReference is the same as the new one. (check done by loader.isCreatedFor(messageReference) ).
The MessageReference is bascially the same (we're still editing the same draft message), but the Flags are not identical. However, the checks on messageReference instance was not comparing the Flag attributes, thus not reloading the edited message; and the quoted message remains un-editable.
The proposed fix is then to compare the Flag attribute in MessageReference.java > equals(...), so that LocalMessageLoader.java can now identify that we need to reload the message (this time the quoted message is correctly editable).

**Comment by cketti** [comment]
Thanks for the write-up :+1:

The intention of the `MessageReference` check is to not load the same message twice. The proposed change works against that. What broke the feature is not this check, but the one I added with PR #4576. It prevents the "load finished" callback to be triggered more than once for the same message.

Actually, it's not necessary to load the message again when the edit button is clicked. I'm guessing the original author wrote it like this because it was an easy way to call `MessageCompose.loadLocalMessageForDisplay()` again after setting `forcePlainText` to `true`.
But we can accomplish the same thing by remembering the last `MessageViewInfo` value passed to `loadLocalMessageForDisplay()`. Then calling the method with the saved value when the edit button is clicked.

Do you want to take another stab at fixing the problem? If not, I'm happy to work on a fix myself.

**Comment by cketti** [comment]
See #4670

**Comment by fabienli** [comment]
Hi,
I think I'm late, as I've just noticed you fixed it with commit: https://github.com/k9mail/k-9/commit/560003234ff2b941c5ec6a89b9e5efc6875bfb6d .
I'll try faster next time :-)
Cheers !

**Comment by cketti** [comment]
Sorry for taking this opportunity to contribute away from you. I went ahead and did it myself because I haven't heard back from you. I didn't expect you to come up with a patch in 3 days. A short message that you intended to work on it would have been enough for me to wait.

The good news is that there are lots of bugs in K-9 Mail :wink: Maybe you'll find another one that you would like to fix.

**Pull request closed without merging**
