### PR TITLE
socks_proxy rebase with master

### PR DESCRIPTION
**Pull request by ndew623**
I'm interested in working on the proxy feature if this rebase is an ok starting point. I noticed proxy support was a potential GSOC project. I don't want to step on any toes, but since I don't see any recent issues mentioning proxies I figured no one was working on it.

### CODE REVIEW

**Comment by philipwhiuk** [comment]
You've used `git merge` not `git rebase` to bring socks_proxy up to date. hence the ridiculously large number of commits. Please re-do.

**Comment by ndew623** [comment]
I used `git rebase`. What is the expected result? A single commit? I'm new to git. I realize this isn't a help forum for git but maybe you can see where I'm going wrong here.
This is exactly the process I followed (k9mail is the alias for this repo, origin is the alias for my repo):
`git checkout socks_proxy`
`git reset --hard k9mail/socks_proxy`
`git push origin --force`
`git rebase k9mail/master`
repeatedly used `git status`, `git add -u`, and `git rebase --continue` to find and resolve conflicts
`git push origin --force`
Now this PR is closed because apparently force pushing does that. Regardless, the result in my origin repo is still a huge number of commits, and a new PR would look exactly like this one.
Thanks for your patience and help!

**Comment by philipwhiuk** [comment]
I'd expect the same number of commits that are on the socks_proxy branch. I saw a lot of commits that are already on master.

**Comment by Valodim** [comment]
This is *almost* right, but you need to create the PR against master, not against socks_proxy. The expected amount of commits is just the six commits from #1181.

**Pull request closed without merging**
