### PR TITLE
iCal (ICS) support

### PR DESCRIPTION
**Pull request by philipwhiuk**
So I've improved this PR, rebased it etc etc. I added support for insecure iCal parts (when I originally wrote the PR I didn't understand `extraParts`. I made some slight refactoring to make it clearer what extra parts were). I don't want to show every possible thing in the iCal spec - that's the point of a calendar app. I've just made it usable for the stuff you get in a typical event.

This PR still only supports **reading** the common iCal events. It doesn't support responding to them inside K-9. Outlook has a nice 'Accept / Tentative / Decline' thing which I'm tempted to implement. But that can be a separate PR - this stands up fine on it's own.

You can still download and open the iCal file corresponding to an event in Google if you want to.

### CODE REVIEW

**Comment by cketti** [comment]
I haven't yet looked at this very closely. But I saw a couple of FIXME comments and that's why I added the "don't merge" label.

@philipwhiuk: Can you please add screenshots to show off the feature.

Small note: There's no need to add a license file for a library whose source code doesn't live inside our repository.

**Comment by philipwhiuk** [comment]
The FIXME comments are mostly marking code that was already commented out. But I'll take a look and see why they were commented out before and fix it.

**Comment by philipwhiuk** [comment]
screenshot_20180119-000353

**Comment by Valodim** [comment]
rebased on current master. I dropped the locked ical events, this is fallback anyways so showing those as locked attachments is fine.

I dislike how much code this adds, but it *is* a cool feature, especially if we have 1) automatic input into calendar, 2) quick accept/reject replies.

**Comment by KlavsKlavsen** [comment]
this would be really really nice to have

**Comment by cketti** [comment]
Love the idea. But I feel a feature like this needs more UI/UX design work upfront.

**Pull request closed without merging**
