### PR TITLE
Always send IP instead of hostname in HELO/EHLO

### PR DESCRIPTION
**Pull request by Valodim**
Clients are very often behind NATs, which makes the hostname in HELO/EHLO messages virtually useless these days. Attempting to figure out a hostname we could use also led to issues with some strict Postfix
configurations (see #3387). This PR changes our behavior to simply send the local IP always.

### CODE REVIEW

**Comment by cketti** [comment]
Why remove the privacy setting? This leaks the internal IP if the client is behind a NAT gateway or proxy.

**Comment by artbristol** [comment]
This looks like it will fix the issues mentioned.

I'm trying to work out if exposing the local IP address (from NAT) is a privacy risk in this case. It's sent before STARTTLS kicks in. There was a fuss about WebRTC leaking it a while ago https://hacking.ventures/local-ip-discovery-with-html5-webrtc-security-and-privacy-risk/ but I'm not convinced it's relevant here.

**Comment by Valodim** [comment]
If the privacy concern is valid, why not behave like that by default?

**Comment by artbristol** [comment]
I guess the previous method of returning "localhost" is technically invalid per the SMTP spec

```
The domain name given in the EHLO command MUST be either a primary
      host name (a domain name that resolves to an address RR) or, if
      the host has no name, an address literal, as described in
      Section 4.1.3 and discussed further in the EHLO discussion of
      Section 4.1.4.
```

so if the user wants to maybe break things in the name of their privacy, then they can do that, but by default we shouldn't behave that way

**Comment by cketti** [comment]
I believe quite a few servers reject "localhost". We could try using `[127.0.0.1]` by default.

**Comment by Valodim** [comment]
> so if the user wants to maybe break things in the name of their privacy, then they can do that, but by default we shouldn't behave that way

I really dislike settings like that, because they are lose-lose: Either the user feels bad because they aren't choosing to preserve their privacy, or they choose to, forget about it and things might break mysteriously. If there is any way at all to just behave sanely without a setting, we should take it.

I'd be fine with a static [127.0.0.1], [192.168.0.2], or something like that.

**Comment by cketti** [comment]
Let's go with `[127.0.0.1]` for IPv4 and `[IPv6:::1]` for IPv6 and test with large email providers.

**Comment by maedoredyti** [comment]
I will test it but when will be the new K9 on F.Droid ?

**Comment by maedoredyti** [comment]
I will tell you what is the problem. I fought with it log time ago and checking local address/hostname is not a simple two lines of code. You must iterate through interfaces and find the interface you are actually connected through.
`````
  for (Enumeration<NetworkInterface> en = NetworkInterface.getNetworkInterfaces(); en.hasMoreElements();) {
    NetworkInterface intf = en.nextElement();
    for (Enumeration<InetAddress> enumIpAddr = intf.getInetAddresses(); enumIpAddr.hasMoreElements();) {
      InetAddress inetAddress = enumIpAddr.nextElement();
      if (  (!inetAddress.isLoopbackAddress()) && (inetAddress instanceof Inet4Address)  ) {
        myipaddress = inetAddress.getHostAddress().toString();
        byte[] IPA = inetAddress.getAddress();
        ByteBuffer bbf = ByteBuffer.wrap(IPA);
        IPCAN = (long)bbf.getInt() & 0xFFFFFFFFL;
        bbf.clear();
        no_interface = 0;
        return;
      }
    }
  }
`````

**Comment by cketti** [comment]
@maedoredyti: We're not interested in the address of the actual loopback interface. We're using the typical addresses of loopback interfaces as dummy argument to the EHLO command. That should satisfy the requirements of RFC 5321 for EHLO without potentially leaking an internal name or IP address.

**Pull request merged**
