### PR TITLE
Managed configs

### PR DESCRIPTION
**Pull request by Zusel**
ManagedConfigs

New functions:

Automatic configuration of the app when the MDM sets the necessary configs. If not enough is set, the profile is not created automatically but the user is sent to the manual setup. In the manual setup, however, the set settings are then also suggested. The password can not be transferred with and must be entered in all cases by the user!

For automatic setup of the account the following is needed:
If imap wanted:
- imapServer
- imapPort
- smtpServer
- smtpPort
- email

if pop3 is wanted:
- pop3Server
- pop3Port
-smtpServer
-smtpPort
-email

The following settings can be made by the MDM:

//IMAP
imapServer
imapSecurity
imapPort
imapUsername
imapAuthentication
autoDetectImapNamespace
imapPrefix
compressionOnMobile
compressionOnWiFi
compressionOnOther

//SMTP
smtpServer
smtpSecurity
smtpPort
requireSignIn
smtpUsername
smtpAuthentication

//POP3
pop3Server
pop3Security
pop3Port
pop3Username
pop3Authentication

//GENERAL
notifyMeWhenMailArrives
accountName
senderName
email
accountType

//Folder
archiveFolder
draftFolder
sentFolder
trashFolder

### CODE REVIEW

**Comment by ASLLR** [comment]
Hi, 
i reopen this issue with : https://connect.mozilla.org/t5/ideas/configure-thunderbird-android-with-mdm/idi-p/84436#M45484 i think this is not available.

**Comment by WassimDhib** [comment]
Hi @Zusel
any new on this issue ? 

We a re a team of developers and we want to integrate Managed configs in Thunderbird mobile.

**Comment by Zusel** [comment]
Hey, I haven’t been working for the company I did that for in quite a while. That’s why I unfortunately don’t know the current state of things anymore. So I’m afraid I can’t help with that.

**Comment by WassimDhib** [comment]
Thanks

What is the company name ? I will try to contact them.

From your own expérience, did your développements (in this pull request)
work for managing configuration with an mdm ?

The pull request was not merged. Dou you know why ?

Thanks for yout time.

**Comment by Zusel** [comment]
I don’t think the company will be able to help with that since it was a city administration, and they don’t do software development. Back then, I developed it in the early stages, and I was also in contact with the developer at that time. He told me that the code quality just wasn’t very good. I can totally understand that, because I was still very new to software development back then. And yes, it worked :) I believe it’s still being used to this day.

**Pull request closed without merging**
