### PR TITLE
Move setting "showAnimations" to generalSettings and refactor ViewSwitcher

### PR DESCRIPTION
**Pull request by schlagi123**
- move setting "showAnimations" to GeneralSettings
- translate ViewSwitcher to kotlin
- refactor ViewSwitcher

### CODE REVIEW

**Comment by schlagi123** [comment]
@cketti If I find time in the next days, I would move one by one of the settings in the `GeneralSettingsManager`. Is this ok for you or should I wait with that?

**Comment by cketti** [comment]
This is a difficult topic, for two reasons. 

1. I want K-9 Mail to have a better separation between the "core" and the user interface. In the future it should be possible to use the core and build a new UI on top of it, also one that doesn't work anything like the current UI. To achieve that we need to push all UI-related things out of core and into the UI module(s), including settings. Many of the things inside of `K9` are UI-related. So they should probably live in a class called `GeneralUiSettings` in the UI module. But it might also be a good idea to split the UI into multiple modules. So we might need multiple more specialized settings classes. I'm still working out how to best approach this.

2. More often than not, the `K9` object is used at the wrong layer. Simply changing `K9.someProperty` to `generalSettingsManager.getSettings().someProperty` only makes this more obvious. Because now we'll have to inject `GeneralSettingsManager` into classes that clearly should be configured externally and not read the settings directly. `ViewSwitcher` is a good example. I find the code reads worse when `GeneralSettingsManager` is used but the code isn't changed to push reading the settings to the proper layer.

Doing (2) is **a lot** of work because at least two layers have to be touched. Most of the time it also requires extensive refactoring to create the proper layering because our UI code is… not great. 

Given all that, I want to keep the settings as-is for now.

---

In general, your contributions to K-9 Mail are very much appreciated! Is there an area in particular you'd like to work on? I'd be happy to dig up and/or create some issues for you. 
If you don't have a preference, I suggest improving the "show headers" screen. It is a fairly isolated piece of code and I have lots of ideas for it. Let me know if you're interested and I'll write them down.

**Comment by schlagi123** [comment]
@cketti Time is the problem for me in most cases. I have no preferences, but in Android UI I'm not so good, because I'm a web- and backend-developer. So the best for me are small tasks (for the motivation to do it on weekend or after my work).

**Comment by cketti** [comment]
Here are a couple of issues that should be rather small in scope:
- #5800
- #5767
- #5755

**Pull request closed without merging**
