### PR TITLE
Pick a contrasting foreground for drawer account chips

### PR DESCRIPTION
**Pull request by williamvds**
Uses the greatest contrasting color from the Material Drawer's background colors
This makes the chip icon more visible against lighter backgrounds 

Some screenshots:  
dark background
light background

### CODE REVIEW

**Comment by ByteHamster** [comment]
I think this could get too colorful. In my opinion, an app should have only very few different colors on one screen. What do you think about using just black and white foregrounds, depending on how light the account color is?

**Comment by cketti** [comment]
I don't know. It looks weird to have a mixed set of icons with light and dark foregrounds.

Currently the account header background is bothering me a lot more. I'd welcome experiments using different approaches. Maybe with different gradients or entirely without gradient. Using very light or dark versions of the account color as background so there's more contrast to the account icon. Or using the account color as header background and icon foreground color and (depending on the theme?) a light or dark background color for the account icons.

**Comment by williamvds** [comment]
Darkening the color seems to be effective, though I'm not sure about it aesthetically

accountchipcontrastdarkening

(Background gradient disabled to act as a reference for the original color)

Algorithm:
```java
float[] hsv = new float[3];
Color.colorToHSV(bg, hsv);
while (Utility.contrastRatio(fg, bg) < 3) {
    hsv[2] *= .9f;
    bg = Color.HSVToColor(hsv);
}
```

**Comment by Valodim** [comment]
might be my screen, but that text is pretty hard to read

**Comment by wiktor-k** [comment]
> might be my screen, but that text is pretty hard to read

I think that's what they were referring to in "though I'm not sure about it aesthetically" :)

**Comment by williamvds** [comment]
Yep, the background's gradient was disabled so the original color is obvious. Normally the gradient makes it more legible  
I'm not sure about it aesthetically because the method of picking the  darker color is rather dumb, and could use ones that don't work well  
There's probably a way to find nicer darker versions of a color, then the one that passes a minimum contrast could be used

**Comment by morckx** [comment]
If you just want a darker tinted background you can decrease the grey values in [drawer_header_background.xml](https://github.com/k9mail/k-9/blob/e9d3c14ff8d5399f80daf45291a440c3183bebd0/app/ui/src/main/res/drawable/drawer_header_background.xml). There you can also get rid of the gradient. 

I'm on the one hand quite happy with the gradient, but, on the other hand, often think that it's a bit too much. Maybe a darker tint without gradient would be a good compromise.

**Comment by ByteHamster** [comment]
I created some mock-ups. The account itself is the same on every image: white foreground and 50% black background. Personally, I think a plain background looks boring. Additionally, it feels too "strong", meaning too much area of the same color.

In every case, the contrast of the account image seems to be good.

## Plain color
  

## Multi-Gradient
 

## Material paper

**Comment by Valodim** [comment]
The last one looks really nice, I like that :+1:

**Comment by ByteHamster** [comment]
I just added another one with plain background and a big, slightly darker email icon.

**Comment by cketti** [comment]
> The last one looks really nice, I like that

I like the "Material paper" version, too. Does it work well with K-9 Mail's default account colors? Or should we change what we use as default account colors? They're probably still Holo-based anyway.

**Comment by ByteHamster** [comment]
A problem I see with my mockup is that the actual account color is no longer used. It's just using the dark versions. Is that a good idea?

**Comment by morckx** [comment]
> A problem I see with my mockup is that the actual account color is no longer used. It's just using the dark versions. Is that a good idea?

My reasons for using a darkened version of the account colors were that other colors seem quite arbitrary and potentially misleading, and that when there is a photo for the account, the account color will be nowhere present in the drawer.

Can't you tint your material paper background with the account color just like it's done now, by only replacing the background drawable?

(Another idea to have at least the account color present was to have a colored circle around the photo, but that seemed neither ideal nor easy to implement.)

**Comment by ByteHamster** [comment]
> Can't you tint your material paper background with the account color just like it's done now, by only replacing the background drawable?

Yes but in order to support yellow, we need to use a quite dark background image. To provide contrast for the account chip, we also need to darken the chip color. Therefore, the original (not darkened) color is never used.

Yellow is the only color that creates problems. What about just providing a discrete number of colors, without including yellow (or just some darker shade)? Google calendar also just supports a limited number of colors. Then we can use the actual color for the background and account chips without darkening.

**Comment by williamvds** [comment]
Apologies for the lack of clarity - I wasn't suggesting that the background gradient be removed, it was simply removed when I took that screenshot so that you could compare the original account color with the one used in the chip

But while the conversation has derailed into the drawer background, might I suggest this:

drawerbackgroundproposal

Pros:
- uses the original account color
- text & account icon are legible
  - the gradient should probably end a bit darker

Cons:
- still looks a bit simple?
  - could be used in combination with one of @ByteHamster's suggestions

**Comment by ByteHamster** [comment]
I like the horizontal gradient because it allows to use the actual account color. I think that it's a good step forward. Replacing the background with paper or mail icon can be done after fixing the account icons.

Did you add the gradient to the image or was it possible to enable a gradient using the drawer itself?

**Comment by morckx** [comment]
> Did you add the gradient to the image or was it possible to enable a gradient using the drawer itself?

(If you mean me)  The gradient is defined  [here](https://github.com/k9mail/k-9/blob/e9d3c14ff8d5399f80daf45291a440c3183bebd0/app/ui/src/main/res/drawable/drawer_header_background.xml)

and this is the whole commit: https://github.com/k9mail/k-9/commit/e9d3c14ff8d5399f80daf45291a440c3183bebd0

**Comment by ByteHamster** [comment]
I wondered if the gradient in @williamvds screenshot is added by simply removing the angle or by using something that's included in MaterialDrawer

**Comment by ByteHamster** [comment]
I just checked out your branch. Looks nice. 

I think adding the material paper background AND the gradient might be too much. The gradient itself looks interesting enough and it works with all colors. :+1:

**Comment by wiktor-k** [comment]
I'd also vote for "Material Paper", it looks very professional. Gradients are OK, not bad, but Material Paper is IMHO the best :+1:

**Comment by morckx** [comment]
I also like the "Material Paper" background best. @ByteHamster: Do you have a source for it that we could use (with a suitable license)?

**Comment by ByteHamster** [comment]
@morckx Unfortunately not. I just took the image for the mockup from Google images :P If everyone agrees that we want to use that background, I can create a similar one in Inkscape

**Comment by ByteHamster** [comment]
Looks like Android <24 does not support gradients in paths. Therefore, adding the material paper can not be done with xml vector drawables. @cketti would you also accept a background in png (+svg source) format?

**Comment by cketti** [comment]
> @cketti would you also accept a background in png (+svg source) format?

Sure, that's fine.

**Comment by ByteHamster** [comment]
I added the material paper background in PR #3851

**Comment by wiktor-k** [comment]
:thinking: should this be closed because of #3851?

**Comment by ByteHamster** [comment]
The original issue this fixes (white avatar on yellow chip background) is not yet fixed. #3851 is only about the background of the drawer.

I talked to cketty a few days ago and he told me that he'd prefer restricting the possible account colors on the settings screen instead of allowing to select yellow and then display another color. 

Maybe we could use a color picker similar to the one Google Calendar uses. Other suggestion would be just a bunch of colored circles like this:
https://github.com/kristiyanP/colorpicker

**Comment by wiktor-k** [comment]
Oh, right, now I see the thread was hijacked to discuss two things at once, thanks for the clarification @ByteHamster!

The colorpicker you linked to looks nice.

**Comment by cketti** [comment]
With PR #3851 merged the original issue shouldn't be a problem anymore.

**Pull request closed without merging**
