### PR TITLE
Add oauth2 support for gmail and outlook

### PR DESCRIPTION
**Pull request by Monkey-Matt**
This is an updated PR to fix the merge conflicts of the [previous xoauth2 PR](https://github.com/k9mail/k-9/pull/4832)

Relates to #655 

Note that Gmail support requires updating the google client id (and potentially package name) in `common/build.gradle`.
Use the google console to create OAuth 2.0 Client IDs: https://console.cloud.google.com/apis/credentials

Also worth considering this adds a dependency on retrofit which isn't used by k9 anywhere else.

### CODE REVIEW

**Comment by Rennarde1312** [comment]
Hi, any chance to see this merged ?

**Comment by hockeymikey** [comment]
These changes aren't working for me currently. Tried a merge of it on main and adding an account gets stuck on the "Checking incoming server settings" screen for both incoming and outgoing. Testing this with an outlook university account. Settings are correct and it works in Thunderbird. Gmail doesn't work either, client ids are correct. Nothing stands out to me in the logs. I'll try to investigate more later.

**Comment by drt24** [comment]
Is this going anywhere? MFA/XOAUTH2 has become mandatory with my employer and so I can no longer use k9 mail.

**Comment by starshipcoder** [comment]
For information, the use of webview for authentication is discouraged by google and could not work anymore in future.
https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html

I make it work with https://github.com/openid/AppAuth-Android

If mainteners are interested in adding oauth2, I could do a PR and provide help for the google certification process

**Comment by Krzmbrzl** [comment]
As has been mentioned in the corresponding issue (https://github.com/k9mail/k-9/issues/655#issuecomment-1057870347) already, using this authentication method will become mandatory by the end of this month. Therefore, it would be really awesome, if the work on this could be finished by then :rocket:

**Comment by D4v1dH03** [comment]
> using this authentication method will become mandatory by the end of this month.


Please read carefully. It says **May 30th**, not March 31st.

**Comment by Krzmbrzl** [comment]
Oops, my bad. Thanks for correcting me. The main argument stands though: if this is not merged in the near future, we'll have a problem with gmail.

**Comment by cheggerdev** [comment]
Any updates on this topic?

**Comment by cheggerdev** [comment]
Are there any updates on this topic?

**Comment by D4v1dH03** [comment]
> Are there any updates on this topic?

Would you stop repeating yourself and spamming our inboxes, thank you.

**Comment by cheggerdev** [comment]
@cketti Do you plan to finish #6013 and #6021 before you merge this? If so, do you think this is feasable before the deadline?

**Comment by cheggerdev** [comment]
@cketti Looking at the commits you are doing: well done. Great work!
Now we are in May and Google's deadline is coming closer. Are the requisites done for merging this feature?

**Comment by cketti** [comment]
Superseded by #6082

A big thank you to everyone who worked on this :heart: 
I was able to copy a few things. Some things I implemented differently.

**Pull request closed without merging**
