### PR TITLE
Clean up message list menu

### PR DESCRIPTION
**Pull request by cketti**
Before:
k9mail_old_message_list_toolbar k9mail_old_message_list_toolbar_expanded

After:
k9mail_new_message_list_toolbar k9mail_new_message_list_toolbar_expanded

### CODE REVIEW

**Comment by ByteHamster** [comment]
On the first sight, the compose icon looks like an unread email (toggle unread? Show unread list?). Maybe adding a little plus sign somewhere in that icon would make it more clear.

**Comment by cketti** [comment]
Or maybe use the pen icon instead? 
pen icon

**Comment by ByteHamster** [comment]
Yeah, that's definitely easier to recognize!

What about using a FAB? It could be colored in the account color, so users can directly see which account they are in (now that there no longer are the colored chips next to each message). I think it would also look quite nice and material ;) There already is an empty list item in the bottom of each list (that shows a ripple effect even if it does not do anything), so if you increase the height of that item, the FAB does not cover the messages.

**Comment by hoellen** [comment]
Are the icons from fontawesome? If so, I would suggest the `edit` icon:
grafik

**Comment by cketti** [comment]
The icons are from https://material.io/resources/icons/

**Comment by cketti** [comment]
@ByteHamster: A FAB is probably a bit more work than I want to take on myself right now. But since I mostly use K-9 Mail to read messages I'd want a way to disable it. And in that case we'll need an icon in the toolbar.

If there are no objections, I'll go with the pen icon for now. We can change it later if we find something that matches the current icon style but is a better fit for "compose email".

**Pull request merged**
