### PR TITLE
added RFC2231 parameter decode function into MimeUtility.unfoldAndDecode

### PR DESCRIPTION
**Pull request by sksthrs**
About issues #1466 .

Major mail applications (Thunderbird, Apple mail) uses RFC2231 for encoding filenames in Content-Disposition, but k9mail doesn't handle them.
This is very troublesome for non-English (like Japanese) users because many attachments are broken in filenames.

This PR resolves that issue.
Unit tests are based on real Content-Disposition.

### CODE REVIEW

**Comment by cketti** [comment]
Awesome. Thanks a lot. I'll have a closer look at this soon.

Did you copy the code from somewhere or write it yourself?
I think we should include the examples from RFC 2231 in the tests as well.

**Comment by sksthrs** [comment]
I wrote by myself (no copy).

Should I add test from RFC2231 ? (it's okay)
notice : An example in RFC2231 remains wrong. (See errata : https://www.rfc-editor.org/errata/eid590 )

**Comment by sksthrs** [comment]
Added tests for examples in RFC2231.

And I found a bug in de-quoting. so fixed.

**Comment by cketti** [comment]
Sorry, it has taken so long to give you some feedback. But here it goes:
- It looks like this approach to parsing header parameters was inspired by `MimeUtility.getAllHeaderParameters()`. Unfortunately, the method of splitting the header at all occurrences of a semicolon is flawed. The same goes for dealing with quoted values. A better approach is to write a parser that properly takes context into account. Think of supporting something like `value="one;two"`.
- I don't like the API. First decoding the parameters then encoding them as a String that can be handled by `MimeUtility.getHeaderParameter()` feels very wrong. I think we should have something analog to `MimeParameterEncoder`. Feed it the header value as string and get back an object holding the main value and a map of parameters.
- To keep track of bytes okio's `Buffer` class is better suited than `List<Byte>`.

**Comment by cketti** [comment]
Superseded by PR #3570.

**Pull request closed without merging**
