### PR TITLE
Korean(ko) translation

### PR DESCRIPTION
**Pull request by Uni-**

### CODE REVIEW

**Comment by cketti** [comment]
Thanks for your contribution! However, we use Transifex to handle our translations. Please update the Korean translation there: https://www.transifex.com/projects/p/k9mail/

**Comment by Uni-** [comment]
@cketti, Sorry that I didn't know that (because I had submitted translation patches via GitHub, months ago.) I'll try to get it familiar soon. Thank you for your hard work!

**Comment by jberkel** [comment]
it looks like transifex should be able to offer a git/github integration, so that work is not duplicated unnecessarily.

**Comment by cketti** [comment]
You could use Transifex' command line tool to push changes to Transifex. But that would overwrite any changes made using their web interface since the last time we pulled translations from Transifex.

**Comment by jberkel** [comment]
i don't know how transifex works internally. it's just a shame to turn down translation PRs (and there have been quite a few) because the tool we use doesn't offer any proper integration with common version control systems.

**Comment by cketti** [comment]
Transifex automatically picks up the master language (values/strings.xml) from Github and we can pull the changes in the Git repository using the Transifex command line tool.
In my opinion there's no need for two way synchronization (Transifex<->Github). As soon as you do that you have to deal with merge conflicts.

**Comment by jberkel** [comment]
That might be the case but forcing potential contributors to use another site instead of just submitting plain PRs just seems wrong to me. Ideally Transifex should just import translation updates from PRs (rationale: no need to learn another tool). And translation conflicts should be a lot less frequent than code conflicts.

**Comment by cketti** [comment]
Few translators actually know how Git/Github works. We've had a lot more contributions since we moved to Transifex.

@jberkel If you're volunteering to resolve merge conflicts I'm happy to give you push access to Transifex.

**Pull request closed without merging**
